/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Frontier.Issue4Pesin.ManeLowerBound
import Mathlib.Probability.Martingale.Convergence

/-!
# Pesin part 2, node N-L1-RN: the Layer-1 conditional-density martingale step (foliation-free)

This file isolates and proves **sorry-free** the abstract measure-theoretic core of the one
sub-step of Mañé's Proposition 7.7 that the recon flagged as node `N-L1-RN`: the convergence,
and sub-exponential-rate decay, of the **conditional-density martingale** `r_n := μ(Pₙ)/ν(Pₙ)`.

## What N-L1-RN actually is, and what it does NOT need

In Mañé's proof (Contractor *The Pesin Entropy Formula*, §7, Prop. 7.7) the only place a martingale
enters is the splitting
`(1/n) log μ(Pₙ(x)) = (1/n) log ν(Pₙ(x)) + (1/n) log (μ(Pₙ(x)) / ν(Pₙ(x)))`,
whose **last term tends to `0` a.e.** The ratio `r_n(x) = μ(Pₙ(x))/ν(Pₙ(x))` is, atom by atom along
the refining partition `Pₙ`, exactly the value of the conditional expectation of the
Radon–Nikodym density `g := dμ/dν` with respect to the σ-algebra `ℱ n` generated by `Pₙ`:
`r_n(x) = (ν[g | ℱ n]) x`. By the a.e. Lévy upward / L¹-martingale-convergence theorem
(`MeasureTheory.Integrable.tendsto_ae_condExp`) this converges a.e. to the `ℱ_∞`-measurable
`g = dμ/dν`, a finite limit; where `g > 0` the real-analytic tail
`rate_log_div_tendsto_zero_of_tendsto_pos` (already landed in `ManeLowerBound`) sends
`(1/n) log r_n → 0`.

**The decisive observation: this martingale step is purely measure-theoretic.** It refers only to a
filtration `ℱ : Filtration ℕ m0` on the ambient measurable space, an integrable density
`g : Ω → ℝ`, and the conditional expectations `ν[g | ℱ n]`. It needs **no foliation, no leaf
measure `ν` as a geometric object, no unstable manifold `Pₙ`** — the partition's only role is to
*generate* the abstract filtration `ℱ`, and the leaf measure's only role is to be the *base*
measure against which `g = dμ/dν` and the conditional expectations are taken. Thus N-L1-RN admits a
faithful, fully general statement that this file lands sorry-free. A future SMB/Mañé proof
consumes `condDensity_log_rate_tendsto_zero` directly, supplying `ℱ` = (partition-generated
filtration), the base measure = leaf volume `ν`, and `g` = `dμ/dν`.

## Main results

* `condExp_tendsto_ae` — the bare a.e. martingale convergence of the conditional-density sequence
  `(ν[g | ℱ n]) x → g x`, a direct specialisation of `Integrable.tendsto_ae_condExp`. This is the
  martingale half of N-L1-RN.
* `condDensity_log_rate_tendsto_zero` — **the full N-L1-RN building block**: for an integrable,
  `ℱ_∞`-measurable, a.e.-strictly-positive density `g`, the log conditional-density rate vanishes,
  `(1/n) · log ((ν[g | ℱ n]) x) → 0` for a.e. `x`. This is exactly the term Mañé discards; it is
  the composition of the martingale convergence above with the already-landed real-analytic tail
  `rate_log_div_tendsto_zero_of_tendsto_pos`.

Both are sorry-free and axiom-clean (`propext, Classical.choice, Quot.sound`).

## What remains BLOCKED (and is *not* this node)

Wiring this into Prop. 7.7 still needs: the countable refining partition `Pₙ` whose generated
filtration is `ℱ` (with `diam Pₙ ≤ ρ`), the identification `r_n = ν[dμ/dν | ℱ n]` atom-by-atom, the
leaf measure `ν` as a geometric object (the unstable foliation / Pesin manifold theorem), and the
Shannon–McMillan–Breiman convergence of the `ν`-term `(1/n) log ν(Pₙ)`. Those are the genuine
Mathlib-scale gaps recorded as the BLOCKED leaves in `ManeLowerBound`. N-L1-RN — the martingale
density step in isolation — is *not* among them, and is closed here.

## References

* Maryam Contractor, *The Pesin Entropy Formula*, UChicago REU 2023, §7 (Prop. 7.7).
* R. Mañé, *A proof of Pesin's formula*, Ergodic Theory Dynam. Systems **1** (1981) 95–102.
-/

open MeasureTheory Filter Topology

namespace Frontier.Issue4Pesin

section Martingale

variable {Ω : Type*} {m0 : MeasurableSpace Ω} {ν : Measure Ω} [IsFiniteMeasure ν]
    {ℱ : Filtration ℕ m0} {g : Ω → ℝ}

/-- **The conditional-density martingale converges a.e. (martingale half of N-L1-RN).**

For a finite base measure `ν`, a filtration `ℱ : Filtration ℕ m0`, and an integrable density
`g` measurable with respect to the limit σ-algebra `⨆ n, ℱ n`, the sequence of conditional
expectations `(ν[g | ℱ n]) x` converges `ν`-a.e. to `g x`. This is exactly the a.e. convergence of
the Mañé conditional-density ratio `r_n = μ(Pₙ)/ν(Pₙ) = (ν[dμ/dν | ℱ n])` once `Pₙ` is replaced by
the abstract filtration `ℱ` it generates and `dμ/dν` by `g`.

It is a direct specialisation of Mathlib's L¹-martingale-convergence theorem
`MeasureTheory.Integrable.tendsto_ae_condExp`; it needs **no foliation data**. -/
theorem condExp_tendsto_ae (hg : Integrable g ν) (hgmeas : StronglyMeasurable[⨆ n, ℱ n] g) :
    ∀ᵐ x ∂ν, Tendsto (fun n => (ν[g | ℱ n]) x) atTop (𝓝 (g x)) :=
  hg.tendsto_ae_condExp hgmeas

/-- **Node N-L1-RN, the full Layer-1 building block: the log conditional-density rate vanishes a.e.**

For a finite base measure `ν`, a filtration `ℱ`, and an integrable, `⨆ n, ℱ n`-measurable density
`g` that is `ν`-a.e. **strictly positive**, the normalised logarithm of the conditional-density
martingale tends to `0` a.e.:
`(1/n) · log ((ν[g | ℱ n]) x) → 0`  for `ν`-a.e. `x`.

This is precisely the term Mañé discards in Prop. 7.7, step 3:
`(1/n) log (μ(Pₙ(x)) / ν(Pₙ(x))) → 0` a.e., with `μ(Pₙ)/ν(Pₙ) = (ν[dμ/dν | ℱ n])` and `g = dμ/dν`
(strictly positive `ν`-a.e. since `μ ≪ ν` with density `g`). The proof composes:
* the a.e. martingale convergence `condExp_tendsto_ae` (`(ν[g|ℱ n]) x → g x`, a finite limit), with
* the already-landed real-analytic tail `rate_log_div_tendsto_zero_of_tendsto_pos`
  (`rₙ → k > 0 ⟹ (1/n) log rₙ → 0`),
fed pointwise on the a.e. set where both the convergence holds and `g x > 0`.

Fully sorry-free and foliation-free: the only dynamical/geometric data is hidden inside `ℱ` (the
partition-generated filtration), `ν` (the leaf measure), and `g` (the Radon–Nikodym density), each
of which is an *input* a future Mañé proof supplies — none is constructed here, and none is needed
to state or prove this node. -/
theorem condDensity_log_rate_tendsto_zero (hg : Integrable g ν)
    (hgmeas : StronglyMeasurable[⨆ n, ℱ n] g) (hgpos : ∀ᵐ x ∂ν, 0 < g x) :
    ∀ᵐ x ∂ν, Tendsto (fun n : ℕ => (1 / (n : ℝ)) * Real.log ((ν[g | ℱ n]) x))
      atTop (𝓝 0) := by
  filter_upwards [condExp_tendsto_ae hg hgmeas, hgpos] with x hx hxpos
  exact rate_log_div_tendsto_zero_of_tendsto_pos hxpos hx

end Martingale

end Frontier.Issue4Pesin
