import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.Analysis.SpecialFunctions.Log.PosLog
import Mathlib.Dynamics.Ergodic.Ergodic
import Mathlib.MeasureTheory.Function.L1Space.Integrable

/-!
# Linear cocycles over a measure-preserving system

This file sets up the basic object of the Oseledets multiplicative ergodic theorem:
the **iterated linear cocycle** generated by a matrix-valued map `A : X → Matrix (Fin d)
(Fin d) ℝ` over a self-map `T : X → X`.

We use the convention that the newest factor is on the **left**:
`cocycle A T 0 x = 1` and `cocycle A T (n+1) x = cocycle A T n (T x) * A x`, so that
`cocycle A T n x = A (T^[n-1] x) * ⋯ * A (T x) * A x`. With this convention the
cocycle identity reads `cocycle A T (m + n) x = cocycle A T m (T^[n] x) * cocycle A T n x`.

The matrix norm is the (scoped) L2 operator norm `Matrix.Norms.L2Operator`, which is
submultiplicative; vectors live in `EuclideanSpace ℝ (Fin d)` and the action is via
`Matrix.toEuclideanCLM`.

This module is part of the skeleton: definitions are concrete, but the structural
lemmas (cocycle identity, measurability) are stated with `sorry` and discharged in the
cocycle-infrastructure phase.
-/

open MeasureTheory
open scoped Matrix.Norms.L2Operator

namespace Oseledets

/-- The (entrywise) **Pi measurable structure on matrices**, induced from the entry
type `α`. A matrix is a function `m → n → α`, and this is the natural σ-algebra for
matrix-valued maps (for finitely many entries over a Borel `α`, it agrees with the
Borel σ-algebra). Mathlib does not yet register this instance because `Matrix` is a
`def`, not reducibly the Pi type, so the ambient Pi instance does not transfer. -/
instance instMeasurableSpaceMatrix {m n α : Type*} [MeasurableSpace α] :
    MeasurableSpace (Matrix m n α) :=
  inferInstanceAs (MeasurableSpace (m → n → α))

variable {X : Type*} {d : ℕ}

/-- The iterated linear cocycle generated by `A` over `T`, newest factor on the left.

`cocycle A T 0 x = 1`, `cocycle A T (n + 1) x = cocycle A T n (T x) * A x`. -/
noncomputable def cocycle (A : X → Matrix (Fin d) (Fin d) ℝ) (T : X → X) :
    ℕ → X → Matrix (Fin d) (Fin d) ℝ
  | 0,     _ => 1
  | (n + 1), x => cocycle A T n (T x) * A x

@[simp] theorem cocycle_zero (A : X → Matrix (Fin d) (Fin d) ℝ) (T : X → X) (x : X) :
    cocycle A T 0 x = 1 := rfl

theorem cocycle_succ (A : X → Matrix (Fin d) (Fin d) ℝ) (T : X → X) (n : ℕ) (x : X) :
    cocycle A T (n + 1) x = cocycle A T n (T x) * A x := rfl

@[simp] theorem cocycle_one (A : X → Matrix (Fin d) (Fin d) ℝ) (T : X → X) (x : X) :
    cocycle A T 1 x = A x := by simp [cocycle_succ]

/-- The **cocycle identity** `A⁽ᵐ⁺ⁿ⁾(x) = A⁽ᵐ⁾(Tⁿ x) · A⁽ⁿ⁾(x)`. -/
theorem cocycle_add (A : X → Matrix (Fin d) (Fin d) ℝ) (T : X → X) (m n : ℕ) (x : X) :
    cocycle A T (m + n) x = cocycle A T m (T^[n] x) * cocycle A T n x := by
  sorry

/-- The one-sided integrability hypothesis: `log⁺‖A‖ ∈ L¹(μ)`. -/
def IntegrableLogNorm [MeasurableSpace X] (A : X → Matrix (Fin d) (Fin d) ℝ)
    (μ : Measure X) : Prop :=
  Integrable (fun x => Real.posLog ‖A x‖) μ

/-- Measurability of each iterate of the cocycle, given a measurable generator. -/
theorem measurable_cocycle [MeasurableSpace X] {A : X → Matrix (Fin d) (Fin d) ℝ}
    (hA : Measurable A) {T : X → X} (hT : Measurable T) (n : ℕ) :
    Measurable (fun x => cocycle A T n x) := by
  sorry

end Oseledets
