/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Multifractal.BernoulliTwoSidedEntropy
import Oseledets.Multifractal.BernoulliTwoSidedErgodic
import Oseledets.Krieger.ZIterate

/-!
# The two-sided coordinate partition is two-sided generating (literal, not mod-0)

The Krieger finite-generator interface (`Oseledets/Krieger/ZIterate.lean`) consumes a
**two-sided generating** partition: `IsGeneratingTwoSided e P` asserts that the smallest
`ziter e`-pullback-stable σ-algebra containing `σ(P)` saturates the whole product σ-algebra,
`⨆ n : ℤ, comap (ziter e n) σ(P) = mα`.

This file discharges that hypothesis *literally* (not merely modulo `0`) for the canonical
setup: the invertible left shift `biShiftEquiv` on the two-sided full shift `BiShift α₀ := ℤ → α₀`
with the
time-`0` coordinate partition `coordPartitionZFin` and any (Bernoulli) measure `bernZ ν`. The
statement is true *on the nose* — no measure-theoretic approximation is needed — because the
two-sided shift exactly translates coordinate σ-algebras and the product σ-algebra over `ℤ` is, by
definition, the supremum of all coordinate comaps.

## The argument (porting the one-sided `coordPartition_isGenerating` to `ℤ`)

* **`σ(coordPartitionZ)` is the time-`0` coordinate σ-algebra.** The cells `{x | x 0 = i}` are
  exactly the singleton preimages of the `0`-th projection; over a finite alphabet a measurable
  subset of
  `α₀` is a finite union of singletons, so `generatedSigmaAlgebra (coordPartitionZ) = coordSigmaZ 0`
  (`generatedSigmaAlgebra_coordPartitionZ_eq`). The `Fin`-reindexed partition `coordPartitionZFin`
  generates the *same* σ-algebra (reindexing leaves the range of cells unchanged,
  `generatedSigmaAlgebra_coordPartitionZFin_eq`).
* **`ziter biShiftEquiv n` translates coordinates.** `ziter biShiftEquiv n x i = x (i + n)`
  (`ziter_biShiftEquiv_apply`), so `eval 0 ∘ ziter biShiftEquiv n = eval n` and hence
  `comap (ziter biShiftEquiv n) (coordSigmaZ 0) = coordSigmaZ n` (`comap_ziter_coordSigmaZ`).
* **The `ℤ`-supremum is the full σ-algebra.** Every integer coordinate `n` is hit, so
  `⨆ n : ℤ, coordSigmaZ n = MeasurableSpace.pi = mα` (`pi_eq_iSup_coordSigmaZ`).

## Main result

* `Oseledets.Multifractal.coordPartitionZFin_isGeneratingTwoSided`:
  `IsGeneratingTwoSided biShiftEquiv (coordPartitionZFin (bernZ ν))`.
-/

open MeasureTheory Function MeasurableSpace
open Oseledets.Entropy Oseledets.Krieger

namespace Oseledets.Multifractal

variable {α₀ : Type*} [Fintype α₀] [MeasurableSpace α₀] [MeasurableSingletonClass α₀]

/-! ### `σ(coordPartitionZ)` is the time-`0` coordinate σ-algebra -/

/-- The σ-algebra generated by the two-sided coordinate partition is the `0`-th coordinate σ-algebra
`coordSigmaZ 0 = comap (eval 0) m`: the cells `{x | x 0 = i}` are exactly the singleton preimages of
the `0`-th projection, and over a finite alphabet a measurable subset of `α₀` is a finite union of
singletons, so the two generated σ-algebras coincide. (Two-sided port of
`generatedSigmaAlgebra_coordPartition_eq`.) -/
theorem generatedSigmaAlgebra_coordPartitionZ_eq (μ : Measure (BiShift α₀)) :
    generatedSigmaAlgebra μ (coordPartitionZ μ) = coordSigmaZ (α₀ := α₀) 0 := by
  unfold coordSigmaZ
  refine le_antisymm ?_ ?_
  · -- `σ(cells) ≤ comap (eval 0) m`: each cell is a singleton preimage, hence comap-measurable.
    refine generateFrom_le ?_
    rintro _ ⟨i, rfl⟩
    exact ⟨{i}, measurableSet_singleton i, rfl⟩
  · -- `comap (eval 0) m ≤ σ(cells)`: a measurable `s ⊆ α₀` is `⋃ i ∈ s, {i}`, so its preimage is a
    -- finite union of cells.
    rw [comap_eq_generateFrom]
    refine generateFrom_le ?_
    rintro _ ⟨s, _, rfl⟩
    have hpre : (fun x : BiShift α₀ => x 0) ⁻¹' s
        = ⋃ i ∈ s, (coordPartitionZ μ).cells i := by
      ext x
      simp only [coordPartitionZ, Set.mem_preimage, Set.mem_iUnion, Set.mem_setOf_eq,
        exists_prop]
      constructor
      · intro hx; exact ⟨x 0, hx, rfl⟩
      · rintro ⟨i, hi, rfl⟩; exact hi
    rw [hpre]
    refine Set.Finite.measurableSet_biUnion s.toFinite (fun i _ => ?_)
    exact measurableSet_generateFrom ⟨i, rfl⟩

/-- The σ-algebra generated by the `Fin`-reindexed two-sided coordinate partition equals that of the
original: a bijective reindexing leaves the *range* of cells unchanged. (Two-sided port of
`generatedSigmaAlgebra_coordPartitionFin_eq`.) -/
theorem generatedSigmaAlgebra_coordPartitionZFin_eq (μ : Measure (BiShift α₀)) :
    generatedSigmaAlgebra μ (coordPartitionZFin μ)
      = generatedSigmaAlgebra μ (coordPartitionZ μ) := by
  unfold generatedSigmaAlgebra
  congr 1
  rw [coordPartitionZFin]
  exact (Fintype.equivFin α₀).symm.surjective.range_comp (coordPartitionZ μ).cells

/-! ### `ziter biShiftEquiv n` translates coordinates -/

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- The `m`-th forward iterate of the *inverse* shift retreats every (integer) index by `m`:
`(biShiftEquiv.symm)^[m] x i = x (i - m)`. -/
theorem biShiftEquiv_symm_iterate_apply (m : ℕ) (x : BiShift α₀) (i : ℤ) :
    ((biShiftEquiv (α₀ := α₀)).symm : BiShift α₀ → BiShift α₀)^[m] x i = x (i - m) := by
  induction m generalizing i with
  | zero => simp
  | succ m ih =>
    rw [Function.iterate_succ_apply', biShiftEquiv_symm_apply, ih]
    congr 1
    omega

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **The two-sided iterate translates coordinates.** The two-sided iterate `ziter biShiftEquiv n`
advances every (integer) index by `n`: `ziter biShiftEquiv n x i = x (i + n)`. For `n ≥ 0` this is
the forward-shift iterate formula `biShiftMap^[k] x i = x (i + k)`; for `n < 0` it is the
inverse-shift iterate formula `biShiftEquiv_symm_iterate_apply`. -/
theorem ziter_biShiftEquiv_apply (n : ℤ) (x : BiShift α₀) (i : ℤ) :
    ziter (biShiftEquiv (α₀ := α₀)) n x i = x (i + n) := by
  cases n with
  | ofNat k =>
    rw [ziter_ofNat, coe_biShiftEquiv, biShiftMap_iterate_apply]
    congr 1
  | negSucc k =>
    rw [ziter_negSucc, biShiftEquiv_symm_iterate_apply]
    congr 1

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Per-`n` pullback identity.** Pulling back the time-`0` coordinate σ-algebra along the
two-sided iterate `ziter biShiftEquiv n` gives the `n`-th coordinate σ-algebra:
`comap (ziter biShiftEquiv n) (coordSigmaZ 0) = coordSigmaZ n`. Indeed
`eval 0 ∘ ziter biShiftEquiv n = eval n` since `ziter biShiftEquiv n x 0 = x n`. -/
theorem comap_ziter_coordSigmaZ (n : ℤ) :
    MeasurableSpace.comap (ziter (biShiftEquiv (α₀ := α₀)) n) (coordSigmaZ (α₀ := α₀) 0)
      = coordSigmaZ (α₀ := α₀) n := by
  rw [coordSigmaZ, MeasurableSpace.comap_comp]
  congr 1
  funext x
  change ziter (biShiftEquiv (α₀ := α₀)) n x 0 = x n
  rw [ziter_biShiftEquiv_apply, zero_add]

/-! ### The two-sided generating property -/

/-- **The two-sided coordinate partition is two-sided generating.** For the invertible left shift
`biShiftEquiv` on the two-sided full shift `BiShift α₀` with the two-sided i.i.d. (Bernoulli)
measure `bernZ ν`, the `Fin`-reindexed time-`0` coordinate partition `coordPartitionZFin` is
two-sided
generating in the *literal* (not merely mod-`0`) sense of Krieger's interface:
`⨆ n : ℤ, comap (ziter biShiftEquiv n) σ(coordPartitionZFin) = mα`.

The reindexed partition generates the same σ-algebra as `coordPartitionZ`, namely the time-`0`
coordinate σ-algebra `coordSigmaZ 0`; the two-sided iterate at `n` pulls this back to the `n`-th
coordinate σ-algebra `coordSigmaZ n`; and the product σ-algebra over `ℤ` is, by definition, the
supremum of all the coordinate σ-algebras, so the `ℤ`-saturation recovers `mα`. -/
theorem coordPartitionZFin_isGeneratingTwoSided (ν : Measure α₀) [IsProbabilityMeasure ν] :
    IsGeneratingTwoSided (biShiftEquiv (α₀ := α₀)) (coordPartitionZFin (bernZ ν)) := by
  unfold IsGeneratingTwoSided
  simp_rw [generatedSigmaAlgebra_coordPartitionZFin_eq, generatedSigmaAlgebra_coordPartitionZ_eq,
    comap_ziter_coordSigmaZ]
  exact (pi_eq_iSup_coordSigmaZ).symm

end Oseledets.Multifractal
