/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Lyapunov.Extensions.ConstantCocycle
import Oseledets.Lyapunov.Extensions.ConstantCocycleSpectralRadius
import Oseledets.Lyapunov.ExteriorNorm.Plucker
import Oseledets.Mathlib.SchurTriangulation
import Mathlib.LinearAlgebra.Matrix.Charpoly.Eigs
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# The full Lyapunov spectrum of a general constant cocycle (Yamamoto's theorem)

For a **constant** (non-symmetric) generator `A ≡ M` the iterated cocycle is the matrix power
`Mⁿ` (`Oseledets.cocycle_const`), so the `i`-th Lyapunov exponent of the cocycle is the
deterministic limit `lim_n (1/n) log σᵢ(Mⁿ)` of the normalized log singular values of the powers.

**Yamamoto's theorem** (Yamamoto, 1967; sharpened by Huang–Tam and others) identifies this limit:
for every matrix `M` and every sorted index `i`,
```
  lim_n (σᵢ(Mⁿ))^{1/n} = |λᵢ(M)|,
```
where `|λᵢ(M)|` is the `i`-th largest *eigenvalue modulus* of `M`, counted with (algebraic)
multiplicity. Equivalently, in logarithmic form,
```
  lim_n (1/n) log σᵢ(Mⁿ) = log |λᵢ(M)|.
```
Hence the `i`-th Lyapunov exponent of the constant cocycle generated by `M` is `log |λᵢ(M)|`. This
is the natural common generalization of two facts already in the library:
* the **symmetric** case `Oseledets.exponents_const`, where `|λᵢ(M)|` is the `i`-th sorted
  eigenvalue of `|M|` (and the singular values of `Mⁿ` are literally `|λ|ⁿ`); and
* the **top** exponent `= log (spectral radius)`, which is Yamamoto at `i = 0` (`s₁ = ‖·‖`).

## Status of this module

The arithmetic content **above** Yamamoto's limit — that the cocycle's `exponents … i` equals
`log |λᵢ(M)|` *given* the limit — is proved here **sorry-free** by uniqueness of limits, since
`exponents … i` is *defined* (in `Oseledets.Lyapunov.Extensions.Spectrum`) as the deterministic
limit of exactly the sequence `(1/n) log σᵢ(cocycle …) = (1/n) log σᵢ(Mⁿ)`.

Yamamoto's limit itself (`yamamoto_singularValues_tendsto`) is **now proved sorry-free** (it was the
last `BLOCKED` leaf of issue #8). This module pursues the **exterior-power / Gelfand route**
(Strategy C of the feasibility report), which *sidesteps* the polar decomposition, the
multiplicative Jordan–Chevalley decomposition, and Weyl perturbation that the trace-moment route
(Dowla–Mukherjee/Nayak) needs, reducing the entire leaf to a single residual matrix-analysis fact
(`compoundMatrix_charpoly_roots_eq`), which is in turn discharged via ℂ-Schur triangulation
(`Oseledets.Mathlib.SchurTriangulation`):

> the spectral radius of the `(i+1)`-st compound (exterior power) `C_{i+1}(M)` equals the product
> of the top `i+1` eigenvalue moduli of `M`, `∏_{k≤i} |λₖ(M)|`.

The reduction works because the repository already provides the two non-trivial ingredients:

* **`σ-product = compound norm`**
  (`Oseledets.ExteriorNorm.prod_singularValues_eq_l2_opNorm_compound`):
  `∏_{k<j} σₖ(Mⁿ) = ‖C_j(Mⁿ)‖`, and `C_j(Mⁿ) = (C_j M)ⁿ` (`compoundMatrix_pow` below, an immediate
  consequence of Cauchy–Binet `compoundMatrix_mul`); and
* **Gelfand for a real matrix** (`Oseledets.tendsto_pow_norm_one_div_spectralRadius`):
  `‖Bⁿ‖^{1/n} → (spectralRadius ℂ B_ℂ).toReal`, applied to `B = C_j(M)`.

Chaining these gives `(σ₀⋯σ_{j-1}(Mⁿ))^{1/n} → ρ(C_j(M))`; with the spectral fact
`ρ(C_{i+1}(M)) = ∏_{k≤i}|λₖ|` this is the product form of Yamamoto, and the single-index statement
follows by telescoping `j = i+1` against `j = i` in `(1/n) log`. The telescoping/`log`-of-zero
bookkeeping (`yamamoto_prod_to_index`) and the eventual-vanishing bridge (`hvanish`, from
nilpotency of the compound when `|λᵢ| = 0`) are **sorry-free**.

The spectral fact `spectralRadius_compound_eq_prod_eigenvalueModuli` is **proved sorry-free** from
the clean multiset eigenvalue identity `compoundMatrix_charpoly_roots_eq` — the multiset of
characteristic-polynomial roots of the complexified compound `(C_j M)_ℂ` equals the multiset of
`j`-fold products of the eigenvalues of `M`, `(powersetCard j (roots M_ℂ)).map (∏)`. From that
multiset identity, *all* of the remaining content — that the spectral radius (= max spectral
modulus, finite-spectrum `toReal` plumbing) equals the product of the top-`j` eigenvalue moduli — is
discharged sorry-free here via a self-contained combinatorial development: the top-`j` product
maximizes products over `j`-sub-multisets of a nonnegative multiset (`prod_le_take_sort`, built from
descending-sorted sublist domination `sublist_getElem_le_getElem_of_sorted_ge`), together with the
sub-multiset lifting
`exists_le_of_le_map` and the two `spectralRadius`-extraction bounds.

**`compoundMatrix_charpoly_roots_eq` is now itself proved sorry-free** (the spectrum of `⋀^j A` =
the `j`-fold products of the spectrum of `A`). The proof combines: (i) **Schur triangulation over
`ℂ`** (`Matrix.schur_triangulation`, grafted in `Oseledets.Mathlib.SchurTriangulation` from the
Mathlib-style proof of Gordon Hsu) producing a unitary `U` and upper-triangular `T` with
`A = U T U⁻¹` and `T.diag` multiset `= A.charpoly.roots`; (ii) **Cauchy–Binet for the
minor-compound over any commutative ring**
(`compoundOf_mul`, proved here via the abstract exterior power `exteriorPower.map` and
`LinearMap.toMatrix_comp`) making `compoundOf j A` similar to the triangular `compoundOf j T`; and
(iii) the **triangular-compound structure** (`compoundOf_blockTriangular`, `compoundOf_diag`,
`roots_charpoly_of_blockTriangular_inj`, `diag_prod_multiset_eq`) reading off the compound's
charpoly roots as the `j`-fold diagonal products `= (powersetCard j (roots M_ℂ)).map (∏)`. The whole
module is therefore sorry-free.

## Main definitions

* `Oseledets.eigenvalueModuli M` — the moduli `|λ(M)|` of the (complex) eigenvalues of a real
  matrix `M`, counted with algebraic multiplicity and **sorted in non-increasing order** as a
  `List ℝ` of length `d`. The `i`-th largest modulus is `(eigenvalueModuli M).getD i 0`.

## Main results

* `Oseledets.eigenvalueModuli_length` — the list has length `d` (so `getD i 0` is the genuine
  `i`-th entry for `i < d`).
* `Oseledets.yamamoto_singularValues_tendsto` — **Yamamoto's theorem** (the only `BLOCKED` leaf):
  `(1/n) log σᵢ(Mⁿ) → log |λᵢ(M)|`.
* `Oseledets.exponents_const_general` — **the full spectrum of a general constant cocycle**
  (sorry-free *given* Yamamoto): `exponents (fun _ => M) … i = log |λᵢ(M)|`.

## References

* T. Yamamoto, *On the extreme values of the roots of matrices*, J. Math. Soc. Japan **19** (1967).
* H. Huang, T.-Y. Tam, *An extension of Yamamoto's theorem on the eigenvalues and singular values
  of a matrix*, J. Math. Soc. Japan **58** (2006).
* P. N. Dowla, S. Mukherjee, et al., *A stronger form of Yamamoto's theorem on singular values*,
  arXiv:2303.01252 (2023). (Theorem 3.8 / Corollary 3.9.)
-/

open MeasureTheory Filter Topology
open scoped Matrix

namespace Oseledets

variable {X : Type*} [MeasurableSpace X] {d : ℕ}

/-! ## The sorted eigenvalue moduli of a real matrix -/

/-- **The sorted eigenvalue moduli of a real matrix.** Mapping `M` into `Matrix _ _ ℂ` and taking
the roots of its characteristic polynomial gives the complex eigenvalues of `M` counted with
algebraic multiplicity; their moduli, sorted in non-increasing order, form the list
`eigenvalueModuli M : List ℝ`. The `i`-th largest eigenvalue modulus is
`(eigenvalueModuli M).getD i 0`. -/
noncomputable def eigenvalueModuli (M : Matrix (Fin d) (Fin d) ℝ) : List ℝ :=
  (((M.map (algebraMap ℝ ℂ)).charpoly.roots).map (fun z => ‖z‖)).sort (· ≥ ·)

/-- The sorted eigenvalue-moduli list has length `d`: the characteristic polynomial of the `d × d`
matrix `M` (over the algebraically closed field `ℂ`) is monic of degree `d` and therefore splits
with exactly `d` roots counted with multiplicity. -/
theorem eigenvalueModuli_length (M : Matrix (Fin d) (Fin d) ℝ) :
    (eigenvalueModuli M).length = d := by
  rw [eigenvalueModuli, Multiset.length_sort, Multiset.card_map]
  -- Over the algebraically closed field `ℂ` the charpoly splits, so its root multiset has
  -- cardinality equal to its degree `d`.
  have hsplits : ((M.map (algebraMap ℝ ℂ)).charpoly).Splits := IsAlgClosed.splits _
  rw [Polynomial.splits_iff_card_roots.mp hsplits, Matrix.charpoly_natDegree_eq_dim,
    Fintype.card_fin]

/-! ## Strategy C: exterior-power / Gelfand reduction

The whole leaf reduces, through reusable repository infrastructure, to the spectral fact about the
compound (exterior power) matrix `compoundMatrix_charpoly_roots_eq`, which is itself proved
sorry-free below (Schur triangulation + Cauchy–Binet + triangular-compound structure). We first
record the
multiplicative and combinatorial ingredients, then the sorry-free assembly. -/

open scoped Matrix.Norms.L2Operator ENNReal

/-! ### Combinatorial core: the top-`j` product maximizes products over `j`-sub-multisets

These lemmas are pure order/combinatorics on multisets of nonnegative reals; they have no matrix
content. The goal is `prod_le_take_sort` and `topProd_mem_powersetCard_prod`, which together pin the
maximum of `T.prod` over `T ∈ powersetCard j m` to the product of the top `j` elements of the
descending sort of `m`. -/

/-- **Lifting a sub-multiset through a map.** If `T ≤ s.map f` then there is `u ≤ s` with
`u.map f = T`. (Pick a preimage of each element of `T` inside `s`.) -/
private theorem exists_le_of_le_map {α β : Type*} {f : α → β} {T : Multiset β} {s : Multiset α}
    (h : T ≤ s.map f) : ∃ u ≤ s, u.map f = T := by
  classical
  induction T using Multiset.induction_on generalizing s with
  | empty => exact ⟨0, Multiset.zero_le s, by simp⟩
  | cons b T ih =>
      -- `b ∈ s.map f`, so `b = f a` for some `a ∈ s`.
      have hb : b ∈ s.map f := Multiset.mem_of_le h (Multiset.mem_cons_self b T)
      rw [Multiset.mem_map] at hb
      obtain ⟨a, ha, rfl⟩ := hb
      -- `T ≤ (s.erase a).map f`.
      have hTle : T ≤ (s.erase a).map f := by
        have hcons : f a ::ₘ T ≤ s.map f := h
        rw [← Multiset.cons_erase ha, Multiset.map_cons] at hcons
        exact (Multiset.cons_le_cons_iff (f a)).mp hcons
      obtain ⟨u, hule, humap⟩ := ih hTle
      refine ⟨a ::ₘ u, ?_, ?_⟩
      · rw [← Multiset.cons_erase ha]; exact Multiset.cons_le_cons a hule
      · rw [Multiset.map_cons, humap]

/-- The product of the first `j` entries of a list equals `∏_{k<j} L.getD k 0`, for `j ≤ length`. -/
private theorem prod_take_eq_prod_range_getD (L : List ℝ) (j : ℕ) (hj : j ≤ L.length) :
    (L.take j).prod = ∏ k ∈ Finset.range j, L.getD k 0 := by
  induction j with
  | zero => simp
  | succ m ih =>
      have hm : m ≤ L.length := Nat.le_of_succ_le hj
      have hmlt : m < L.length := hj
      rw [List.prod_take_succ L m hmlt, ih hm, Finset.prod_range_succ]
      congr 1
      rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem hmlt, Option.getD_some]

/-- **Descending-sorted sublist domination.** If `c` is a sublist of a list `l` that is sorted in
non-increasing order (`l.Pairwise (· ≥ ·)`), then position-by-position the entries of `c` are
dominated by those of `l`: `c[i] ≤ l[i]` for every `i < c.length`. (Inserting elements of a
descending list can only make later entries no larger, so the `i`-th entry of the sublist sits at or
after the `i`-th entry of the whole list.) -/
private theorem sublist_getElem_le_getElem_of_sorted_ge {α : Type*} [Preorder α]
    {c l : List α} (hcl : c.Sublist l) (hl : l.Pairwise (· ≥ ·)) :
    ∀ (i : ℕ) (hic : i < c.length),
      c[i] ≤ l[i]'(lt_of_lt_of_le hic hcl.length_le) := by
  induction hcl with
  | slnil => intro i hic; simp at hic
  | @cons L₁ L₂ a h ih =>
      -- relation is `L₁ <+ (a :: L₂)`; here `l = a :: L₂`, `c = L₁`.
      intro i hic
      have hLsorted : L₂.Pairwise (· ≥ ·) := (List.pairwise_cons.mp hl).2
      have hiL : i < L₂.length := lt_of_lt_of_le hic h.length_le
      -- IH on `L₂` (sorted): `L₁[i] ≤ L₂[i]`.
      have hcL : L₁[i]'hic ≤ L₂[i]'hiL := ih hLsorted i hic
      -- `L₂[i] ≤ (a :: L₂)[i]` by descending sortedness of `a :: L₂`.
      have hipp : i + 1 < (a :: L₂).length := by simpa using Nat.succ_lt_succ hiL
      have hstep : L₂[i]'hiL ≤ (a :: L₂)[i]'(by simpa using Nat.lt_succ_of_lt hiL) := by
        have := (List.pairwise_iff_getElem.mp hl) i (i + 1)
          (by simpa using Nat.lt_succ_of_lt hiL) hipp (Nat.lt_succ_self i)
        have hshift : (a :: L₂)[i + 1]'hipp = L₂[i]'hiL := by simp
        rw [hshift] at this
        exact this
      exact le_trans hcL hstep
  | @cons_cons L₁ L₂ a h ih =>
      intro i hic
      cases i with
      | zero => simp
      | succ k =>
          have hkc : k < L₁.length := by simpa using Nat.lt_of_succ_lt_succ (by simpa using hic)
          have hLsorted : L₂.Pairwise (· ≥ ·) := (List.pairwise_cons.mp hl).2
          have := ih hLsorted k hkc
          simpa using this

/-- For a sub-multiset `T ≤ m`, the descending sorts satisfy `T.sort <+ m.sort`. (Both are
non-increasingly sorted and `T.sort` is a sub-permutation of `m.sort`.) -/
private theorem sort_sublist_sort_of_le {m T : Multiset ℝ} (hTm : T ≤ m) :
    (T.sort (· ≥ ·)).Sublist (m.sort (· ≥ ·)) := by
  refine List.sublist_of_subperm_of_pairwise (r := (· ≥ ·)) ?_ ?_ ?_
  · -- `T.sort <+~ m.sort` from `T ≤ m` via the multiset coercion.
    have : ((T.sort (· ≥ ·) : List ℝ) : Multiset ℝ) ≤ ((m.sort (· ≥ ·) : List ℝ) : Multiset ℝ) := by
      rw [Multiset.sort_eq, Multiset.sort_eq]; exact hTm
    rwa [Multiset.coe_le] at this
  · exact Multiset.pairwise_sort _ _
  · exact Multiset.pairwise_sort _ _

/-- **Products of a `j`-sub-multiset are dominated by the top-`j` product.** For a multiset `m` of
nonnegative reals and a sub-multiset `T ≤ m` with `card T = j`, the product `T.prod` is at most the
product of the top `j` entries of the descending sort of `m`. -/
private theorem prod_le_take_sort {m T : Multiset ℝ} {j : ℕ} (hpos : ∀ x ∈ m, 0 ≤ x)
    (hTm : T ≤ m) (hcard : Multiset.card T = j) :
    T.prod ≤ (((m.sort (· ≥ ·)).take j).prod) := by
  classical
  -- Work with the descending sorts.
  set Lm := m.sort (· ≥ ·) with hLm
  set LT := T.sort (· ≥ ·) with hLT
  have hsub : LT.Sublist Lm := sort_sublist_sort_of_le hTm
  have hLTlen : LT.length = j := by rw [hLT, Multiset.length_sort, hcard]
  have hLmsorted : Lm.Pairwise (· ≥ ·) := Multiset.pairwise_sort _ _
  have hjLm : j ≤ Lm.length := by rw [← hLTlen]; exact hsub.length_le
  -- `T.prod = LT.prod`.
  have hTprod : LT.prod = T.prod := by
    rw [hLT, ← Multiset.prod_coe, Multiset.sort_eq]
  rw [← hTprod]
  -- nonneg of entries of `LT` (they are entries of `m`).
  have hposLT : ∀ i (hi : i < LT.length), 0 ≤ LT[i] := by
    intro i hi
    have hmem : LT[i] ∈ LT := List.getElem_mem hi
    have hmem' : LT[i] ∈ m := by
      have : LT[i] ∈ (T.sort (· ≥ ·)) := by rw [← hLT]; exact hmem
      rw [Multiset.mem_sort] at this
      exact Multiset.mem_of_le hTm this
    exact hpos _ hmem'
  -- Position-by-position domination from the sublist + sortedness.
  have hdom := sublist_getElem_le_getElem_of_sorted_ge hsub hLmsorted
  -- Express both products over `Fin j` and compare.
  have hLT_take_len : (Lm.take j).length = j := by rw [List.length_take]; omega
  -- A list of length `j` has product equal to the `Fin j`-indexed product of its entries.
  have prod_eq_fin : ∀ (L : List ℝ) (hL : L.length = j),
      L.prod = ∏ i : Fin j, L[(i : ℕ)]'(by rw [hL]; exact i.2) := by
    intro L hL
    subst hL
    rw [← Fin.prod_univ_getElem L]
  rw [prod_eq_fin LT hLTlen, prod_eq_fin (Lm.take j) hLT_take_len]
  apply Finset.prod_le_prod
  · intro i _; exact hposLT i (by rw [hLTlen]; exact i.2)
  · intro i _
    have hiLm : (i : ℕ) < Lm.length := lt_of_lt_of_le i.2 hjLm
    have hdomi := hdom i (by rw [hLTlen]; exact i.2)
    have htake : (Lm.take j)[(i : ℕ)]'(by rw [hLT_take_len]; exact i.2) = Lm[(i : ℕ)]'hiLm := by
      rw [List.getElem_take]
    rw [htake]; exact hdomi

/-- **The compound (exterior power) of a matrix power is the power of the compound.**
`C_k(Mⁿ) = (C_k M)ⁿ`. This is Cauchy–Binet (`ExteriorNorm.compoundMatrix_mul`) iterated, with
`ExteriorNorm.compoundMatrix_one` for the base case; it is the multiplicativity that lets Gelfand's
formula act on `C_k(M)` rather than on each `C_k(Mⁿ)` separately. Sorry-free. -/
theorem compoundMatrix_pow (k : ℕ) (M : Matrix (Fin d) (Fin d) ℝ) (n : ℕ) :
    ExteriorNorm.compoundMatrix k (M ^ n) = (ExteriorNorm.compoundMatrix k M) ^ n := by
  induction n with
  | zero => simpa using ExteriorNorm.compoundMatrix_one k
  | succ m ih => rw [pow_succ, pow_succ, ExteriorNorm.compoundMatrix_mul, ih]

/-! ### Spectral-radius bookkeeping over `ℂ` (finite spectrum = charpoly roots) -/

/-- **Upper bound for the (real) spectral radius.** If every spectral value of `A` has norm at most
`B ≥ 0`, then `(spectralRadius ℂ A).toReal ≤ B`, provided the spectral radius is finite. -/
private theorem spectralRadius_toReal_le {N : ℕ} (A : Matrix (Fin N) (Fin N) ℂ) {B : ℝ}
    (hB : 0 ≤ B) (hfin : spectralRadius ℂ A ≠ ⊤)
    (hbound : ∀ μ ∈ spectrum ℂ A, ‖μ‖ ≤ B) :
    (spectralRadius ℂ A).toReal ≤ B := by
  have hle : spectralRadius ℂ A ≤ ENNReal.ofReal B := by
    refine iSup₂_le fun μ hμ => ?_
    calc (‖μ‖₊ : ENNReal) = ENNReal.ofReal ‖μ‖ := by
            rw [← ENNReal.ofReal_coe_nnreal, coe_nnnorm]
      _ ≤ ENNReal.ofReal B := ENNReal.ofReal_le_ofReal (hbound μ hμ)
  calc (spectralRadius ℂ A).toReal ≤ (ENNReal.ofReal B).toReal :=
          ENNReal.toReal_le_toReal hfin ENNReal.ofReal_ne_top |>.mpr hle
    _ = B := ENNReal.toReal_ofReal hB

/-- **Lower bound for the (real) spectral radius.** Every spectral value's norm is at most the real
spectral radius (finite case). -/
private theorem le_spectralRadius_toReal {N : ℕ} (A : Matrix (Fin N) (Fin N) ℂ) {μ : ℂ}
    (hfin : spectralRadius ℂ A ≠ ⊤) (hμ : μ ∈ spectrum ℂ A) :
    ‖μ‖ ≤ (spectralRadius ℂ A).toReal := by
  have hle : (‖μ‖₊ : ENNReal) ≤ spectralRadius ℂ A :=
    le_iSup₂ (f := fun k _ => (‖k‖₊ : ENNReal)) μ hμ
  have := (ENNReal.toReal_le_toReal (by simp) hfin).mpr hle
  simpa using this

/-! ### The bridge: complexified compound = compound of the complexification

The `(t, s)` entry of `compoundMatrix j M` is the determinant of the `j × j` minor of `M` selecting
the rows enumerated by the `t`-th `j`-subset and the columns enumerated by the `s`-th `j`-subset.
These enumerators (`compoundRowEnum`, `compoundColEnum`) depend only on `d`, `j` and the index — not
on the entry ring — so the same combinatorial data defines a compound `compoundOf` over *any*
commutative ring. Functoriality of the determinant under a ring hom (`RingHom.map_det`,
`Matrix.submatrix_map`) then gives the bridge
`(compoundMatrix j M).map f = compoundOf j (M.map f)`. -/

open scoped Classical in
/-- The row/column enumerator of the `t`-th `j`-subset used in `compoundMatrix` (ring-agnostic). -/
noncomputable def compoundEnum (j : ℕ)
    (t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) (i : Fin j) : Fin d :=
  (Set.powersetCard.ofFinEmbEquiv.symm
    ((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t)) i

open scoped Classical in
/-- The compound matrix of `A` over an arbitrary commutative ring, using the **same** combinatorial
row/column enumerators as the real `ExteriorNorm.compoundMatrix`. Its `(t, s)` entry is the
determinant of the `j × j` minor of `A` selecting rows `compoundEnum j t` and columns
`compoundEnum j s`. -/
noncomputable def compoundOf {S : Type*} [CommRing S] (j : ℕ) (A : Matrix (Fin d) (Fin d) S) :
    Matrix (Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))))
      (Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) S :=
  Matrix.of fun t s => (A.submatrix (compoundEnum j t) (compoundEnum j s)).det

/-- `compoundOf` of a complex matrix coincides entrywise with the real `compoundMatrix` definition
when `S = ℝ`. (Just unfolds both to the same minor determinant.) -/
theorem compoundOf_real_eq (j : ℕ) (M : Matrix (Fin d) (Fin d) ℝ) :
    compoundOf j M = ExteriorNorm.compoundMatrix j M := by
  classical
  ext t s
  rw [compoundOf, ExteriorNorm.compoundMatrix, Matrix.of_apply, Matrix.of_apply]
  rfl

/-- **The bridge.** Mapping the real compound matrix through a ring hom equals the abstract compound
of the mapped matrix: `(compoundMatrix j M).map f = compoundOf j (M.map f)`. The `(t, s)` entry is
`f (det minor) = det (f-mapped minor) = det (minor of mapped matrix)` by `RingHom.map_det` and
`Matrix.submatrix_map`. -/
theorem map_compoundMatrix_eq_compoundOf {S : Type*} [CommRing S]
    (j : ℕ) (M : Matrix (Fin d) (Fin d) ℝ) (f : ℝ →+* S) :
    (ExteriorNorm.compoundMatrix j M).map f = compoundOf j (M.map f) := by
  classical
  ext t s
  rw [Matrix.map_apply, ExteriorNorm.compoundMatrix, Matrix.of_apply, compoundOf, Matrix.of_apply,
    RingHom.map_det, RingHom.mapMatrix_apply, Matrix.submatrix_map]
  rfl

/-- Specialisation of the bridge to the complexification `f = algebraMap ℝ ℂ`. -/
theorem map_compoundMatrix_complex (j : ℕ) (M : Matrix (Fin d) (Fin d) ℝ) :
    (ExteriorNorm.compoundMatrix j M).map (algebraMap ℝ ℂ)
      = compoundOf j (M.map (algebraMap ℝ ℂ)) :=
  map_compoundMatrix_eq_compoundOf j M (algebraMap ℝ ℂ)

/-! ### Cauchy–Binet for `compoundOf` over any commutative ring (via the abstract exterior power)

`compoundOf j A` is, after reindexing, the matrix in the wedge basis
`(Pi.basisFun S (Fin d)).exteriorPower j` of the abstract functorial map
`exteriorPower.map j (Matrix.toLin' A)`. Functoriality
`exteriorPower.map j (g ∘ f) = (map j g) ∘ (map j f)` (`exteriorPower.map_comp`) together with
`Matrix.toLin'_mul` and `LinearMap.toMatrix_comp` then gives the *Cauchy–Binet identity*
`compoundOf j (A * B) = compoundOf j A * compoundOf j B` over **any** commutative ring `S` — the
genuinely missing multiplicativity that the ℝ-only `ExteriorNorm.compoundMatrix_mul` does not
provide over `ℂ`. -/

open scoped Classical in
/-- The **abstract `j`-th compound matrix** of `A`, indexed by `powersetCard (Fin d) j`: the matrix
in the wedge basis `(Pi.basisFun S (Fin d)).exteriorPower j` of `exteriorPower.map j (toLin' A)`. -/
noncomputable def compoundAbstract {S : Type*} [CommRing S] (j : ℕ) (A : Matrix (Fin d) (Fin d) S) :
    Matrix (Set.powersetCard (Fin d) j) (Set.powersetCard (Fin d) j) S :=
  LinearMap.toMatrix ((Pi.basisFun S (Fin d)).exteriorPower j)
    ((Pi.basisFun S (Fin d)).exteriorPower j) (exteriorPower.map j (Matrix.toLin' A))

/-- The `(t, s)` entry of `compoundAbstract j A` is the determinant of the `j × j` minor of `A`
selecting rows enumerated by `ofFinEmbEquiv.symm t` and columns by `ofFinEmbEquiv.symm s`. -/
theorem compoundAbstract_apply {S : Type*} [CommRing S] (j : ℕ) (A : Matrix (Fin d) (Fin d) S)
    (t s : Set.powersetCard (Fin d) j) :
    compoundAbstract j A t s
      = (A.submatrix (fun i => Set.powersetCard.ofFinEmbEquiv.symm t i)
          (fun i => Set.powersetCard.ofFinEmbEquiv.symm s i)).det := by
  classical
  rw [compoundAbstract, LinearMap.toMatrix_apply, exteriorPower.coe_basis,
    exteriorPower.map_apply_ιMulti_family, exteriorPower.basis_repr_apply]
  -- Now both sides are determinants of `j × j` matrices over `S`.
  rw [exteriorPower.ιMulti_family, exteriorPower.ιMultiDual_apply_ιMulti, ← Matrix.det_transpose]
  -- Entrywise: `b.coord p (toLin' A (b q)) = A p q`.
  have hentry : ∀ p q : Fin d,
      (Pi.basisFun S (Fin d)).coord p ((Matrix.toLin' A) ((Pi.basisFun S (Fin d)) q)) = A p q := by
    intro p q
    rw [Module.Basis.coord_apply, Pi.basisFun_repr, Matrix.toLin'_apply, Pi.basisFun_apply,
      Matrix.mulVec_single_one, Matrix.col_apply]
  congr 1
  ext i k
  simp only [Matrix.of_apply, Matrix.transpose_apply, Matrix.submatrix_apply, Function.comp_apply]
  rw [hentry]

/-- **Cauchy–Binet (abstract form).** `compoundAbstract j (A * B) = compoundAbstract j A *
compoundAbstract j B`. Immediate from functoriality of `exteriorPower.map` and
`LinearMap.toMatrix_comp`. -/
theorem compoundAbstract_mul {S : Type*} [CommRing S] (j : ℕ)
    (A B : Matrix (Fin d) (Fin d) S) :
    compoundAbstract j (A * B) = compoundAbstract j A * compoundAbstract j B := by
  classical
  rw [compoundAbstract, compoundAbstract, compoundAbstract, Matrix.toLin'_mul,
    exteriorPower.map_comp, LinearMap.toMatrix_comp _ ((Pi.basisFun S (Fin d)).exteriorPower j)]

/-- `compoundAbstract j 1 = 1`. -/
theorem compoundAbstract_one {S : Type*} [CommRing S] (j : ℕ) :
    compoundAbstract j (1 : Matrix (Fin d) (Fin d) S) = 1 := by
  rw [compoundAbstract, Matrix.toLin'_one, exteriorPower.map_id, LinearMap.toMatrix_id]

/-- `compoundOf j A` is the reindexing of `compoundAbstract j A` along the wedge-index equivalence
`wIndexEquiv`. (Both have entry `det (minor along the subset enumerators)`; the enumerators of
`compoundOf` are precisely `ofFinEmbEquiv.symm` of the `wIndexEquiv`-preimage subset.) -/
theorem compoundOf_eq_reindex {S : Type*} [CommRing S] (j : ℕ) (A : Matrix (Fin d) (Fin d) S) :
    compoundOf j A
      = Matrix.reindex (ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j)
          (ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j)
          (compoundAbstract j A) := by
  classical
  ext t s
  rw [compoundOf, Matrix.of_apply, Matrix.reindex_apply, Matrix.submatrix_apply,
    compoundAbstract_apply]
  rfl

/-- **Cauchy–Binet for `compoundOf`** over any commutative ring: multiplicativity of the
minor-compound. -/
theorem compoundOf_mul {S : Type*} [CommRing S] (j : ℕ) (A B : Matrix (Fin d) (Fin d) S) :
    compoundOf j (A * B) = compoundOf j A * compoundOf j B := by
  rw [compoundOf_eq_reindex, compoundOf_eq_reindex, compoundOf_eq_reindex, compoundAbstract_mul]
  ext t s
  simp only [Matrix.reindex_apply, Matrix.submatrix_apply, Matrix.mul_apply]
  exact Fintype.sum_equiv (ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j) _ _
    (fun _ => by simp [Equiv.symm_apply_apply])

/-- `compoundOf j 1 = 1`. -/
theorem compoundOf_one {S : Type*} [CommRing S] (j : ℕ) :
    compoundOf j (1 : Matrix (Fin d) (Fin d) S) = 1 := by
  rw [compoundOf_eq_reindex, compoundAbstract_one]
  ext t s
  simp only [Matrix.reindex_apply, Matrix.submatrix_apply, Matrix.one_apply,
    EmbeddingLike.apply_eq_iff_eq]

/-! ### Minors of an upper-triangular matrix

For an upper-triangular `U` (`U.BlockTriangular id`, i.e. `U a b = 0` when `b < a`) and a strictly
monotone index selection `r : Fin j → Fin d`, the principal-style minor `U.submatrix r r` is again
upper triangular, so its determinant is the product of its diagonal entries `∏ U (r i) (r i)`. -/

/-- A submatrix of an upper-triangular matrix along a strictly monotone selection `r` is upper
triangular, hence its determinant is the diagonal product `∏ U (r i) (r i)`. -/
theorem det_submatrix_upperTriangular_diag {S : Type*} [CommRing S] {n m : ℕ}
    (U : Matrix (Fin n) (Fin n) S) (hU : U.BlockTriangular id) (r : Fin m → Fin n)
    (hr : StrictMono r) :
    (U.submatrix r r).det = ∏ i, U (r i) (r i) := by
  classical
  have hbt : (U.submatrix r r).BlockTriangular id := by
    intro a b hab
    -- `id b < id a` means `b < a`; want `(U.submatrix r r) a b = U (r a) (r b) = 0`.
    have hba : (b : Fin m) < a := hab
    have : r b < r a := hr hba
    exact hU this
  rw [Matrix.det_of_upperTriangular hbt]
  rfl

/-- **Vanishing of an off-diagonal triangular minor.** For an upper-triangular `U`
(`U.BlockTriangular id`) and strictly monotone selections `r, c : Fin m → Fin n`, the minor
`det (U.submatrix r c)` vanishes whenever the row selection "overtakes" the column selection at some
index, i.e. there is `i` with `c i < r i`.

Proof: by `det_apply`, each permutation term `∏ k, U (r (σ k)) (c k)` is nonzero only if
`r (σ k) ≤ c k` for all `k` (upper-triangularity kills entries with `c k < r (σ k)`). Restricting to
`k ≤ i` (there are `i+1` such), monotonicity of `c` gives `r (σ k) ≤ c k ≤ c i < r i`, hence (since
`r` is strictly monotone) `σ k < i` — an injection from an `(i+1)`-set into an `i`-set, impossible.
So every term vanishes. -/
theorem det_submatrix_upperTriangular_vanish {S : Type*} [CommRing S] {n m : ℕ}
    (U : Matrix (Fin n) (Fin n) S) (hU : U.BlockTriangular id) {r c : Fin m → Fin n}
    (hr : StrictMono r) (hc : Monotone c) {i : Fin m} (hi : c i < r i) :
    (U.submatrix r c).det = 0 := by
  classical
  rw [Matrix.det_apply]
  refine Finset.sum_eq_zero (fun σ _ => ?_)
  -- Show the term vanishes: find `k` with `U (r (σ k)) (c k) = 0`, then the product is 0.
  suffices hprod : ∏ k, (U.submatrix r c) (σ k) k = 0 by
    rw [hprod, smul_zero]
  -- Either some factor is zero (done), or all factors are nonzero (contradiction).
  by_contra hne
  have hall : ∀ k, (U.submatrix r c) (σ k) k ≠ 0 := by
    intro k hk
    exact hne (Finset.prod_eq_zero (Finset.mem_univ k) hk)
  -- Upper-triangularity: each nonzero factor forces `r (σ k) ≤ c k`.
  have hle : ∀ k, r (σ k) ≤ c k := by
    intro k
    by_contra hlt
    push Not at hlt
    -- `c k < r (σ k)`, i.e. `id (c k) < id (r (σ k))`, so `U (r (σ k)) (c k) = 0`.
    exact hall k (hU hlt)
  -- Pigeonhole on `k ≤ i`: `σ` maps `Iic i` (card `i+1`) into `Iio i` (card `i`).
  have hmap : ∀ k ∈ Finset.Iic i, σ k ∈ Finset.Iio i := by
    intro k hk
    rw [Finset.mem_Iio]
    -- `r (σ k) ≤ c k ≤ c i < r i`, so `r (σ k) < r i`, so `σ k < i`.
    have hck : c k ≤ c i := hc (Finset.mem_Iic.mp hk)
    have : r (σ k) < r i := lt_of_le_of_lt (le_trans (hle k) hck) hi
    exact hr.lt_iff_lt.mp this
  -- `σ` is injective, so the image of `Iic i` has card `= card (Iic i) = i+1 > i = card (Iio i)`.
  have hinj : Set.InjOn σ (Finset.Iic i) := fun a _ b _ h => σ.injective h
  have hcard := Finset.card_le_card_of_injOn σ hmap hinj
  rw [Fin.card_Iic, Fin.card_Iio] at hcard
  omega

/-- **Roots of the charpoly of an upper-triangular matrix.** Over an integral domain, the
characteristic-polynomial root multiset of an upper-triangular matrix (`M.BlockTriangular id`) is
exactly the multiset of its diagonal entries. From `Matrix.charpoly_of_upperTriangular`
(`charpoly = ∏ i, (X - C (M i i))`) and `Polynomial.roots_multiset_prod_X_sub_C`. -/
theorem roots_charpoly_of_upperTriangular {S : Type*} [CommRing S] [IsDomain S] {n : ℕ}
    (U : Matrix (Fin n) (Fin n) S) (hU : U.BlockTriangular id) :
    U.charpoly.roots = Finset.univ.val.map (fun i => U i i) := by
  rw [Matrix.charpoly_of_upperTriangular U hU]
  rw [show (∏ i : Fin n, (Polynomial.X - Polynomial.C (U i i)))
      = ((Finset.univ.val.map (fun i => U i i)).map
          (fun a => Polynomial.X - Polynomial.C a)).prod by
    rw [Multiset.map_map, ← Finset.prod_eq_multiset_prod]; rfl]
  rw [Polynomial.roots_multiset_prod_X_sub_C]

/-- The compound index `finrank ℝ (⋀^j (EuclideanSpace ℝ (Fin d)))` is nonzero exactly when
`j ≤ d`, since it equals `Nat.choose d j` (`exteriorPower.finrank_eq`,
`finrank (EuclideanSpace ℝ (Fin d)) = d`). Packaged as a `NeZero` instance under `j ≤ d` so that
Gelfand's formula (which needs a nonempty matrix index) applies to `C_j(M)`. -/
theorem neZero_finrank_exteriorPower_of_le {j : ℕ} (hj : j ≤ d) :
    NeZero (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) := by
  refine ⟨?_⟩
  rw [exteriorPower.finrank_eq, finrank_euclideanSpace, Fintype.card_fin]
  exact (Nat.choose_pos hj).ne'

/-! ### Compound of a triangular matrix is triangular with the `j`-fold diagonal products

For triangular `U` the minor `det (U.submatrix (enum t) (enum s))` vanishes unless the sorted row
selection `enum t` is pointwise dominated by the column selection `enum s` (otherwise a row index
overtakes a column index, killing the determinant by `det_submatrix_upperTriangular_vanish`); on
the diagonal it is the product `∏ i, U (enum t i) (enum t i)` by
`det_submatrix_upperTriangular_diag`. We
package this as block-triangularity of `compoundOf j U` w.r.t. the lexicographic order of the sorted
subset enumerators, whose diagonal is the `j`-fold diagonal products. -/

/-- The subset enumerator `compoundEnum j t = ofFinEmbEquiv.symm (…)` is strictly monotone (it is
the order embedding `Finset.orderEmbOfFin`). -/
theorem compoundEnum_strictMono (j : ℕ)
    (t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) :
    StrictMono (compoundEnum j t) := by
  classical
  intro a b hab
  rw [compoundEnum, compoundEnum, Set.powersetCard.ofFinEmbEquiv_symm_apply]
  exact (Finset.orderEmbOfFin _ _).strictMono hab

/-- **Compound of a triangular matrix is triangular** in the lexicographic order on the sorted
subset enumerators, with diagonal entries the `j`-fold diagonal products. Concretely
`compoundOf j U` is `BlockTriangular` for `b t := toLex (compoundEnum j t)`, and
`compoundOf j U t t = ∏ i, U (enum i) (enum i)`. -/
theorem compoundOf_blockTriangular {S : Type*} [CommRing S] (j : ℕ)
    (U : Matrix (Fin d) (Fin d) S) (hU : U.BlockTriangular id) :
    (compoundOf j U).BlockTriangular (fun t => toLex (compoundEnum j t)) := by
  classical
  intro t s hts
  -- `hts : toLex (enum s) < toLex (enum t)` in the Pi.Lex order. Unfold to get the first index `i`
  -- where they differ: `enum s i < enum t i`.
  rw [compoundOf, Matrix.of_apply]
  obtain ⟨i, _, hlt⟩ : ∃ i, (∀ k, k < i → compoundEnum j s k = compoundEnum j t k) ∧
      compoundEnum j s i < compoundEnum j t i := hts
  exact det_submatrix_upperTriangular_vanish U hU (compoundEnum_strictMono j t)
    (compoundEnum_strictMono j s).monotone hlt

/-- The diagonal entry of `compoundOf j U` for triangular `U` is the `j`-fold product of diagonal
entries of `U` over the subset enumerated by `t`. -/
theorem compoundOf_diag {S : Type*} [CommRing S] (j : ℕ)
    (U : Matrix (Fin d) (Fin d) S) (hU : U.BlockTriangular id)
    (t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) :
    compoundOf j U t t = ∏ i, U (compoundEnum j t i) (compoundEnum j t i) := by
  rw [compoundOf, Matrix.of_apply,
    det_submatrix_upperTriangular_diag U hU (compoundEnum j t) (compoundEnum_strictMono j t)]

/-! ### The diagonal-product multiset of the compound = the `j`-fold products of the diagonal

For the diagonal entries `g : Fin d → S` of a triangular matrix, the multiset of `j`-fold products
`∏_{a ∈ S} g a` over all `j`-subsets `S` (= the diagonal multiset of `compoundOf j U`) is exactly
`(powersetCard j (univ.val.map g)).map prod`. This is the combinatorial heart matching the
compound's diagonal to the eigenvalue `j`-products. -/

/-- Product of `g` over the ordered enumeration of the `j`-subset indexed by `t` equals the product
of `g` over that subset (`Finset`). -/
theorem prod_compoundEnum {S : Type*} [CommMonoid S] (j : ℕ) (g : Fin d → S)
    (t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) :
    ∏ i, g (compoundEnum j t i)
      = ∏ a ∈ ((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t :
          Set.powersetCard (Fin d) j).1, g a := by
  classical
  set Sset := (ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t with hSset
  have himg : (Sset : Finset (Fin d))
      = Finset.univ.image (Set.powersetCard.ofFinEmbEquiv.symm Sset) := by
    rw [Set.powersetCard.ofFinEmbEquiv_symm_apply, Finset.image_orderEmbOfFin_univ]
  calc ∏ i, g (compoundEnum j t i)
      = ∏ i, g ((Set.powersetCard.ofFinEmbEquiv.symm Sset) i) := by
        refine Finset.prod_congr rfl (fun i _ => ?_); rw [compoundEnum]
    _ = ∏ a ∈ (Sset : Finset (Fin d)), g a := by
        rw [himg, Finset.prod_image
          (fun a _ b _ h => (Set.powersetCard.ofFinEmbEquiv.symm Sset).injective h)]

/-- The multiset of `j`-subsets of `Fin d`, as enumerated by the compound index, equals the multiset
`Multiset.powersetCard j univ.val` of `j`-sub-multisets of `univ.val`. (Bridge between the
`Set.powersetCard (Fin d) j` subtype enumeration used by the compound and the
`Multiset.powersetCard` on the LHS of the target.) -/
theorem subset_multiset_eq_powersetCard (j : ℕ) :
    (Finset.univ.val.map fun t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) =>
        ((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t :
          Set.powersetCard (Fin d) j).1.val)
      = Multiset.powersetCard j (Finset.univ.val : Multiset (Fin d)) := by
  classical
  -- Step 1: reindex `Fin N ≃ Set.powersetCard (Fin d) j` to a `univ`-over-subtype enumeration.
  have hstep1 : (Finset.univ.val.map
        fun t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) =>
        ((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t :
          Set.powersetCard (Fin d) j).1.val)
      = (Finset.univ : Finset (Set.powersetCard (Fin d) j)).val.map
          (fun S' : Set.powersetCard (Fin d) j => S'.1.val) := by
    rw [← Multiset.map_univ_val_equiv
      (ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm, Multiset.map_map]
    rfl
  -- Step 2: `univ.val (subtype).map (·.1)` = `(univ.filter (·.card = j)).val`
  -- = `powersetCard j univ`.
  have hstep2 : (Finset.univ : Finset (Set.powersetCard (Fin d) j)).val.map
        (fun S' : Set.powersetCard (Fin d) j => S'.1)
      = (Finset.powersetCard j (Finset.univ : Finset (Fin d))).val := by
    rw [Finset.univ_val_map_subtype_val (α := Finset (Fin d))
      (p := fun s => s ∈ Set.powersetCard (Fin d) j)]
    congr 1
    ext s
    simp only [Finset.mem_filter, Finset.mem_univ, true_and, Set.powersetCard.mem_iff,
      Finset.mem_powersetCard, Finset.subset_univ]
  calc (Finset.univ.val.map fun t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) =>
        ((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t :
          Set.powersetCard (Fin d) j).1.val)
      = (Finset.univ : Finset (Set.powersetCard (Fin d) j)).val.map
          (fun S' : Set.powersetCard (Fin d) j => S'.1.val) := hstep1
    _ = ((Finset.univ : Finset (Set.powersetCard (Fin d) j)).val.map
          (fun S' : Set.powersetCard (Fin d) j => S'.1)).map (fun F : Finset (Fin d) => F.val) :=
        (Multiset.map_map (fun F : Finset (Fin d) => F.val)
          (fun S' : Set.powersetCard (Fin d) j => S'.1) Finset.univ.val).symm
    _ = (Finset.powersetCard j (Finset.univ : Finset (Fin d))).val.map
          (fun F : Finset (Fin d) => F.val) := by
        rw [hstep2]
    _ = Multiset.powersetCard j (Finset.univ.val : Multiset (Fin d)) :=
        Finset.map_val_val_powersetCard _ _

/-- **The diagonal-product multiset of the compound.** The multiset, over all compound indices `t`,
of the `j`-fold diagonal products `∏ g (enum t i)` equals `(powersetCard j (univ.val.map g)).map
prod`, for any `g : Fin d → S` over a commutative ring. -/
theorem diag_prod_multiset_eq {S : Type*} [CommRing S] (j : ℕ) (g : Fin d → S) :
    (Finset.univ.val.map
        fun t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) =>
          ∏ i, g (compoundEnum j t i))
      = (Multiset.powersetCard j (Finset.univ.val.map g)).map Multiset.prod := by
  classical
  -- Rewrite each diagonal product as the product over the subset's underlying multiset.
  have hL : (Finset.univ.val.map
        fun t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) =>
          ∏ i, g (compoundEnum j t i))
      = (Finset.univ.val.map
        fun t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) =>
          (((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t :
            Set.powersetCard (Fin d) j).1.val.map g).prod) := by
    refine Multiset.map_congr rfl (fun t _ => ?_)
    rw [prod_compoundEnum, Finset.prod]
  rw [hL, Multiset.powersetCard_map, Multiset.map_map]
  -- Reduce to the subset-multiset bridge, mapped through `(·.map g).prod`.
  rw [show (fun t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) =>
        (((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t :
          Set.powersetCard (Fin d) j).1.val.map g).prod)
      = (fun m : Multiset (Fin d) => (m.map g).prod) ∘
        (fun t => ((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm t :
          Set.powersetCard (Fin d) j).1.val) from rfl]
  rw [← Multiset.map_map, subset_multiset_eq_powersetCard]
  rfl

/-- **Roots of a block-triangular matrix with injective ordering function.** If `M : Matrix (Fin N)
(Fin N) S` (over an integral domain) is `BlockTriangular b` with `b : Fin N → α` injective into a
linearly ordered `α`, then `M.charpoly.roots` is the diagonal multiset `univ.val.map M.diag`. Proof:
sort the index by `b` (`Tuple.sort b`); the sorted relabeling makes `M` upper triangular
(`BlockTriangular id`), its charpoly equals `M`'s (conjugation by a permutation), and the diagonal
multiset is permutation-invariant. -/
theorem roots_charpoly_of_blockTriangular_inj {S : Type*} [CommRing S] [IsDomain S] {N : ℕ}
    {α : Type*} [LinearOrder α] (M : Matrix (Fin N) (Fin N) S) {b : Fin N → α}
    (hb : Function.Injective b) (hM : M.BlockTriangular b) :
    M.charpoly.roots = Finset.univ.val.map M.diag := by
  classical
  -- Sorting permutation: `b ∘ σ` is monotone, and injective ⇒ strictly monotone.
  set σ := Tuple.sort b with hσ
  have hmono : Monotone (b ∘ σ) := Tuple.monotone_sort b
  have hsmono : StrictMono (b ∘ σ) :=
    hmono.strictMono_of_injective (hb.comp σ.injective)
  -- Reindex: `N' := M.submatrix σ σ` is BlockTriangular id.
  have hN' : (M.submatrix σ σ).BlockTriangular id := by
    intro p q hpq
    -- `id q < id p` i.e. `q < p`; want `(M.submatrix σ σ) p q = M (σ p) (σ q) = 0`,
    -- using `b (σ q) < b (σ p)` from strict monotonicity.
    have : (b ∘ σ) q < (b ∘ σ) p := hsmono hpq
    exact hM this
  -- charpoly invariance under conjugation by the permutation `σ`.
  have hcharpoly : (M.submatrix σ σ).charpoly = M.charpoly := by
    have := Matrix.charpoly_reindex σ.symm M
    rwa [Matrix.reindex_apply, Equiv.symm_symm] at this
  -- diag multiset is permutation-invariant.
  have hdiag : Finset.univ.val.map (fun i => (M.submatrix σ σ) i i)
      = Finset.univ.val.map M.diag := by
    have hd : (fun i => (M.submatrix σ σ) i i) = M.diag ∘ σ := by
      funext i; simp [Matrix.diag, Matrix.submatrix_apply]
    rw [hd, ← Multiset.map_map M.diag σ, Multiset.map_univ_val_equiv]
  rw [← hcharpoly, roots_charpoly_of_upperTriangular _ hN', hdiag]

/-- `compoundOf j ↑Q` is a unit for any matrix unit `Q`, with inverse `compoundOf j ↑Q⁻¹`
(from Cauchy–Binet `compoundOf_mul` and `compoundOf_one`). -/
theorem isUnit_compoundOf {S : Type*} [CommRing S] (j : ℕ) (Q : (Matrix (Fin d) (Fin d) S)ˣ) :
    IsUnit (compoundOf j (Q : Matrix (Fin d) (Fin d) S)) :=
  ⟨{ val := compoundOf j (Q : Matrix (Fin d) (Fin d) S)
     inv := compoundOf j (↑Q⁻¹ : (Matrix (Fin d) (Fin d) S)ˣ)
     val_inv := by rw [← compoundOf_mul, Units.mul_inv, compoundOf_one]
     inv_val := by rw [← compoundOf_mul, Units.inv_mul, compoundOf_one] }, rfl⟩

/-- **The assembly (Schur ⇒ compound roots identity).** GIVEN a Schur factorization of `A` over `ℂ`
— a unit `Q` and an upper-triangular `T` (`T.BlockTriangular id`) with `A = ↑Q * T * ↑Q⁻¹` and
diagonal multiset `univ.val.map T.diag = A.charpoly.roots` — the compound root identity
`(compoundOf j A).charpoly.roots = (powersetCard j A.charpoly.roots).map prod` holds. Proof:
Cauchy–Binet makes `compoundOf j A` conjugate (by the unit `compoundOf j ↑Q`) to the triangular
`compoundOf j T`; conjugation preserves the charpoly; `compoundOf j T` is block-triangular with
diagonal the `j`-fold products of `T`'s diagonal, whose multiset is the `j`-fold products of
`A.charpoly.roots`. -/
theorem compoundOf_charpoly_roots_of_schur (j : ℕ) (A : Matrix (Fin d) (Fin d) ℂ)
    (Q : (Matrix (Fin d) (Fin d) ℂ)ˣ) (T : Matrix (Fin d) (Fin d) ℂ)
    (hT : T.BlockTriangular id)
    (hconj : A = (Q : Matrix (Fin d) (Fin d) ℂ) * T * (↑Q⁻¹ : Matrix (Fin d) (Fin d) ℂ))
    (hdiagT : Finset.univ.val.map T.diag = A.charpoly.roots) :
    (compoundOf j A).charpoly.roots
      = (A.charpoly.roots.powersetCard j).map Multiset.prod := by
  classical
  -- `compoundOf j A` is conjugate to `compoundOf j T` by the unit `P := compoundOf j ↑Q`.
  obtain ⟨P, hP⟩ := isUnit_compoundOf j Q
  have hPinv : ((↑P⁻¹ : Matrix (Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))))
        (Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) ℂ))
      = compoundOf j (↑Q⁻¹ : (Matrix (Fin d) (Fin d) ℂ)ˣ) := by
    refine Units.inv_eq_of_mul_eq_one_right ?_
    rw [hP, ← compoundOf_mul, Units.mul_inv, compoundOf_one]
  have hAcompound : compoundOf j A
      = (↑P : Matrix _ _ ℂ) * compoundOf j T * (↑P⁻¹ : Matrix _ _ ℂ) := by
    rw [hconj, compoundOf_mul, compoundOf_mul, hP, hPinv]
  -- Charpoly is conjugation-invariant.
  have hcharpoly : (compoundOf j A).charpoly = (compoundOf j T).charpoly := by
    rw [hAcompound, Matrix.coe_units_inv P, Matrix.charpoly_units_conj P (compoundOf j T)]
  -- The triangular compound's roots = its diagonal multiset (block-triangular, injective order).
  have hinj : Function.Injective
      (fun t : Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) =>
        toLex (compoundEnum j t)) := by
    intro a b hab
    -- `toLex` injective; `compoundEnum` injective.
    have h1 : compoundEnum j a = compoundEnum j b := by
      have := congrArg ofLex hab; simpa using this
    -- `compoundEnum j t = ⇑(ofFinEmbEquiv.symm (wIndexEquiv.symm t))`; unwind the injectivities.
    have hemb : Set.powersetCard.ofFinEmbEquiv.symm
        ((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm a)
        = Set.powersetCard.ofFinEmbEquiv.symm
        ((ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm b) :=
      DFunLike.coe_injective h1
    exact (ExteriorNorm.wIndexEquiv (EuclideanSpace.basisFun (Fin d) ℝ) j).symm.injective
      (Set.powersetCard.ofFinEmbEquiv.symm.injective hemb)
  have hroots : (compoundOf j T).charpoly.roots
      = Finset.univ.val.map (compoundOf j T).diag :=
    roots_charpoly_of_blockTriangular_inj _ hinj (compoundOf_blockTriangular j T hT)
  rw [hcharpoly, hroots]
  -- Compute the diagonal multiset of `compoundOf j T` as the `j`-fold products of `T`'s diagonal.
  have hdiagcompound : Finset.univ.val.map (compoundOf j T).diag
      = (Multiset.powersetCard j (Finset.univ.val.map T.diag)).map Multiset.prod := by
    rw [show (compoundOf j T).diag
        = fun t => ∏ i, T.diag (compoundEnum j t i) from
      funext fun t => compoundOf_diag j T hT t]
    exact diag_prod_multiset_eq j T.diag
  rw [hdiagcompound, hdiagT]

/-- **The spectrum of the `j`-th exterior power (now proved sorry-free).** The multiset of
characteristic-polynomial roots of the complexified `j`-th compound matrix is exactly the multiset
of `j`-fold products of the complex eigenvalues of `M`:
```
  roots( (C_j M)_ℂ.charpoly )  =  (powersetCard j  roots(M_ℂ.charpoly)).map (∏)
```
This is the classical statement that the spectrum of `⋀^j A` is the set of `j`-fold products
`λ_{i₀}⋯λ_{i_{j-1}}` of eigenvalues of `A`, at the level of multisets (with algebraic multiplicity).

**Proof (assembled from the sorry-free pieces above).**
* The bridge `map_compoundMatrix_complex` turns the goal into a statement about the ring-agnostic
  minor-compound `compoundOf j A` with `A := M.map (algebraMap ℝ ℂ)`.
* **Schur triangulation over `ℂ`** (`Matrix.schur_triangulation`, grafted in
  `Oseledets.Mathlib.SchurTriangulation`
  from the Mathlib-style proof of Gordon Hsu): `A = U * T * star U` with `U` unitary and `T` upper
  triangular (`T.BlockTriangular id`); since `star U = U⁻¹`, `A` is similar to `T`, so `A.charpoly =
  T.charpoly` and `T`'s diagonal multiset is `A.charpoly.roots`.
* **Cauchy–Binet over any commutative ring** (`compoundOf_mul`, proved here via the abstract
  exterior power `exteriorPower.map` and `LinearMap.toMatrix_comp`): `compoundOf j` is
  multiplicative and sends units to units, so `compoundOf j A` is similar (by the unit
  `compoundOf j U`) to
  `compoundOf j T`; hence `(compoundOf j A).charpoly = (compoundOf j T).charpoly`
  (`compoundOf_charpoly_roots_of_schur`).
* **Triangular compound** (`compoundOf_blockTriangular`, `compoundOf_diag`): `compoundOf j T` is
  block-triangular in the lexicographic order of the subset enumerators, with diagonal the `j`-fold
  diagonal products of `T`; `roots_charpoly_of_blockTriangular_inj` reads off its charpoly roots as
  that diagonal multiset, and `diag_prod_multiset_eq` matches it to
  `(powersetCard j (univ.val.map T.diag)).map prod = (powersetCard j A.charpoly.roots).map prod`. -/
theorem compoundMatrix_charpoly_roots_eq (M : Matrix (Fin d) (Fin d) ℝ) (j : ℕ) :
    ((ExteriorNorm.compoundMatrix j M).map (algebraMap ℝ ℂ)).charpoly.roots
      = (((M.map (algebraMap ℝ ℂ)).charpoly.roots).powersetCard j).map Multiset.prod := by
  classical
  rw [map_compoundMatrix_complex]
  set A : Matrix (Fin d) (Fin d) ℂ := M.map (algebraMap ℝ ℂ) with hA
  -- Schur triangulation over `ℂ`: `A = U * T * star U` with `U` unitary, `T` upper triangular.
  set U : Matrix (Fin d) (Fin d) ℂ := (A.schurTriangulationUnitary : Matrix (Fin d) (Fin d) ℂ)
    with hU
  set T : Matrix (Fin d) (Fin d) ℂ := (A.schurTriangulation : Matrix (Fin d) (Fin d) ℂ) with hT
  have hTtri : T.BlockTriangular id := by rw [hT]; exact A.schurTriangulation.2
  have hschur : A = U * T * star U := A.schur_triangulation
  -- Package the unitary as a matrix unit `Q` with `↑Q⁻¹ = star ↑U`.
  let Q : (Matrix (Fin d) (Fin d) ℂ)ˣ :=
    { val := U
      inv := star U
      val_inv := by rw [hU]; exact Unitary.coe_mul_star_self A.schurTriangulationUnitary
      inv_val := by rw [hU]; exact Unitary.coe_star_mul_self A.schurTriangulationUnitary }
  have hconj : A = (Q : Matrix (Fin d) (Fin d) ℂ) * T * (↑Q⁻¹ : Matrix (Fin d) (Fin d) ℂ) := hschur
  -- The triangular factor's diagonal multiset is `A.charpoly.roots` (similar matrices, triangular).
  have hdiagT : Finset.univ.val.map T.diag = A.charpoly.roots := by
    have hAcharpoly : A.charpoly = T.charpoly := by
      rw [hconj, Matrix.coe_units_inv Q, Matrix.charpoly_units_conj Q T]
    rw [hAcharpoly, roots_charpoly_of_upperTriangular T hTtri]
    rfl
  exact compoundOf_charpoly_roots_of_schur j A Q T hTtri hconj hdiagT

theorem spectralRadius_compound_eq_prod_eigenvalueModuli [NeZero d]
    (M : Matrix (Fin d) (Fin d) ℝ) (j : ℕ) :
    (spectralRadius ℂ ((ExteriorNorm.compoundMatrix j M).map (algebraMap ℝ ℂ))).toReal
      = ∏ k ∈ Finset.range j, (eigenvalueModuli M).getD k 0 := by
  classical
  set Aℂ := (ExteriorNorm.compoundMatrix j M).map (algebraMap ℝ ℂ) with hAℂ
  -- Roots/moments of `M` over `ℂ`.
  set rootsM := ((M.map (algebraMap ℝ ℂ)).charpoly).roots with hrootsM
  set momentsM : Multiset ℝ := rootsM.map (fun z => ‖z‖) with hmomentsM
  have hcardRoots : Multiset.card rootsM = d := by
    rw [hrootsM, (Polynomial.splits_iff_card_roots).mp (IsAlgClosed.splits _),
      Matrix.charpoly_natDegree_eq_dim, Fintype.card_fin]
  have hcardMoments : Multiset.card momentsM = d := by
    rw [hmomentsM, Multiset.card_map, hcardRoots]
  have hposMoments : ∀ x ∈ momentsM, 0 ≤ x := by
    intro x hx
    rw [hmomentsM, Multiset.mem_map] at hx
    obtain ⟨z, _, rfl⟩ := hx; exact norm_nonneg z
  -- `‖∏ S‖ = (S.map ‖·‖).prod` for any complex multiset.
  have hnorm_prod : ∀ S : Multiset ℂ, ‖S.prod‖ = (S.map (fun z => ‖z‖)).prod := by
    intro S
    have := map_multiset_prod (normHom : ℂ →*₀ ℝ) S
    simpa using this
  -- `eigenvalueModuli M = momentsM.sort (· ≥ ·)`.
  have heigen : eigenvalueModuli M = momentsM.sort (· ≥ ·) := rfl
  have hlenEig : (eigenvalueModuli M).length = d := eigenvalueModuli_length M
  -- The complex spectrum of the compound = root support; describe spectrum-membership via the
  -- sharp roots identity.
  have hroots_eq : Aℂ.charpoly.roots = (rootsM.powersetCard j).map Multiset.prod := by
    rw [hAℂ, compoundMatrix_charpoly_roots_eq]
  have hspec_mem : ∀ μ : ℂ, μ ∈ spectrum ℂ Aℂ ↔
      ∃ S ∈ rootsM.powersetCard j, S.prod = μ := by
    intro μ
    rw [Matrix.mem_spectrum_iff_isRoot_charpoly, ← Polynomial.mem_roots Aℂ.charpoly_monic.ne_zero,
      hroots_eq, Multiset.mem_map]
  -- For each spectral value `μ = S.prod`, `‖μ‖ = (S.map ‖·‖).prod`, a `j`-product of moments.
  rcases le_or_gt j d with hjd | hjd
  · -- Main range `j ≤ d`.
    -- The compound dimension `choose d j` is nonzero, so the matrix algebra is nontrivial and the
    -- spectral radius is finite.
    haveI : NeZero (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) :=
      neZero_finrank_exteriorPower_of_le hjd
    haveI : Nonempty (Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) :=
      ⟨⟨0, Nat.pos_of_ne_zero (NeZero.ne _)⟩⟩
    have hfin : spectralRadius ℂ Aℂ ≠ ⊤ :=
      ne_top_of_le_ne_top (by simp) (spectrum.spectralRadius_le_nnnorm (𝕜 := ℂ) Aℂ)
    -- The take-`j` of the sorted moments, as a sub-multiset, realizes the top-`j` product.
    set Ltop := (momentsM.sort (· ≥ ·)).take j with hLtop
    have hLtop_sub : (Ltop : Multiset ℝ) ≤ momentsM := by
      have h1 : (Ltop : Multiset ℝ) ≤ ((momentsM.sort (· ≥ ·) : List ℝ) : Multiset ℝ) := by
        rw [Multiset.coe_le]
        exact ((momentsM.sort (· ≥ ·)).take_prefix j).sublist.subperm
      rwa [Multiset.sort_eq] at h1
    have hLtop_card : Multiset.card (Ltop : Multiset ℝ) = j := by
      rw [Multiset.coe_card, hLtop, List.length_take, Multiset.length_sort, hcardMoments,
        Nat.min_eq_left hjd]
    -- RHS equals the top-`j` product.
    have hlen : (momentsM.sort (· ≥ ·)).length = d := by
      rw [Multiset.length_sort, hcardMoments]
    have hRHS : ∏ k ∈ Finset.range j, (eigenvalueModuli M).getD k 0 = Ltop.prod := by
      rw [heigen, hLtop, prod_take_eq_prod_range_getD _ _ (by rw [hlen]; exact hjd)]
    rw [hRHS]
    -- Now prove `(spectralRadius).toReal = Ltop.prod` by two inequalities.
    -- The top-`j` product is nonnegative (entries of `Ltop` are entries of `momentsM`).
    have hLtop_nonneg : 0 ≤ Ltop.prod := by
      apply List.prod_nonneg
      intro x hx
      have : x ∈ momentsM := Multiset.mem_of_le hLtop_sub (by rw [Multiset.mem_coe]; exact hx)
      exact hposMoments x this
    refine le_antisymm ?_ ?_
    · -- ≤: every spectral modulus is ≤ the top-`j` product.
      refine spectralRadius_toReal_le _ hLtop_nonneg hfin ?_
      intro μ hμ
      rw [hspec_mem] at hμ
      obtain ⟨S, hS, rfl⟩ := hμ
      rw [Multiset.mem_powersetCard] at hS
      -- `‖∏ S‖ = ∏_{x∈S} ‖x‖ = (S.map ‖·‖).prod`.
      rw [hnorm_prod S]
      -- `S.map ‖·‖ ≤ momentsM`, card `j`; apply the combinatorial bound.
      have hsub : (S.map (fun z => ‖z‖)) ≤ momentsM := by
        rw [hmomentsM]; exact Multiset.map_le_map hS.1
      have hcard' : Multiset.card (S.map (fun z => ‖z‖)) = j := by
        rw [Multiset.card_map]; exact hS.2
      have := prod_le_take_sort (m := momentsM) (T := S.map (fun z => ‖z‖))
        hposMoments hsub hcard'
      rwa [← hLtop] at this
    · -- ≥: the top-`j` subset realizes a spectral value of that modulus.
      -- Find `S ≤ rootsM`, `card S = j`, with `S.map ‖·‖ = Ltop` (as multisets).
      obtain ⟨S, hSle, hSmap⟩ := exists_le_of_le_map
        (f := fun z : ℂ => ‖z‖) (T := (Ltop : Multiset ℝ)) (s := rootsM)
        (by rw [← hmomentsM]; exact hLtop_sub)
      have hScard : Multiset.card S = j := by
        have : Multiset.card (S.map (fun z => ‖z‖)) = Multiset.card (Ltop : Multiset ℝ) := by
          rw [hSmap]
        rwa [Multiset.card_map, hLtop_card] at this
      -- `S.prod` is a spectral value with `‖S.prod‖ = Ltop.prod`.
      have hSspec : S.prod ∈ spectrum ℂ Aℂ := by
        rw [hspec_mem]
        exact ⟨S, by rw [Multiset.mem_powersetCard]; exact ⟨hSle, hScard⟩, rfl⟩
      have hnormS : ‖S.prod‖ = Ltop.prod := by
        rw [hnorm_prod S, hSmap, Multiset.prod_coe]
      have := le_spectralRadius_toReal Aℂ hfin hSspec
      rwa [hnormS] at this
  · -- Tail `j > d`: the compound has dimension `choose d j = 0`, spectrum empty, radius `0`;
    -- the RHS product contains the zero factor `getD d 0 = 0`.
    -- RHS = 0 because `getD d 0 = 0` (list has length `d`) and `d ∈ range j`.
    have hRHS0 : ∏ k ∈ Finset.range j, (eigenvalueModuli M).getD k 0 = 0 := by
      apply Finset.prod_eq_zero (i := d) (by rw [Finset.mem_range]; exact hjd)
      rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none (by rw [hlenEig]), Option.getD_none]
    rw [hRHS0]
    -- The compound dimension is `0`, so the matrix is over the empty index; spectrum is empty.
    have hdim0 : Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))) = 0 := by
      rw [exteriorPower.finrank_eq, finrank_euclideanSpace, Fintype.card_fin,
        Nat.choose_eq_zero_of_lt hjd]
    -- `Fin (finrank …)` is empty.
    haveI hempty : IsEmpty (Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) := by
      rw [hdim0]; exact Fin.isEmpty
    -- The matrix algebra is a subsingleton (`1 = 0`), so every spectrum is empty.
    have hsubsingleton : Subsingleton (Matrix (Fin (Module.finrank ℝ
        (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))))
        (Fin (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))) ℂ) :=
      inferInstance
    have hspecempty : spectrum ℂ Aℂ = ∅ := by
      rw [Set.eq_empty_iff_forall_notMem]
      intro μ hμ
      rw [spectrum.mem_iff] at hμ
      apply hμ
      -- In a subsingleton ring `algebraMap μ - Aℂ` is a unit (everything is).
      exact (isUnit_of_subsingleton _)
    have hradius0 : spectralRadius ℂ Aℂ = 0 := by
      rw [spectralRadius, hspecempty]; simp
    rw [hradius0, ENNReal.toReal_zero]

/-- **A complex matrix of spectral radius `0` is nilpotent.** If `spectralRadius ℂ A = 0` then every
spectral value (= every root of `A.charpoly`) has norm `0`, hence is `0`; the (monic, split)
characteristic polynomial is therefore `X ^ N`, and Cayley–Hamilton gives `A ^ N = 0`. -/
theorem isNilpotent_of_spectralRadius_eq_zero {N : ℕ} (A : Matrix (Fin N) (Fin N) ℂ)
    (h : spectralRadius ℂ A = 0) : IsNilpotent A := by
  -- Every spectral value is `0`.
  have hspec : ∀ μ ∈ spectrum ℂ A, μ = 0 := by
    intro μ hμ
    have : (‖μ‖₊ : ENNReal) ≤ spectralRadius ℂ A := le_iSup₂ (f := fun k _ => (‖k‖₊ : ENNReal)) μ hμ
    rw [h, nonpos_iff_eq_zero] at this
    simpa using this
  -- Every charpoly root is `0`.
  have hroots : ∀ μ ∈ A.charpoly.roots, μ = 0 := by
    intro μ hμ
    refine hspec μ ?_
    rw [Matrix.mem_spectrum_iff_isRoot_charpoly]
    exact (Polynomial.mem_roots'.mp hμ).2
  -- The charpoly splits and is monic, so it is the product over its roots of `(X - root)`.
  have hsplits : A.charpoly.Splits := IsAlgClosed.splits _
  have hmonic : A.charpoly.Monic := A.charpoly_monic
  have hprod : A.charpoly = (A.charpoly.roots.map fun a => Polynomial.X - Polynomial.C a).prod := by
    have := hsplits.eq_prod_roots_of_monic hmonic
    simpa using this
  -- All roots are `0`, so the product is `X ^ (card roots) = X ^ N`.
  have hcard : A.charpoly.roots.card = N := by
    rw [(Polynomial.splits_iff_card_roots).mp hsplits, Matrix.charpoly_natDegree_eq_dim,
      Fintype.card_fin]
  have hXpow : A.charpoly = Polynomial.X ^ N := by
    rw [hprod]
    have hmap : (A.charpoly.roots.map fun a => Polynomial.X - Polynomial.C a)
        = A.charpoly.roots.map fun _ => (Polynomial.X : Polynomial ℂ) := by
      refine Multiset.map_congr rfl ?_
      intro a ha
      rw [hroots a ha, map_zero, sub_zero]
    rw [hmap, Multiset.map_const', Multiset.prod_replicate, hcard]
  -- Cayley–Hamilton.
  refine ⟨N, ?_⟩
  have := A.aeval_self_charpoly
  rwa [hXpow, map_pow, Polynomial.aeval_X] at this

/-- **The Gelfand limit for the compound, in product form.** For every `j ≥ 1`,
```
  (∏_{k<j} σₖ(Mⁿ))^{1/n}  →  ρ(C_j(M)_ℂ)   as n → ∞,
```
because `∏_{k<j} σₖ(Mⁿ) = ‖C_j(Mⁿ)‖ = ‖(C_j M)ⁿ‖`
(`ExteriorNorm.prod_singularValues_eq_l2_opNorm_compound` + `compoundMatrix_pow`) and Gelfand's
formula `‖Bⁿ‖^{1/n} → ρ(B_ℂ)` (`tendsto_pow_norm_one_div_spectralRadius`) applies to `B = C_j(M)`.
Sorry-free. -/
theorem tendsto_prod_singularValues_pow (M : Matrix (Fin d) (Fin d) ℝ) (j : ℕ)
    [NeZero (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))] :
    Tendsto (fun n : ℕ =>
        (∏ k ∈ Finset.range j, (Matrix.toEuclideanLin (M ^ n)).singularValues k) ^ (1 / n : ℝ))
      atTop (𝓝 (spectralRadius ℂ
        ((ExteriorNorm.compoundMatrix j M).map (algebraMap ℝ ℂ))).toReal) := by
  -- Gelfand for the compound matrix `C_j(M)`.
  have hg := tendsto_pow_norm_one_div_spectralRadius (ExteriorNorm.compoundMatrix j M)
  refine hg.congr fun n => ?_
  -- `∏_{k<j} σₖ(Mⁿ) = ‖C_j(Mⁿ)‖ = ‖(C_j M)ⁿ‖`.
  rw [ExteriorNorm.prod_singularValues_eq_l2_opNorm_compound, compoundMatrix_pow]

/-- **Monotonicity of the sorted eigenvalue moduli.** Because `eigenvalueModuli M` is the
non-increasing (`· ≥ ·`) sort of the modulus multiset, the `i`-th entry never exceeds an earlier
entry: for `k ≤ i` with `i` inside the list, `(eigenvalueModuli M).getD k 0 ≥ (eigenvalueModuli
M).getD i 0`. Pure list bookkeeping (no matrix content). -/
theorem eigenvalueModuli_getD_antitone (M : Matrix (Fin d) (Fin d) ℝ) {k i : ℕ}
    (hki : k ≤ i) (hi : i < (eigenvalueModuli M).length) :
    (eigenvalueModuli M).getD i 0 ≤ (eigenvalueModuli M).getD k 0 := by
  have hk : k < (eigenvalueModuli M).length := lt_of_le_of_lt hki hi
  have hsorted : (eigenvalueModuli M).Pairwise (· ≥ ·) := by
    rw [eigenvalueModuli]; exact Multiset.pairwise_sort _ _
  have hrel : (eigenvalueModuli M).get ⟨k, hk⟩ ≥ (eigenvalueModuli M).get ⟨i, hi⟩ :=
    hsorted.rel_get_of_le (by exact_mod_cast hki)
  rw [List.getD_eq_getElem?_getD, List.getD_eq_getElem?_getD,
    List.getElem?_eq_getElem hk, List.getElem?_eq_getElem hi, Option.getD_some, Option.getD_some]
  simpa [List.get_eq_getElem] using hrel

/-- **Residual leaf 2 (telescoping / `log`-of-zero bookkeeping).** Given the product-form Gelfand
limits — `(∏_{k<j} σₖ(Mⁿ))^{1/n} → ∏_{k<j}|λₖ|` for `j = i` and `j = i+1`, packaged via residual
leaf 1 — together with the eventual vanishing of `σᵢ(Mⁿ)` when `|λᵢ| = 0` (the honest hypothesis
`hvanish`, discharged at the call site from the nilpotency of the compound), the single-index
Yamamoto limit `(1/n) log σᵢ(Mⁿ) → log|λᵢ|` follows by telescoping
`log(∏_{k<i+1}) − log(∏_{k<i}) = log σᵢ`.

This is the "elementary but voluminous" repackaging flagged as sub-lemma S15 in the feasibility
report: it passes from the multiplicative (`^{1/n}`) form to the additive (`(1/n)·log`) form,
divides out the lower product, and handles the junk-value branch where `|λᵢ|` vanishes
(`Real.log 0 = 0`). Sorry-free; uses only `Real`-analysis plumbing (`Real.log_rpow`,
`Real.log_prod`, `Filter.Tendsto.log`) plus the sortedness of `eigenvalueModuli` and the
honest `hvanish` hypothesis. -/
theorem yamamoto_prod_to_index [NeZero d] (M : Matrix (Fin d) (Fin d) ℝ) (i : ℕ)
    (hi : Tendsto (fun n : ℕ =>
        (∏ k ∈ Finset.range (i + 1), (Matrix.toEuclideanLin (M ^ n)).singularValues k)
          ^ (1 / n : ℝ))
      atTop (𝓝 (∏ k ∈ Finset.range (i + 1), (eigenvalueModuli M).getD k 0)))
    (hi' : Tendsto (fun n : ℕ =>
        (∏ k ∈ Finset.range i, (Matrix.toEuclideanLin (M ^ n)).singularValues k) ^ (1 / n : ℝ))
      atTop (𝓝 (∏ k ∈ Finset.range i, (eigenvalueModuli M).getD k 0)))
    (hvanish : (eigenvalueModuli M).getD i 0 = 0 →
        ∀ᶠ n : ℕ in atTop, (Matrix.toEuclideanLin (M ^ n)).singularValues i = 0) :
    Tendsto (fun n : ℕ => (n : ℝ)⁻¹ *
        Real.log ((Matrix.toEuclideanLin (M ^ n)).singularValues i))
      atTop (𝓝 (Real.log ((eigenvalueModuli M).getD i 0))) := by
  -- Abbreviations.
  set lami : ℝ := (eigenvalueModuli M).getD i 0 with hlami_def
  -- Both eigenvalue moduli are nonnegative (they are norms of complex numbers).
  have hmem_nonneg : ∀ x ∈ eigenvalueModuli M, 0 ≤ x := by
    intro x hx
    simp only [eigenvalueModuli, Multiset.mem_sort, Multiset.mem_map] at hx
    obtain ⟨z, _, rfl⟩ := hx
    exact norm_nonneg z
  have hmod_nonneg : ∀ k, 0 ≤ (eigenvalueModuli M).getD k 0 := by
    intro k
    rcases lt_or_ge k (eigenvalueModuli M).length with hk | hk
    · rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem hk, Option.getD_some]
      exact hmem_nonneg _ (List.getElem_mem hk)
    · rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none hk, Option.getD_none]
  rcases eq_or_lt_of_le (hmod_nonneg i) with hlami_zero | hlami_pos
  · -- **Zero case**: `λᵢ = 0`, so the target limit is `Real.log 0 = 0`, and the `i`-th singular
    -- value vanishes eventually (`hvanish`), making the sequence eventually constant `0`.
    have hlami0 : lami = 0 := hlami_zero.symm
    rw [hlami0, Real.log_zero]
    apply Tendsto.congr' (f₁ := fun _ : ℕ => (0 : ℝ))
    · filter_upwards [hvanish hlami0] with n hn
      rw [hn, Real.log_zero, mul_zero]
    · exact tendsto_const_nhds
  · -- **Positive case**: `λᵢ > 0`, hence (by sortedness) every earlier modulus is `> 0`, so both
    -- product limits are positive; take `log` of both `Tendsto`s and subtract.
    have hi_lt_len : i < (eigenvalueModuli M).length := by
      by_contra h
      push Not at h
      rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none h, Option.getD_none] at hlami_pos
      exact lt_irrefl _ hlami_pos
    -- Each factor of the top product is positive.
    have hfac_pos : ∀ k ∈ Finset.range (i + 1), 0 < (eigenvalueModuli M).getD k 0 := by
      intro k hk
      rw [Finset.mem_range, Nat.lt_succ_iff] at hk
      exact lt_of_lt_of_le hlami_pos (eigenvalueModuli_getD_antitone M hk hi_lt_len)
    -- The two product limits are positive.
    have hP1_pos : 0 < ∏ k ∈ Finset.range (i + 1), (eigenvalueModuli M).getD k 0 :=
      Finset.prod_pos hfac_pos
    have hP0_pos : 0 < ∏ k ∈ Finset.range i, (eigenvalueModuli M).getD k 0 :=
      Finset.prod_pos fun k hk => hfac_pos k (by
        rw [Finset.mem_range] at hk ⊢; omega)
    -- Take `log` of both convergences.
    have hlog1 := hi.log hP1_pos.ne'
    have hlog0 := hi'.log hP0_pos.ne'
    -- The difference of the two log-sequences is `(1/n) log σᵢ(Mⁿ)`, eventually.
    -- First, `log` of the product limits telescopes to `log λᵢ`.
    have hlami_eq : Real.log (∏ k ∈ Finset.range (i + 1), (eigenvalueModuli M).getD k 0)
        - Real.log (∏ k ∈ Finset.range i, (eigenvalueModuli M).getD k 0) = Real.log lami := by
      rw [hlami_def, Real.log_prod (fun k hk => (hfac_pos k hk).ne'),
        Real.log_prod (fun k hk => (hfac_pos k (by rw [Finset.mem_range] at hk ⊢; omega)).ne'),
        Finset.sum_range_succ]
      ring
    -- Combine: `hlog1 - hlog0 → log λᵢ`.
    have hcomb := hlog1.sub hlog0
    rw [hlami_eq] at hcomb
    -- Match the combined sequence to the goal sequence, eventually.
    refine hcomb.congr' ?_
    filter_upwards [hi.eventually (eventually_gt_nhds hP1_pos),
      hi'.eventually (eventually_gt_nhds hP0_pos),
      eventually_ge_atTop 1] with n hn1 hn0 hn_ge
    have hn_ne : (1 / n : ℝ) ≠ 0 := by
      have : (0 : ℝ) < n := by exact_mod_cast Nat.lt_of_lt_of_le Nat.zero_lt_one hn_ge
      positivity
    -- At such `n`, all singular values in the top product are positive.
    -- `(∏σ)^{1/n} > 0` forces `∏σ > 0`.
    have hPn1_pos : 0 < ∏ k ∈ Finset.range (i + 1),
        (Matrix.toEuclideanLin (M ^ n)).singularValues k := by
      by_contra h
      push Not at h
      have hge : 0 ≤ ∏ k ∈ Finset.range (i + 1),
          (Matrix.toEuclideanLin (M ^ n)).singularValues k :=
        Finset.prod_nonneg fun k _ => (Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg k
      have : ∏ k ∈ Finset.range (i + 1),
          (Matrix.toEuclideanLin (M ^ n)).singularValues k = 0 := le_antisymm h hge
      rw [this, Real.zero_rpow hn_ne] at hn1
      exact lt_irrefl _ hn1
    have hPn0_pos : 0 < ∏ k ∈ Finset.range i,
        (Matrix.toEuclideanLin (M ^ n)).singularValues k := by
      by_contra h
      push Not at h
      have hge : 0 ≤ ∏ k ∈ Finset.range i,
          (Matrix.toEuclideanLin (M ^ n)).singularValues k :=
        Finset.prod_nonneg fun k _ => (Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg k
      have : ∏ k ∈ Finset.range i,
          (Matrix.toEuclideanLin (M ^ n)).singularValues k = 0 := le_antisymm h hge
      rw [this, Real.zero_rpow hn_ne] at hn0
      exact lt_irrefl _ hn0
    -- `σᵢ(Mⁿ) > 0` since the top product is positive and it is one of the factors.
    have hσi_pos : 0 < (Matrix.toEuclideanLin (M ^ n)).singularValues i := by
      rw [Finset.prod_range_succ] at hPn1_pos
      nlinarith [Finset.prod_nonneg (fun k (_ : k ∈ Finset.range i) =>
        (Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg k),
        (Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg i]
    -- Now compute the difference of logs of `rpow`s.
    rw [Real.log_rpow hPn1_pos, Real.log_rpow hPn0_pos,
      Finset.prod_range_succ, Real.log_mul hPn0_pos.ne' hσi_pos.ne']
    ring

/-! ## Yamamoto's theorem (assembled from the two residual leaves, sorry-free glue) -/

/-- **Yamamoto's theorem (the singular-value / eigenvalue-modulus limit).**
For every real `d × d` matrix `M` and every sorted index `i`, the normalized log of the `i`-th
singular value of the power `Mⁿ` converges to `log` of the `i`-th largest eigenvalue modulus of
`M`:
```
  (1/n) · log σᵢ(Mⁿ)  →  log |λᵢ(M)|   as n → ∞.
```
Equivalently `(σᵢ(Mⁿ))^{1/n} → |λᵢ(M)|`. This is the classical theorem of Yamamoto (1967), in the
logarithmic form consumed by the Oseledets spectrum.

This is assembled by **Strategy C** (exterior-power / Gelfand): the product-form Gelfand limits
`(∏_{k<j} σₖ(Mⁿ))^{1/n} → ρ(C_j(M))` (`tendsto_prod_singularValues_pow`, sorry-free) are rewritten
through the residual spectral fact (`spectralRadius_compound_eq_prod_eigenvalueModuli`,
`ρ(C_{i+1}(M)) = ∏_{k≤i}|λₖ|`) and telescoped through `yamamoto_prod_to_index` (now sorry-free) to
the single index `i`. The glue here is sorry-free; the former single residual matrix-analysis fact
`spectralRadius_compound_eq_prod_eigenvalueModuli` is now itself **proved sorry-free** (via
`compoundMatrix_charpoly_roots_eq` + ℂ-Schur triangulation — see
`Oseledets.Mathlib.SchurTriangulation`), so this
whole module is now sorry-free.

For the degenerate `d = 0` case (no `NeZero d`) the statement is handled by the constant-cocycle
consumer directly, which always supplies `[NeZero d]`. -/
theorem yamamoto_singularValues_tendsto [NeZero d] (M : Matrix (Fin d) (Fin d) ℝ) (i : ℕ) :
    Tendsto (fun n : ℕ => (n : ℝ)⁻¹ *
        Real.log ((Matrix.toEuclideanLin (M ^ n)).singularValues i))
      atTop (𝓝 (Real.log ((eigenvalueModuli M).getD i 0))) := by
  rcases lt_or_ge i d with hid | hid
  · -- Main range `i < d`: both compound dimensions `C_{i+1}`, `C_i` are nonempty, so the two
    -- product-form Gelfand limits apply; rewrite each spectral radius via residual leaf 1 and
    -- telescope via residual leaf 2.
    haveI : NeZero (Module.finrank ℝ (⋀[ℝ]^(i + 1) (EuclideanSpace ℝ (Fin d)))) :=
      neZero_finrank_exteriorPower_of_le hid
    haveI : NeZero (Module.finrank ℝ (⋀[ℝ]^i (EuclideanSpace ℝ (Fin d)))) :=
      neZero_finrank_exteriorPower_of_le hid.le
    have hi := tendsto_prod_singularValues_pow M (i + 1)
    rw [spectralRadius_compound_eq_prod_eigenvalueModuli M (i + 1)] at hi
    have hi' := tendsto_prod_singularValues_pow M i
    rw [spectralRadius_compound_eq_prod_eigenvalueModuli M i] at hi'
    have hvanish : (eigenvalueModuli M).getD i 0 = 0 →
        ∀ᶠ n : ℕ in atTop, (Matrix.toEuclideanLin (M ^ n)).singularValues i = 0 := by
      intro hzero
      -- With `|λᵢ| = 0`, the spectral radius of the `(i+1)`-st compound vanishes, so the compound
      -- is nilpotent; its powers vanish eventually, forcing the top `σ`-product (= the compound
      -- norm) and hence `σᵢ(Mⁿ)` to vanish eventually.
      set B := ExteriorNorm.compoundMatrix (i + 1) M with hB
      -- spectral radius of the compound = `∏_{k<i+1} |λₖ| = 0`.
      have hrho0 : (spectralRadius ℂ (B.map (algebraMap ℝ ℂ))).toReal = 0 := by
        rw [hB, spectralRadius_compound_eq_prod_eigenvalueModuli M (i + 1)]
        apply Finset.prod_eq_zero (Finset.self_mem_range_succ i)
        exact hzero
      -- The spectral radius is finite (bounded by the operator norm), so `toReal = 0 ⇒ = 0`.
      have hfin : spectralRadius ℂ (B.map (algebraMap ℝ ℂ)) ≠ ⊤ :=
        ne_top_of_le_ne_top (by simp) (spectrum.spectralRadius_le_nnnorm _)
      have hrho : spectralRadius ℂ (B.map (algebraMap ℝ ℂ)) = 0 := by
        rwa [ENNReal.toReal_eq_zero_iff, or_iff_left hfin] at hrho0
      -- Hence the complexified compound is nilpotent, and so is `B` itself.
      have hnilℂ : IsNilpotent (B.map (algebraMap ℝ ℂ)) :=
        isNilpotent_of_spectralRadius_eq_zero _ hrho
      obtain ⟨N, hN⟩ := hnilℂ
      have hBN : B ^ N = 0 := by
        have hmap : (B ^ N).map (algebraMap ℝ ℂ) = 0 := by
          rw [Matrix.map_pow, hN]
        ext a b
        have hab := congrArg (fun Z => Z a b) hmap
        simp only [Matrix.map_apply, Matrix.zero_apply] at hab
        exact (algebraMap ℝ ℂ).injective (by simpa using hab)
      -- For `n ≥ N`, `Bⁿ = 0`, so the top `σ`-product vanishes, hence `σᵢ(Mⁿ) = 0`.
      filter_upwards [eventually_ge_atTop N] with n hn
      have hBn0 : B ^ n = 0 := by
        obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le hn
        rw [pow_add, hBN, zero_mul]
      have hprod0 : ∏ k ∈ Finset.range (i + 1),
          (Matrix.toEuclideanLin (M ^ n)).singularValues k = 0 := by
        rw [ExteriorNorm.prod_singularValues_eq_l2_opNorm_compound, compoundMatrix_pow, ← hB, hBn0,
          norm_zero]
      -- The top product is `(∏_{k<i} σₖ) * σᵢ`; since `σᵢ` is the smallest factor (antitone) and
      -- the product is `0`, in fact `σᵢ(Mⁿ) = 0`.
      rw [Finset.prod_range_succ] at hprod0
      by_contra hne
      have hσi : 0 < (Matrix.toEuclideanLin (M ^ n)).singularValues i :=
        lt_of_le_of_ne ((Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg i) (Ne.symm hne)
      have hlow : 0 < ∏ k ∈ Finset.range i,
          (Matrix.toEuclideanLin (M ^ n)).singularValues k :=
        Finset.prod_pos fun k hk => lt_of_lt_of_le hσi
          ((Matrix.toEuclideanLin (M ^ n)).singularValues_antitone
            (by rw [Finset.mem_range] at hk; omega))
      exact (mul_pos hlow hσi).ne' hprod0
    exact yamamoto_prod_to_index M i hi hi' hvanish
  · -- Tail `i ≥ d`: the `i`-th singular value is `0` (`singularValues_of_finrank_le`) and the
    -- `i`-th eigenvalue modulus is `0` (`getD` past the length-`d` list); both sides are the
    -- constant `Real.log 0 = 0`. Sorry-free.
    have hσ : ∀ n : ℕ, (Matrix.toEuclideanLin (M ^ n)).singularValues i = 0 := by
      intro n
      exact (Matrix.toEuclideanLin (M ^ n)).singularValues_of_finrank_le
        (by rw [finrank_euclideanSpace, Fintype.card_fin]; exact hid)
    have hlam : (eigenvalueModuli M).getD i 0 = 0 := by
      rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none, Option.getD_none]
      rw [eigenvalueModuli_length]; exact hid
    simp only [hσ, hlam, Real.log_zero, mul_zero]
    exact tendsto_const_nhds

/-! ## The full Lyapunov spectrum of a general constant cocycle (given Yamamoto) -/

section Spectrum

variable {μ : Measure X} {T : X → X} [IsProbabilityMeasure μ] (hT : Ergodic T μ)
    {M : Matrix (Fin d) (Fin d) ℝ} (hdet : M.det ≠ 0) [NeZero d]

include hdet in
/-- **The full Lyapunov spectrum of a general (non-symmetric) constant cocycle.**
For an invertible real generator `M` (no symmetry assumed) and every sorted index `i`, the `i`-th
Lyapunov exponent of the constant cocycle `x ↦ M` is `log` of the `i`-th largest eigenvalue
modulus of `M`:
```
  exponents (fun _ => M) … i = log |λᵢ(M)|.
```

This is the **general** spectrum statement, of which the symmetric `Oseledets.exponents_const`
(where `|λᵢ(M)| = |M|.eigenvalues₀ i`) and the top-exponent (`i = 0`, the spectral radius) facts
are special cases.

The proof is by **uniqueness of limits**, given Yamamoto's theorem
(`yamamoto_singularValues_tendsto`): `exponents (fun _ => M) … i` is, by construction
(`Oseledets.exponents_tendsto_log_singularValue`), the limit of the sequence
`(1/n) log σᵢ(cocycle (fun _ => M) T n x)`, and the constant cocycle is the matrix power
(`Oseledets.cocycle_const`), so that sequence is exactly `(1/n) log σᵢ(Mⁿ)`, whose limit is
`log |λᵢ(M)|` by Yamamoto. As both sides are base-point independent, a single point extracted from
the (`NeBot`) a.e.-filter of the probability measure suffices. -/
theorem exponents_const_general (i : Fin d) :
    exponents hT (const_det_ne_zero hdet) (const_measurable M) (const_integrableLogNorm M)
        (const_integrableLogNorm_inv M) i
      = Real.log ((eigenvalueModuli M).getD (i : ℕ) 0) := by
  -- Extract a single point at which the σ-limit defining `exponents … i` holds.
  obtain ⟨x, hx⟩ := (exponents_tendsto_log_singularValue hT (const_det_ne_zero hdet)
    (const_measurable M) (const_integrableLogNorm M) (const_integrableLogNorm_inv M) i).exists
  -- Rewrite the constant cocycle as the matrix power inside the σ-sequence.
  have hcoc : ∀ n : ℕ,
      (Matrix.toEuclideanLin (cocycle (fun _ => M) T n x)).singularValues (i : ℕ)
        = (Matrix.toEuclideanLin (M ^ n)).singularValues (i : ℕ) := by
    intro n; rw [cocycle_const]
  -- Both `exponents … i` and `log |λᵢ(M)|` are the limit of the SAME sequence.
  have hx' : Tendsto (fun n : ℕ => (n : ℝ)⁻¹ *
      Real.log ((Matrix.toEuclideanLin (M ^ n)).singularValues (i : ℕ)))
      atTop (𝓝 (exponents hT (const_det_ne_zero hdet) (const_measurable M)
        (const_integrableLogNorm M) (const_integrableLogNorm_inv M) i)) := by
    refine hx.congr (fun n => ?_)
    rw [hcoc n]
  exact tendsto_nhds_unique hx' (yamamoto_singularValues_tendsto M (i : ℕ))

end Spectrum

end Oseledets
