/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Entropy.AbramovRokhlinDefect
import Oseledets.Entropy.CondBlockSubadditive
import Oseledets.Entropy.CondEntropyContinuous
import Oseledets.Entropy.JoinSigmaAlgebra

/-!
# The moving-σ-algebra conditional Kolmogorov–Sinai limit (issue #13, capstone)

This file proves the **capstone** of the Abramov–Rokhlin programme: the moving-index conditional
Kolmogorov–Sinai limit. Writing `A_n := ksJoin hT P n` for the `n`-fold `P`-join,
`σ(B_n) := generatedSigmaAlgebra μ (ksJoin hT Q n)` for the **increasing filtration** generated by
the `Q`-joins, and `f_n := condEntropy μ (σ(B_n)) (A_n).cells`, the main theorem
`tendsto_condEntropy_genJoin_div` states that the Cesàro average `f_n / n` of the conditional join
entropy **against the moving conditioning σ-algebra** `σ(B_n)` converges to the relative
Kolmogorov–Sinai entropy `condKsEntropyPartition hm hT hinv P = h(P, T | 𝒜)`, **provided the
filtration saturates** `𝒜`, i.e. `⨆ n, σ(B_n) = 𝒜` (the hypothesis `hsat`). The saturation
hypothesis is essential — the statement is false without it (the moving σ-algebra need not catch up
to `𝒜`).

The proof is a **two-sided squeeze** `h ≤ liminf (f_n / n)` and `limsup (f_n / n) ≤ h`:

* **Easy direction** (`h ≤ liminf`). Saturation gives `σ(B_n) ≤ 𝒜`, so conditioning on the coarser
  `σ(B_n)` only *increases* entropy (`condEntropy_mono_of_le`):
  `condEntropy μ 𝒜 (A_n).cells ≤ f_n`. Dividing by `n` and passing to the limit with the Fekete
  convergence `tendsto_condKsEntropySeq` (whose limit is `h`) gives `h ≤ liminf (f_n / n)`.

* **Hard direction** (`limsup ≤ h`). A **blocking / Cesàro–Toeplitz** argument. Fix `m ≥ 1` and a
  level `M ≥ 1`. Peeling `n = q·m + r` into `q` blocks of length `m` (the **shifted append
  subadditivity** `condEntropy_genJoin_pullback_append_le` iterated to the **block bound**
  `condEntropy_genJoin_block_le`), and collapsing each block via the **joint pull-back**
  `condEntropy_comap_pullback` together with the shift inclusion
  `comap_iterate_generatedSigmaAlgebra_ksJoin_le`, bounds `f_n ≤ q · g_M + (M + 2m)·L` where
  `g_M := condEntropy μ (σ(B_M)) (A_m).cells` and `L := log (card ι)`. Dividing and taking `limsup`
  kills the `(M + 2m)·L / n` term, leaving `limsup (f_n / n) ≤ g_M / m` for every `M`. The
  **fixed-partition Lévy theorem** `condEntropy_tendsto_iSup` then sends `g_M → condEntropy μ 𝒜
  (A_m).cells` (using `⨆ M, σ(B_M) = 𝒜`), giving `limsup ≤ condEntropy μ 𝒜 (A_m).cells / m` for
  every `m ≥ 1`; the `m`-Fekete convergence `tendsto_condKsEntropySeq` collapses this to
  `limsup ≤ h`.

Two corollaries follow:

* `tendsto_condCellSeq_div`: the discharged W3 hypothesis — the cell-form sequence
  `condCellSeq hT Q P n / n` also converges to `h(P, T | 𝒜)`, through the W2 bridge
  `condEntropyGivenPartition_eq_condEntropy_generated`.
* `abramovRokhlin_partition`: the **unconditional** partition-level identity
  `h(P, T) = h(Q, T) + h(P, T | 𝒜)`, obtained by feeding the vanishing Cesàro defect (read off
  from the main theorem and the `𝒜`-Fekete limit) into `abramovRokhlin_partition_of_defect`.

## Main results

* `Oseledets.Entropy.tendsto_condEntropy_genJoin_div`: the moving-σ-algebra conditional KS limit.
* `Oseledets.Entropy.tendsto_condCellSeq_div`: the cell-form Cesàro limit (W3, discharged).
* `Oseledets.Entropy.abramovRokhlin_partition`: the unconditional Abramov–Rokhlin partition
  identity.

## References

* Manfred Einsiedler, Elon Lindenstrauss, Thomas Ward, *Entropy in Ergodic Theory and Topological
  Dynamics*, Ch. 2 (the blocking / Cesàro–Toeplitz argument).
* Peter Walters, *An Introduction to Ergodic Theory*, Springer GTM **79** (1982), §4.5.
* L. M. Abramov, V. A. Rokhlin, *The entropy of a skew product of measure-preserving
  transformations*, Vestnik Leningrad Univ. **17** (1962).
-/

open MeasureTheory Function Filter Topology ProbabilityTheory MeasurableSpace

namespace Oseledets.Entropy

-- The variable ORDER `{𝒜 ℱ : MeasurableSpace α} [mα : MeasurableSpace α]` (mirroring
-- `CondKSEntropy`/`CondBlockSubadditive`) is load-bearing: `mα` is declared AFTER the conditioning
-- σ-algebras `𝒜`/`ℱ`, so it has higher instance priority and `Measure α` / `MeasurePartition μ ι` /
-- `StandardBorelSpace α` resolve to the ambient `mα`, not a conditioning sub-σ-algebra.
variable {α : Type*} {ι κ : Type*} {𝒜 ℱ : MeasurableSpace α} [mα : MeasurableSpace α]
  [StandardBorelSpace α] {μ : Measure α} [IsProbabilityMeasure μ] {T : α → α}

section Blocking

-- The blocking atoms below hold for the *arbitrary* sub-σ-algebra `ℱ` (no invariance hypothesis).

/-- **Shifted append subadditivity of the conditional iterated-join entropy** for an *arbitrary*
sub-σ-algebra `ℱ ≤ mα` (no invariance hypothesis), with an outer `T^[c]`-pullback:
`H(T⁻ᶜ(⋁ₖ₌₀ᵃ⁺ᵇ⁻¹ T⁻ᵏ α) | ℱ) ≤ H(T⁻ᶜ(⋁ₖ₌₀ᵃ⁻¹ T⁻ᵏ α) | ℱ) + H(T⁻⁽ᶜ⁺ᵃ⁾(⋁ₖ₌₀ᵇ⁻¹ T⁻ᵏ α) | ℱ)`.

This is the `c`-shifted version of `condEntropy_ksJoin_append_le` (which is the case `c = 0`): the
`T^[c]`-pullback of the `(a+b)`-fold join factors, cell by cell under `Fin.appendEquiv`, into the
join of the `T^[c]`-pullback of the `a`-fold join with the `T^[c+a]`-pullback of the `b`-fold join
(`ksJoinCells_append` followed by `T^[c]⁻¹(T^[a]⁻¹ ·) = T^[c+a]⁻¹ ·`), so the conditional join
subadditivity `condEntropy_join_le` bounds it by the sum. The shift `c` is what lets the blocking
argument keep every per-block shift a multiple of the block length `m`. -/
lemma condEntropy_genJoin_pullback_append_le [Fintype ι] (hℱ : ℱ ≤ mα)
    (hT : @MeasurePreserving α α mα mα T μ μ) (P : MeasurePartition μ ι) (c a b : ℕ) :
    condEntropy μ ℱ ((ksJoin hT P (a + b)).pullback (hT.iterate c)).cells
      ≤ condEntropy μ ℱ ((ksJoin hT P a).pullback (hT.iterate c)).cells
        + condEntropy μ ℱ ((ksJoin hT P b).pullback (hT.iterate (c + a))).cells := by
  set R : MeasurePartition μ (Fin a → ι) := (ksJoin hT P a).pullback (hT.iterate c) with hR
  set S : MeasurePartition μ (Fin b → ι) := (ksJoin hT P b).pullback (hT.iterate (c + a)) with hS
  -- Cell identity: the `T^[c]`-pullback of the `(a+b)`-join cell at `appendEquiv (x, y)` is the
  -- join cell of `R` and `S` at `(x, y)`.
  have hcell : ∀ p : (Fin a → ι) × (Fin b → ι),
      ((ksJoin hT P (a + b)).pullback (hT.iterate c)).cells (Fin.appendEquiv a b p)
        = joinCells R.cells S.cells p := by
    rintro ⟨x, y⟩
    simp only [hR, hS, MeasurePartition.pullback_cells, ksJoin_cells, joinCells_apply]
    rw [show (Fin.appendEquiv a b) (x, y) = Fin.append x y from rfl,
      ksJoinCells_append P.cells T a b x y, Set.preimage_inter]
    congr 1
    -- `T^[c]⁻¹(T^[a]⁻¹ B) = T^[c+a]⁻¹ B`.
    rw [← Set.preimage_comp, ← Function.iterate_add,
      show a + c = c + a from Nat.add_comm a c]
  -- Reindex the `(a + b)`-entropy as the conditional join entropy via the append reindexing.
  have hreindex : condEntropy μ ℱ ((ksJoin hT P (a + b)).pullback (hT.iterate c)).cells
      = condEntropy μ ℱ (joinCells R.cells S.cells) := by
    rw [condEntropy_def, condEntropy_def]
    refine integral_congr_ae (Eventually.of_forall fun ω => ?_)
    refine (Equiv.sum_comp (Fin.appendEquiv a b)
      (fun g => Real.negMulLog
        (@condExpKernel α mα _ μ _ ℱ ω
          (((ksJoin hT P (a + b)).pullback (hT.iterate c)).cells g)).toReal)).symm.trans ?_
    exact Finset.sum_congr rfl fun p _ => by rw [hcell p]
  rw [hreindex]
  exact condEntropy_join_le hℱ R S

/-- **Block bound for the conditional iterated-join entropy** against an arbitrary sub-σ-algebra
`ℱ ≤ mα`. Peeling `q·m + r` into `q` blocks of length `m` followed by a remainder block of length
`r` (each peeled with the shifted append subadditivity `condEntropy_genJoin_pullback_append_le` so
that every per-block shift is a multiple of the block length `m`):
`H(A_{qm+r} | ℱ) ≤ ∑_{j<q} H(T⁻ʲᵐ A_m | ℱ) + H(T⁻ᵠᵐ A_r | ℱ)`, writing `A_k = ⋁ₗ₌₀^{k-1} T⁻ˡ α`.

Proved by induction on `q`. The base case `q = 0` is the identity `T^[0]⁻¹ = id`. The inductive step
front-peels the first block of length `m` off `A_{(q+1)m+r} = A_{m + (qm+r)}`
(`condEntropy_genJoin_pullback_append_le` with `a = m`, `b = qm + r`), then applies the inductive
hypothesis to the `T^[m]`-pullback of the remaining `A_{qm+r}` — using the shift parameter `c` of
the helper to absorb the outer `T^[m]` and shift every inner per-block shift by `m`. -/
lemma condEntropy_genJoin_block_le [Fintype ι] (hℱ : ℱ ≤ mα)
    (hT : @MeasurePreserving α α mα mα T μ μ) (P : MeasurePartition μ ι) (m r : ℕ) :
    ∀ q : ℕ, condEntropy μ ℱ
        ((ksJoin hT P (q * m + r)).pullback (hT.iterate 0)).cells
      ≤ (∑ j ∈ Finset.range q,
          condEntropy μ ℱ ((ksJoin hT P m).pullback (hT.iterate (j * m))).cells)
        + condEntropy μ ℱ ((ksJoin hT P r).pullback (hT.iterate (q * m))).cells := by
  -- A general statement with an outer shift `c`, proved by induction on `q`; the lemma is `c = 0`.
  suffices hgen : ∀ q c : ℕ, condEntropy μ ℱ
        ((ksJoin hT P (q * m + r)).pullback (hT.iterate c)).cells
      ≤ (∑ j ∈ Finset.range q,
          condEntropy μ ℱ ((ksJoin hT P m).pullback (hT.iterate (c + j * m))).cells)
        + condEntropy μ ℱ ((ksJoin hT P r).pullback (hT.iterate (c + q * m))).cells by
    intro q
    simpa using hgen q 0
  intro q
  induction q with
  | zero =>
    intro c
    -- `0·m + r = r`, the sum is empty, and `c + 0·m = c`: both sides are `H(T⁻ᶜ A_r | ℱ)`.
    have hi : 0 * m + r = r := by ring
    have hs : c + 0 * m = c := by ring
    rw [hi, hs, Finset.range_zero, Finset.sum_empty]
    exact le_of_eq (zero_add _).symm
  | succ k IH =>
    intro c
    -- `(k+1)m + r = m + (km + r)`.
    have hsplit : (k + 1) * m + r = m + (k * m + r) := by ring
    rw [hsplit]
    -- Front-peel the first block of length `m`, then apply the IH at outer shift `c + m`.
    refine (condEntropy_genJoin_pullback_append_le hℱ hT P c m (k * m + r)).trans ?_
    calc condEntropy μ ℱ ((ksJoin hT P m).pullback (hT.iterate c)).cells
          + condEntropy μ ℱ ((ksJoin hT P (k * m + r)).pullback (hT.iterate (c + m))).cells
        ≤ condEntropy μ ℱ ((ksJoin hT P m).pullback (hT.iterate c)).cells
          + ((∑ j ∈ Finset.range k,
              condEntropy μ ℱ ((ksJoin hT P m).pullback (hT.iterate (c + m + j * m))).cells)
            + condEntropy μ ℱ ((ksJoin hT P r).pullback (hT.iterate (c + m + k * m))).cells) := by
          gcongr
          exact IH (c + m)
      _ = (∑ j ∈ Finset.range (k + 1),
              condEntropy μ ℱ ((ksJoin hT P m).pullback (hT.iterate (c + j * m))).cells)
            + condEntropy μ ℱ ((ksJoin hT P r).pullback (hT.iterate (c + (k + 1) * m))).cells := by
          -- `sum_range_succ'` peels the `j = 0` block (shift `c`); the remaining shifts align.
          rw [Finset.sum_range_succ']
          have hshift : ∀ j ∈ Finset.range k,
              condEntropy μ ℱ ((ksJoin hT P m).pullback (hT.iterate (c + m + j * m))).cells
                = condEntropy μ ℱ ((ksJoin hT P m).pullback (hT.iterate (c + (j + 1) * m))).cells :=
            fun j _ => by rw [show c + m + j * m = c + (j + 1) * m from by ring]
          rw [Finset.sum_congr rfl hshift]
          have hc0 : c + 0 * m = c := by ring
          have hck : c + m + k * m = c + (k + 1) * m := by ring
          rw [hc0, hck]
          ring

variable [Fintype κ]

/-- **Per-block collapse.** For the moving conditioning σ-algebra `σ(B_n) = generatedSigmaAlgebra μ
(ksJoin hT Q n)` and a shift `s ≤ n`, the conditional entropy of the `T^[s]`-pullback of the
`m`-fold `P`-join drops to the conditional entropy of the unshifted `m`-fold join against the
*earlier* σ-algebra `σ(B_{n-s})`:
`H(T⁻ˢ A_m | σ(B_n)) ≤ H(A_m | σ(B_{n-s}))`.

Two steps. First, conditioning monotonicity `condEntropy_mono_of_le` against the *coarser*
`comap (T^[s]) σ(B_{n-s})` (which sits below `σ(B_n)` by the shift inclusion
`comap_iterate_generatedSigmaAlgebra_ksJoin_le`, after `s + (n - s) = n`) only *increases* the
entropy:
`H(T⁻ˢ A_m | σ(B_n)) ≤ H(T⁻ˢ A_m | comap (T^[s]) σ(B_{n-s}))`.
Second, the joint pull-back `condEntropy_comap_pullback` evaluates the right side back to
`H(A_m | σ(B_{n-s}))`. -/
lemma condEntropy_genJoin_block_collapse [Fintype ι]
    (hT : @MeasurePreserving α α mα mα T μ μ) (Q : MeasurePartition μ κ) (P : MeasurePartition μ ι)
    (m s n : ℕ) (hsn : s ≤ n) :
    condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
        ((ksJoin hT P m).pullback (hT.iterate s)).cells
      ≤ condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q (n - s))) (ksJoin hT P m).cells := by
  have hmα : ∀ k, generatedSigmaAlgebra μ (ksJoin hT Q k) ≤ mα := fun k =>
    generatedSigmaAlgebra_le (ksJoin hT Q k)
  -- `comap (T^[s]) σ(B_{n-s}) ≤ σ(B_{s + (n-s)}) = σ(B_n)`.
  have hcomap : MeasurableSpace.comap (T^[s]) (generatedSigmaAlgebra μ (ksJoin hT Q (n - s)))
      ≤ generatedSigmaAlgebra μ (ksJoin hT Q n) := by
    have h := comap_iterate_generatedSigmaAlgebra_ksJoin_le hT Q s (n - s)
    rwa [show s + (n - s) = n from by omega] at h
  calc condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
          ((ksJoin hT P m).pullback (hT.iterate s)).cells
      ≤ condEntropy μ
          (MeasurableSpace.comap (T^[s]) (generatedSigmaAlgebra μ (ksJoin hT Q (n - s))))
          ((ksJoin hT P m).pullback (hT.iterate s)).cells :=
        condEntropy_mono_of_le hcomap (hmα n)
          ((ksJoin hT P m).pullback (hT.iterate s))
    _ = condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q (n - s))) (ksJoin hT P m).cells := by
        rw [MeasurePartition.pullback_cells]
        exact condEntropy_comap_pullback (hmα (n - s)) hT s (ksJoin hT P m)

/-- **The blocking core inequality.** Fix a block length `m ≥ 1` and a level `M`. For *every* `n`,
the conditional join entropy `f_n = H(A_n | σ(B_n))` against the moving σ-algebra is bounded by `q`
copies of the fixed-level term `g_M := H(A_m | σ(B_M))` plus an `n`-independent ceiling, where
`q = n / m`:
`H(A_n | σ(B_n)) ≤ (n / m) · H(A_m | σ(B_M)) + (M·m + m) · log (card ι)`.

This packages the whole blocking argument: the block bound `condEntropy_genJoin_block_le` peels `n =
q·m + r` into `q` shifted `m`-blocks and a remainder; each `m`-block collapses
(`condEntropy_genJoin_block_collapse`) to `H(A_m | σ(B_{n-jm}))`, which is `≤ g_M` for the *good*
blocks (`σ(B_M) ≤ σ(B_{n-jm})` when `M ≤ n - jm`) and `≤ m · log (card ι)` (the uniform bound
`condEntropy_ksJoin_le_nsmul_log_card`) for the *bad* blocks; the bad blocks number at most `M`
(they sit in `Ico (q - M) q`), and the remainder is `≤ m · log (card ι)`. -/
lemma condEntropy_genJoin_blocking_core [Fintype ι] [Nonempty ι]
    (hT : @MeasurePreserving α α mα mα T μ μ) (Q : MeasurePartition μ κ) (P : MeasurePartition μ ι)
    (m M n : ℕ) (hm : 1 ≤ m) :
    condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n)) (ksJoin hT P n).cells
      ≤ (n / m : ℕ) * condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q M)) (ksJoin hT P m).cells
        + ((M * m + m : ℕ) : ℝ) * Real.log (Fintype.card ι) := by
  set L := Real.log (Fintype.card ι) with hL
  set g := condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q M)) (ksJoin hT P m).cells
  set q := n / m with hq
  set r := n % m with hr
  have hL0 : 0 ≤ L := by
    rw [hL]; exact Real.log_nonneg (by exact_mod_cast Fintype.card_pos)
  have hg0 : 0 ≤ g := condEntropy_nonneg
  have hmα : ∀ k, generatedSigmaAlgebra μ (ksJoin hT Q k) ≤ mα := fun k =>
    generatedSigmaAlgebra_le (ksJoin hT Q k)
  have hnqr : n = q * m + r := by
    rw [hq, hr, Nat.mul_comm (n / m) m]; exact (Nat.div_add_mod n m).symm
  have hrm : r < m := by rw [hr]; exact Nat.mod_lt _ hm
  -- (a) Block bound, after `(A_n).pullback (T^[0]) = A_n`.
  have hblock := condEntropy_genJoin_block_le (hmα n) hT P m r q
  have hp0 : ((ksJoin hT P (q * m + r)).pullback (hT.iterate 0)).cells
      = (ksJoin hT P (q * m + r)).cells := by
    simp only [MeasurePartition.pullback_cells, Function.iterate_zero, Set.preimage_id]
  rw [hp0, ← hnqr] at hblock
  -- (b) Remainder ≤ m·L: collapse the `T^[q·m]`-pullback of `A_r` to `σ(B_r)`, then the uniform
  -- bound. `n - q·m = r`.
  have hrem : condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
      ((ksJoin hT P r).pullback (hT.iterate (q * m))).cells ≤ m * L := by
    refine (condEntropy_genJoin_block_collapse hT Q P r (q * m) n (by omega)).trans ?_
    rw [show n - q * m = r from by omega]
    refine (condEntropy_ksJoin_le_nsmul_log_card (hmα r) hT P r).trans ?_
    have : (r : ℝ) ≤ (m : ℝ) := by exact_mod_cast hrm.le
    exact mul_le_mul_of_nonneg_right this hL0
  -- (c) Per-block bound: each `j`-block is `≤ g + (if bad then m·L else 0)`.
  have hbad : ∀ j ∈ Finset.range q,
      condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
          ((ksJoin hT P m).pullback (hT.iterate (j * m))).cells
        ≤ g + (if n - j * m < M then m * L else 0) := by
    intro j hj
    rw [Finset.mem_range] at hj
    have hjn : j * m ≤ n := by
      have : j * m ≤ q * m := Nat.mul_le_mul_right m (le_of_lt hj)
      omega
    -- Collapse the block.
    refine (condEntropy_genJoin_block_collapse hT Q P m (j * m) n hjn).trans ?_
    by_cases hbadj : n - j * m < M
    · -- Bad: use the uniform bound `≤ m·L`, absorbed into `g + m·L`.
      simp only [hbadj, if_true]
      have huni : condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q (n - j * m)))
          (ksJoin hT P m).cells ≤ m * L :=
        condEntropy_ksJoin_le_nsmul_log_card (hmα (n - j * m)) hT P m
      linarith [huni, hg0]
    · -- Good: `σ(B_M) ≤ σ(B_{n-jm})`, so the block entropy drops to `g`.
      simp only [hbadj, if_false, add_zero]
      have hMle : M ≤ n - j * m := by omega
      exact condEntropy_mono_of_le (generatedSigmaAlgebra_ksJoin_mono hT Q hMle) (hmα (n - j * m))
        (ksJoin hT P m)
  -- (d) Sum the per-block bounds.
  have hsum : (∑ j ∈ Finset.range q,
        condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
          ((ksJoin hT P m).pullback (hT.iterate (j * m))).cells)
      ≤ q * g + M * (m * L) := by
    calc (∑ j ∈ Finset.range q,
            condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
              ((ksJoin hT P m).pullback (hT.iterate (j * m))).cells)
        ≤ ∑ j ∈ Finset.range q, (g + (if n - j * m < M then m * L else 0)) :=
          Finset.sum_le_sum hbad
      _ = q * g + (∑ j ∈ Finset.range q, (if n - j * m < M then m * L else 0)) := by
          rw [Finset.sum_add_distrib, Finset.sum_const, Finset.card_range, nsmul_eq_mul]
      _ ≤ q * g + M * (m * L) := by
          gcongr
          -- The bad indicators sum to at most `M`: bad indices sit in `Ico (q - M) q`.
          have hbadset : (Finset.range q).filter (fun j => n - j * m < M)
              ⊆ Finset.Ico (q - M) q := by
            intro j hj
            rw [Finset.mem_filter, Finset.mem_range] at hj
            rw [Finset.mem_Ico]
            obtain ⟨hjq, hbadj⟩ := hj
            refine ⟨?_, hjq⟩
            -- `n - j·m < M` with `n = q·m + r`, `m ≥ 1` forces `q - M ≤ j`.
            have hjm : j * m ≤ q * m := Nat.mul_le_mul_right m (le_of_lt hjq)
            have h1 : q - j ≤ (q - j) * m := Nat.le_mul_of_pos_right _ (by omega)
            have h2 : (q - j) * m = q * m - j * m := by rw [Nat.sub_mul]
            -- `q - j ≤ q·m - j·m ≤ n - j·m < M`.
            omega
          have hcard : ((Finset.range q).filter (fun j => n - j * m < M)).card ≤ M := by
            calc ((Finset.range q).filter (fun j => n - j * m < M)).card
                ≤ (Finset.Ico (q - M) q).card := Finset.card_le_card hbadset
              _ = q - (q - M) := by rw [Nat.card_Ico]
              _ ≤ M := by omega
          have hmL0 : 0 ≤ (m : ℝ) * L := mul_nonneg (Nat.cast_nonneg m) hL0
          calc (∑ j ∈ Finset.range q, (if n - j * m < M then m * L else 0))
              = ∑ j ∈ (Finset.range q).filter (fun j => n - j * m < M), m * L := by
                rw [← Finset.sum_filter]
            _ = ((Finset.range q).filter (fun j => n - j * m < M)).card * (m * L) := by
                rw [Finset.sum_const, nsmul_eq_mul]
            _ ≤ M * (m * L) :=
                mul_le_mul_of_nonneg_right (by exact_mod_cast hcard) hmL0
  -- Assemble: `f_n ≤ (∑ blocks) + remainder ≤ (q·g + M·m·L) + m·L`.
  calc condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n)) (ksJoin hT P n).cells
      ≤ (∑ j ∈ Finset.range q,
            condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
              ((ksJoin hT P m).pullback (hT.iterate (j * m))).cells)
          + condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
              ((ksJoin hT P r).pullback (hT.iterate (q * m))).cells := hblock
    _ ≤ (q * g + M * (m * L)) + m * L := add_le_add hsum hrem
    _ = (q : ℕ) * g + ((M * m + m : ℕ) : ℝ) * L := by push_cast; ring

end Blocking

section Limit

variable [Fintype ι] [Fintype κ] [Nonempty ι]

set_option maxHeartbeats 800000 in
-- The blocking + Lévy squeeze elaborates a long two-sided `liminf`/`limsup` argument in a single
-- `by` block; the default heartbeat budget is insufficient for the combined term.
/-- **The moving-σ-algebra conditional Kolmogorov–Sinai limit** (issue #13 capstone). Writing
`A_n := ksJoin hT P n`, `σ(B_n) := generatedSigmaAlgebra μ (ksJoin hT Q n)` for the increasing
filtration generated by the `Q`-joins, and `f_n := condEntropy μ (σ(B_n)) (A_n).cells`, the Cesàro
average `f_n / n` of the conditional join entropy against the **moving** conditioning σ-algebra
converges to the relative Kolmogorov–Sinai entropy `h(P, T | 𝒜) = condKsEntropyPartition hm hT hinv
P`, **provided** the filtration saturates `𝒜`, i.e. `⨆ n, σ(B_n) = 𝒜` (the hypothesis `hsat`).

This is a two-sided squeeze. The **easy** direction `h ≤ liminf (f_n / n)`: saturation gives
`σ(B_n) ≤ 𝒜`, so conditioning on the coarser `σ(B_n)` only increases entropy
(`condEntropy_mono_of_le`), `condEntropy μ 𝒜 (A_n) ≤ f_n`; dividing and using the `𝒜`-Fekete limit
(`tendsto_condKsEntropySeq`) gives the bound on the liminf. The **hard** direction
`limsup (f_n / n) ≤ h` is a blocking / Cesàro–Toeplitz argument: the core inequality
`condEntropy_genJoin_blocking_core` gives `f_n ≤ (n/m)·g_M + (M·m+m)·L` for `g_M := condEntropy μ
(σ(B_M)) (A_m)`; dividing kills the `n`-independent ceiling in the `limsup`, leaving
`limsup ≤ g_M / m`; the fixed-partition Lévy theorem `condEntropy_tendsto_iSup` (with `⨆ M, σ(B_M) =
𝒜`) sends `g_M → condEntropy μ 𝒜 (A_m)`, giving `limsup ≤ condEntropy μ 𝒜 (A_m) / m` for every
`m ≥ 1`, which the `m`-Fekete limit collapses to `limsup ≤ h`. The saturation hypothesis `hsat` is
essential — the statement is false without it.

See Einsiedler–Lindenstrauss–Ward, *Entropy in Ergodic Theory and Topological Dynamics*, Ch. 2, and
Walters, GTM **79**, §4.5. -/
theorem tendsto_condEntropy_genJoin_div (hm : 𝒜 ≤ mα) (hT : MeasurePreserving T μ μ)
    (hinv : MeasurableSpace.comap T 𝒜 ≤ 𝒜) (Q : MeasurePartition μ κ) (P : MeasurePartition μ ι)
    (hsat : ⨆ n, generatedSigmaAlgebra μ (ksJoin hT Q n) = 𝒜) :
    Tendsto (fun n => condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
        (ksJoin hT P n).cells / (n : ℝ))
      atTop (𝓝 (condKsEntropyPartition hm hT hinv P)) := by
  classical
  set L := Real.log (Fintype.card ι) with hL
  have hL0 : 0 ≤ L := Real.log_nonneg (by exact_mod_cast Fintype.card_pos)
  -- The moving-σ-algebra conditional join entropy sequence and its normalisation.
  set f : ℕ → ℝ := fun n => condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
    (ksJoin hT P n).cells
  have hfn : ∀ k, f k = condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q k))
    (ksJoin hT P k).cells := fun k => rfl
  set u : ℕ → ℝ := fun n => f n / (n : ℝ) with hu
  set h := condKsEntropyPartition hm hT hinv P
  -- σ-algebra bookkeeping.
  have hBleA : ∀ n, generatedSigmaAlgebra μ (ksJoin hT Q n) ≤ 𝒜 := fun n => by
    rw [← hsat]
    exact le_iSup (fun k => generatedSigmaAlgebra μ (ksJoin hT Q k)) n
  have hBlemα : ∀ n, generatedSigmaAlgebra μ (ksJoin hT Q n) ≤ mα := fun n =>
    generatedSigmaAlgebra_le (ksJoin hT Q n)
  -- Boundedness `0 ≤ u n ≤ L`.
  have hu_nonneg : ∀ n, 0 ≤ u n := by
    intro n
    change (0 : ℝ) ≤ condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
      (ksJoin hT P n).cells / (n : ℝ)
    exact div_nonneg condEntropy_nonneg (Nat.cast_nonneg n)
  have hu_le : ∀ n, u n ≤ L := by
    intro n
    change condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n)) (ksJoin hT P n).cells / (n : ℝ)
      ≤ L
    rcases Nat.eq_zero_or_pos n with rfl | hn
    · simp only [Nat.cast_zero, div_zero]; exact hL0
    · rw [div_le_iff₀ (by exact_mod_cast hn)]
      have := condEntropy_ksJoin_le_nsmul_log_card (hBlemα n) hT P n
      rw [← hL] at this
      rw [mul_comm]; exact this
  -- The two boundedness witnesses for the liminf/limsup packaging.
  have hbdd_le : IsBoundedUnder (· ≤ ·) atTop u := isBoundedUnder_of_eventually_le
    (Eventually.of_forall hu_le)
  have hbdd_ge : IsBoundedUnder (· ≥ ·) atTop u := isBoundedUnder_of_eventually_ge
    (Eventually.of_forall hu_nonneg)
  -- ===== EASY DIRECTION: `h ≤ liminf u`. =====
  have hlim_inf : h ≤ liminf u atTop := by
    -- `condKsEntropySeq 𝒜 / n ≤ u n` for all `n`: conditioning on the *coarser* `σ(B_n)` is larger.
    have hcmp : ∀ n, condKsEntropySeq 𝒜 hT P n / (n : ℝ) ≤ u n := by
      intro n
      have hmono : condEntropy μ 𝒜 (ksJoin hT P n).cells ≤ f n :=
        condEntropy_mono_of_le (hBleA n) hm (ksJoin hT P n)
      simp only [hu, condKsEntropySeq]
      gcongr
    -- The `𝒜`-Fekete sequence converges to `h`; pass through `liminf`.
    have hAseq : Tendsto (fun n => condKsEntropySeq 𝒜 hT P n / (n : ℝ)) atTop (𝓝 h) :=
      tendsto_condKsEntropySeq hm hT hinv P
    calc h = liminf (fun n => condKsEntropySeq 𝒜 hT P n / (n : ℝ)) atTop := hAseq.liminf_eq.symm
      _ ≤ liminf u atTop :=
        liminf_le_liminf (Eventually.of_forall hcmp) (hAseq.isBoundedUnder_ge)
          hbdd_le.isCoboundedUnder_ge
  -- ===== HARD DIRECTION: `limsup u ≤ h`. =====
  have hlim_sup : limsup u atTop ≤ h := by
    -- Step 1: for every `m ≥ 1`, `limsup u ≤ condEntropy μ 𝒜 (A_m) / m`.
    have hstep1 : ∀ m : ℕ, 1 ≤ m →
        limsup u atTop ≤ condEntropy μ 𝒜 (ksJoin hT P m).cells / (m : ℝ) := by
      intro m hm1
      have hmR : (0 : ℝ) < m := by exact_mod_cast hm1
      -- Step 1a: for every `M`, `limsup u ≤ g_M / m`, where `g_M = condEntropy μ σ(B_M) (A_m)`.
      have hstep1a : ∀ M : ℕ,
          limsup u atTop
            ≤ condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q M)) (ksJoin hT P m).cells
              / (m : ℝ) := by
        intro M
        set g := condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q M)) (ksJoin hT P m).cells
          with hgeq
        have hg0 : 0 ≤ g := by rw [hgeq]; exact condEntropy_nonneg
        -- The dominating sequence `b n = g/m + (M·m+m)·L / n`, with `b n → g/m`.
        set b : ℕ → ℝ := fun n => g / (m : ℝ) + ((M * m + m : ℕ) : ℝ) * L / (n : ℝ) with hb
        have hb_tendsto : Tendsto b atTop (𝓝 (g / (m : ℝ))) := by
          have hz : Tendsto (fun n : ℕ => ((M * m + m : ℕ) : ℝ) * L / (n : ℝ)) atTop (𝓝 0) :=
            tendsto_const_div_atTop_nhds_zero_nat (((M * m + m : ℕ) : ℝ) * L)
          have hc : Tendsto (fun _ : ℕ => g / (m : ℝ)) atTop (𝓝 (g / (m : ℝ))) :=
            tendsto_const_nhds
          have hsum := hc.add hz
          rw [add_zero] at hsum
          simpa only [hb] using hsum
        -- `u n ≤ b n` eventually (`n ≥ 1`): the blocking core inequality divided by `n`.
        have huleb : ∀ᶠ n in atTop, u n ≤ b n := by
          filter_upwards [eventually_ge_atTop 1] with n hn
          have hnR : (0 : ℝ) < n := by exact_mod_cast hn
          have hcore := condEntropy_genJoin_blocking_core hT Q P m M n hm1
          rw [← hL, ← hgeq, ← hfn n] at hcore
          -- `↑(n/m) ≤ ↑n / ↑m`, so the leading term `↑(n/m)·g ≤ ↑n·(g/↑m)`.
          have hdiv : ((n / m : ℕ) : ℝ) ≤ (n : ℝ) / (m : ℝ) := by
            rw [le_div_iff₀ hmR]; exact_mod_cast Nat.div_mul_le_self n m
          have ht1 : ((n / m : ℕ) : ℝ) * g ≤ (n : ℝ) * (g / (m : ℝ)) := by
            calc ((n / m : ℕ) : ℝ) * g ≤ ((n : ℝ) / (m : ℝ)) * g :=
                  mul_le_mul_of_nonneg_right hdiv hg0
              _ = (n : ℝ) * (g / (m : ℝ)) := by ring
          -- Bound `f n` by `↑n · b n`, then divide.
          have hbn : b n * (n : ℝ)
              = (n : ℝ) * (g / (m : ℝ)) + ((M * m + m : ℕ) : ℝ) * L := by
            rw [hb, add_mul, div_mul_cancel₀ _ (ne_of_gt hnR)]
            ring
          have hub : f n ≤ b n * (n : ℝ) := by
            rw [hbn]
            linarith [hcore, ht1]
          simp only [hu]
          rw [div_le_iff₀ hnR]
          exact hub
        -- `limsup u ≤ limsup b = g/m`.
        calc limsup u atTop
            ≤ limsup b atTop :=
              limsup_le_limsup huleb hbdd_ge.isCoboundedUnder_le hb_tendsto.isBoundedUnder_le
          _ = g / (m : ℝ) := hb_tendsto.limsup_eq
      -- Step 1b: Lévy sends `g_M → condEntropy μ 𝒜 (A_m)`; pass `M → ∞`.
      have hLevy : Tendsto
          (fun M => condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q M)) (ksJoin hT P m).cells)
          atTop (𝓝 (condEntropy μ 𝒜 (ksJoin hT P m).cells)) := by
        have h2 := condEntropy_tendsto_iSup
          (fun M => generatedSigmaAlgebra μ (ksJoin hT Q M))
          (fun a b hab => generatedSigmaAlgebra_ksJoin_mono hT Q hab) hBlemα (ksJoin hT P m)
        rwa [hsat] at h2
      -- `g_M / m → condEntropy μ 𝒜 (A_m) / m`, and `limsup u ≤ g_M/m` for all `M`.
      have hLevy_div : Tendsto
          (fun M => condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q M)) (ksJoin hT P m).cells
            / (m : ℝ)) atTop (𝓝 (condEntropy μ 𝒜 (ksJoin hT P m).cells / (m : ℝ))) :=
        hLevy.div_const _
      exact ge_of_tendsto hLevy_div (Eventually.of_forall hstep1a)
    -- Step 2: `condEntropy μ 𝒜 (A_m)/m = condKsEntropySeq 𝒜 / m → h`; pass `m → ∞`.
    have hAseq : Tendsto (fun m => condEntropy μ 𝒜 (ksJoin hT P m).cells / (m : ℝ)) atTop
        (𝓝 h) := by
      have := tendsto_condKsEntropySeq hm hT hinv P
      simpa only [condKsEntropySeq] using this
    refine ge_of_tendsto hAseq ?_
    filter_upwards [eventually_ge_atTop 1] with m hm1
    exact hstep1 m hm1
  -- ===== Squeeze. =====
  exact tendsto_of_le_liminf_of_limsup_le hlim_inf hlim_sup hbdd_le hbdd_ge

/-- **The cell-form Cesàro limit (W3, discharged under saturation).** The conditional *cell-form*
sequence `condCellSeq hT Q P n / n` converges to the relative Kolmogorov–Sinai entropy
`h(P, T | 𝒜)`, provided the join filtration saturates `𝒜` (`hsat`). This discharges the named
hypothesis `hW3` of `abramovRokhlin_partition_of_W3`: through the W2 bridge
`condEntropyGivenPartition_eq_condEntropy_generated`, the cell-form sequence equals the σ-algebra
conditional join entropy against the moving generated σ-algebra `σ(B_n)`, so the main theorem
`tendsto_condEntropy_genJoin_div` applies verbatim. -/
theorem tendsto_condCellSeq_div (hm : 𝒜 ≤ mα) (hT : MeasurePreserving T μ μ)
    (hinv : MeasurableSpace.comap T 𝒜 ≤ 𝒜) (Q : MeasurePartition μ κ) (P : MeasurePartition μ ι)
    (hsat : ⨆ n, generatedSigmaAlgebra μ (ksJoin hT Q n) = 𝒜) :
    Tendsto (fun n => condCellSeq hT Q P n / (n : ℝ)) atTop
      (𝓝 (condKsEntropyPartition hm hT hinv P)) := by
  -- The W2 bridge identifies the cell-form sequence with the moving-σ-algebra conditional join
  -- entropy, for every `n`.
  have hbridge : (fun n => condCellSeq hT Q P n / (n : ℝ))
      = fun n => condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
          (ksJoin hT P n).cells / (n : ℝ) := by
    funext n
    rw [condCellSeq, condEntropyGivenPartition_eq_condEntropy_generated (ksJoin hT Q n)
      (ksJoin hT P n).cells (ksJoin hT P n).measurable]
  rw [hbridge]
  exact tendsto_condEntropy_genJoin_div hm hT hinv Q P hsat

/-- **The unconditional Abramov–Rokhlin partition identity** (issue #13). Given the per-`n`
refinement of the `P`-join `A_n` over the `Q`-join `B_n` (each `P`-join cell is `μ`-a.e. inside a
single `Q`-join cell, witnessed by `g`) and the saturation hypothesis `hsat : ⨆ n, σ(B_n) = 𝒜`, the
Kolmogorov–Sinai entropy of `P` splits as the entropy of the factor `Q` plus the relative entropy of
`P` over `𝒜`:
`h(P, T) = h(Q, T) + h(P, T | 𝒜)`.

The Cesàro **entropy defect** `(H(A_n | σ(B_n)) − H(A_n | 𝒜)) / n` vanishes: both
`H(A_n | σ(B_n)) / n` (the main theorem `tendsto_condEntropy_genJoin_div`) and `H(A_n | 𝒜) / n =
condKsEntropySeq 𝒜 / n` (Fekete, `tendsto_condKsEntropySeq`) converge to `h(P, T | 𝒜)`, so their
difference tends to `0`. Feeding this defect into `abramovRokhlin_partition_of_defect` assembles the
identity. -/
theorem abramovRokhlin_partition (hm : 𝒜 ≤ mα) (hT : MeasurePreserving T μ μ)
    (hinv : MeasurableSpace.comap T 𝒜 ≤ 𝒜) (Q : MeasurePartition μ κ) (P : MeasurePartition μ ι)
    (g : ∀ n, (Fin n → ι) → (Fin n → κ))
    (hrefine : ∀ n f, (ksJoin hT P n).cells f ≤ᵐ[μ] (ksJoin hT Q n).cells (g n f))
    (hsat : ⨆ n, generatedSigmaAlgebra μ (ksJoin hT Q n) = 𝒜) :
    ksEntropyPartition hT P
      = ksEntropyPartition hT Q + condKsEntropyPartition hm hT hinv P := by
  -- The Cesàro entropy defect vanishes: difference of two sequences with the same limit `h`.
  have hdefect : Tendsto (fun n => (condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT Q n))
      (ksJoin hT P n).cells - condKsEntropySeq 𝒜 hT P n) / (n : ℝ)) atTop (𝓝 0) := by
    have hmoving := tendsto_condEntropy_genJoin_div hm hT hinv Q P hsat
    have hfixed := tendsto_condKsEntropySeq hm hT hinv P
    have hsub := hmoving.sub hfixed
    rw [sub_self] at hsub
    refine hsub.congr fun n => ?_
    rw [sub_div]
  exact abramovRokhlin_partition_of_defect hm hT hinv Q P g hrefine hdefect

end Limit

end Oseledets.Entropy
