/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Entropy.CondKSMovingLimit
import Oseledets.Entropy.Generator
import Oseledets.Entropy.KSEntropyMono
import Mathlib.Probability.Kernel.Condexp

/-!
# The Kolmogorov–Sinai generator theorem `h(T) = h(T, P)`

This file proves the **Kolmogorov–Sinai generator theorem**: for a measure-preserving
transformation `T` of a standard Borel probability space and a *one-sided generating* finite
partition `P` (`IsGenerating μ T P`, i.e. the forward-`T`-saturated σ-algebra generated by `P` is
the ambient σ-algebra `mα`), the entropy of the system is already attained on `P`:
`h(T) = h(T, P)`.

The classical statement is `Oseledets.Entropy.Generator` left as a hypothesis-form interface; here
it is *proved* by assembling the issue-#13 unconditional Abramov–Rokhlin machinery.

## Proof outline (Route A)

`le_antisymm` of two inequalities:

* `h(T, P) ≤ h(T)` is free (`le_ksEntropy`).
* `h(T) ≤ h(T, P)`. Since `ksEntropy hT = ⨆ over finite partitions`, by `iSup_le` it reduces to the
  **crux** `∀ m (Q : MeasurePartition μ (Fin m)), h(T, Q) ≤ h(T, P)`. For the crux, apply the
  unconditional Abramov–Rokhlin partition identity `abramovRokhlin_partition` to the refined
  partition `R := joinPartition Q P` over the factor `P`, conditioning on the **full** σ-algebra
  `mα`. Three ingredients:
  1. `condEntropy_full_eq_zero`: the conditional Shannon entropy against `mα` of any measurable
     partition vanishes (a measurable function is its own conditional expectation w.r.t. the full
     σ-algebra, so each kernel cell mass is `0` or `1` a.e. and `negMulLog` of `{0, 1}` is `0`).
  2. The saturation witness from `hgen : IsGenerating μ T P` (via
     `iSup_generatedSigmaAlgebra_ksJoin_eq`): `⨆ n σ(P-join) = mα`. This is **load-bearing** — the
     moving-index limit underlying `abramovRokhlin_partition` is false without saturation.
  3. The structural refinement witness: each cell of the `(Q ∨ P)`-join lies (exactly, hence a.e.)
     inside a single `P`-join cell, via the second-coordinate projection.

  Combining (1)–(3): `h(R, T) = h(P, T) + h(R, T | mα) = h(P, T) + 0`, while
  `ksEntropyPartition_le_join` gives `h(Q, T) ≤ h(R, T) = h(Q ∨ P, T)`. Hence `h(Q, T) ≤ h(P, T)`.

## Main results

* `Oseledets.Entropy.condEntropy_full_eq_zero`: `H(R | mα) = 0` for the full σ-algebra (N6.1).
* `Oseledets.Entropy.ksEntropyPartition_le_of_generating`: the crux — `h(T, Q) ≤ h(T, P)` for a
  generating `P` and any finite partition `Q`.
* `Oseledets.Entropy.ksEntropy_eq_ksEntropyPartition_of_generating`: the headline generator theorem
  `h(T) = h(T, P)`.

## References

* François Le Maître, *Notes on the Kolmogorov–Sinai theorem* (2017), §2.
* Peter Walters, *An Introduction to Ergodic Theory*, GTM **79**, Springer (1982), Ch. 4.
-/

open MeasureTheory Function Filter Topology ProbabilityTheory MeasurableSpace

namespace Oseledets.Entropy

variable {α : Type*} {ι : Type*} [mα : MeasurableSpace α] [StandardBorelSpace α] [Fintype ι]

/-- **N6.1 — the conditional Shannon entropy against the full σ-algebra vanishes.**
`condEntropy μ mα R.cells = 0` for any finite measurable partition `R`.

A measurable function is its own conditional expectation with respect to the full σ-algebra `mα`
(`condExp_of_stronglyMeasurable` with `hm = le_rfl`). Hence for each cell the regular-conditional
kernel mass `(condExpKernel μ mα ω).real (R.cells i)` equals the indicator `𝟙_{R.cells i} ω`
`μ`-a.e. (`condExpKernel_ae_eq_condExp`), which is `0` or `1`; the Shannon term `negMulLog` is then
`negMulLog 0 = 0` or `negMulLog 1 = 0`. The whole integrand vanishes `μ`-a.e., so the integral is
`0`. -/
lemma condEntropy_full_eq_zero {μ : Measure α} [IsProbabilityMeasure μ]
    (R : MeasurePartition μ ι) :
    condEntropy μ mα R.cells = 0 := by
  have hσ : SigmaFinite (μ.trim (le_refl mα)) := by rw [trim_eq_self]; infer_instance
  rw [condEntropy_def]
  -- The integrand is `μ`-a.e. zero.
  refine integral_eq_zero_of_ae ?_
  -- For each cell `i`, the kernel mass equals the indicator `μ`-a.e.
  have hcell : ∀ i : ι, (fun ω => (@condExpKernel α mα _ μ _ mα ω (R.cells i)).toReal)
      =ᵐ[μ] (R.cells i).indicator (fun _ => (1 : ℝ)) := by
    intro i
    -- `(condExpKernel μ mα ω).real (R.cells i) =ᵐ μ⟦R.cells i | mα⟧`.
    have h1 : (fun ω => (@condExpKernel α mα _ μ _ mα ω (R.cells i)).toReal)
        =ᵐ[μ] μ⟦R.cells i | mα⟧ := condExpKernel_ae_eq_condExp le_rfl (R.measurable i)
    -- `μ⟦R.cells i | mα⟧ = 𝟙_{R.cells i}` (a measurable function is its own conditional
    -- expectation w.r.t. the full σ-algebra).
    have h2 : μ⟦R.cells i | mα⟧ = (R.cells i).indicator (fun _ => (1 : ℝ)) :=
      condExp_of_stronglyMeasurable le_rfl
        ((stronglyMeasurable_const.indicator (R.measurable i)))
        ((integrable_const (1 : ℝ)).indicator (R.measurable i))
    rw [h2] at h1
    exact h1
  -- The pointwise sum of `negMulLog` of `{0, 1}`-valued indicators is `0`, `μ`-a.e.
  filter_upwards [ae_all_iff.mpr hcell] with ω hω
  refine Finset.sum_eq_zero fun i _ => ?_
  rw [hω i]
  -- `negMulLog` of an indicator value (`0` or `1`) is `0`.
  by_cases hmem : ω ∈ R.cells i
  · rw [Set.indicator_of_mem hmem, Real.negMulLog_one]
  · rw [Set.indicator_of_notMem hmem, Real.negMulLog_zero]

omit [StandardBorelSpace α] in
/-- **Structural refinement of the `(Q ∨ P)`-join over the `P`-join.** Each cell of the `n`-fold
join of `joinPartition Q P` is contained in the `n`-fold join cell of `P` indexed by the
second-coordinate projection: with `g n f := fun k => (f k).2`,
`(ksJoin hT (joinPartition Q P) n).cells f ⊆ (ksJoin hT P n).cells (g n f)`.

Each `(Q ∨ P)`-join cell is `⋂ₖ T⁻ᵏ(Q_{(f k).1} ∩ P_{(f k).2})`, contained in
`⋂ₖ T⁻ᵏ(P_{(f k).2})`, the `P`-join cell at `k ↦ (f k).2`. -/
lemma ksJoin_joinPartition_subset {κ : Type*} [Fintype κ] {μ : Measure α} {T : α → α}
    (hT : MeasurePreserving T μ μ) (Q : MeasurePartition μ κ) (P : MeasurePartition μ ι)
    (n : ℕ) (f : Fin n → κ × ι) :
    (ksJoin hT (joinPartition Q P) n).cells f ⊆
      (ksJoin hT P n).cells (fun k => (f k).2) := by
  rw [ksJoin_cells, ksJoin_cells, ksJoinCells_apply, ksJoinCells_apply]
  refine Set.iInter_mono fun k => ?_
  -- `T⁻ᵏ((Q ∨ P)_{f k}) = T⁻ᵏ(Q_{(f k).1} ∩ P_{(f k).2}) ⊆ T⁻ᵏ(P_{(f k).2})`.
  rw [joinPartition_cells, joinCells_apply]
  exact Set.preimage_mono Set.inter_subset_right

omit [StandardBorelSpace α] in
/-- **The index of a partition of a probability space is nonempty.** A probability space is
nonempty (`nonempty_of_isProbabilityMeasure`), so the cover `⋃ i, R.cells i = univ` is a nonempty
set; an empty index type would force the union to be empty, a contradiction. -/
lemma MeasurePartition.index_nonempty {μ : Measure α} [IsProbabilityMeasure μ]
    (R : MeasurePartition μ ι) : Nonempty ι := by
  obtain ⟨x⟩ := nonempty_of_isProbabilityMeasure μ
  obtain ⟨i, _⟩ := Set.mem_iUnion.mp (R.cover ▸ Set.mem_univ x)
  exact ⟨i⟩

/-- **N6.2 — the crux of the generator theorem.** For a generating partition `P` and *any* finite
partition `Q`, the partition-relative entropy of `Q` is dominated by that of `P`:
`h(T, Q) ≤ h(T, P)`.

Work with the join `R := joinPartition Q P`. Monotonicity under refinement gives `h(Q, T) ≤ h(R, T)`
(`ksEntropyPartition_le_join`). The unconditional Abramov–Rokhlin partition identity
`abramovRokhlin_partition`, applied with the refined partition `R` over the factor `P` and
conditioning on the **full** σ-algebra `mα`, splits `h(R, T) = h(P, T) + h(R, T | mα)`. The
saturation witness `⨆ n σ(P-join) = mα` is supplied by `hgen` (via
`iSup_generatedSigmaAlgebra_ksJoin_eq`), the refinement witness by `ksJoin_joinPartition_subset`,
and the relative term `h(R, T | mα) ≤ H(R | mα) = 0` by `condEntropy_full_eq_zero`. Hence
`h(R, T) = h(P, T)`, so `h(Q, T) ≤ h(P, T)`. -/
lemma ksEntropyPartition_le_of_generating {μ : Measure α} [IsProbabilityMeasure μ] {T : α → α}
    (hT : MeasurePreserving T μ μ) {n : ℕ} (P : MeasurePartition μ (Fin n))
    (hgen : IsGenerating μ T P) {m : ℕ} (Q : MeasurePartition μ (Fin m)) :
    ksEntropyPartition hT Q ≤ ksEntropyPartition hT P := by
  -- The refined partition `R = Q ∨ P`, the full-σ-algebra forward-invariance, and its nonempty
  -- index (the blocking step of `abramovRokhlin_partition` needs `Nonempty` of the refined index).
  set R : MeasurePartition μ (Fin m × Fin n) := joinPartition Q P with hR
  have hinv : MeasurableSpace.comap T mα ≤ mα := hT.measurable.comap_le
  have hne : Nonempty (Fin m × Fin n) := R.index_nonempty
  -- The saturation witness from `hgen`, in the shape `abramovRokhlin_partition` consumes.
  have hsat : (⨆ k, generatedSigmaAlgebra μ (ksJoin hT P k)) = mα := by
    rw [iSup_generatedSigmaAlgebra_ksJoin_eq]; exact hgen
  -- The structural refinement witness `g`.
  set g : ∀ k, (Fin k → Fin m × Fin n) → (Fin k → Fin n) :=
    fun _ f k => (f k).2 with hg
  have hrefine : ∀ k f, (ksJoin hT R k).cells f ≤ᵐ[μ] (ksJoin hT P k).cells (g k f) := by
    intro k f
    exact HasSubset.Subset.eventuallyLE
      (hR ▸ ksJoin_joinPartition_subset hT Q P k f)
  -- The Abramov–Rokhlin partition identity at the full σ-algebra `mα`.
  have hAR := abramovRokhlin_partition (𝒜 := mα) le_rfl hT hinv P R g hrefine hsat
  -- The relative term `h(R, T | mα) ≤ H(R | mα) = 0`, and it is also `≥ 0`, so it is `0`.
  have hrel_le : condKsEntropyPartition (𝒜 := mα) le_rfl hT hinv R ≤ condEntropy μ mα R.cells :=
    condKsEntropyPartition_le_condEntropy le_rfl hT hinv R
  rw [condEntropy_full_eq_zero R] at hrel_le
  have hrel_ge : 0 ≤ condKsEntropyPartition (𝒜 := mα) le_rfl hT hinv R :=
    condKsEntropyPartition_nonneg le_rfl hT hinv R
  have hrel : condKsEntropyPartition (𝒜 := mα) le_rfl hT hinv R = 0 :=
    le_antisymm hrel_le hrel_ge
  -- `h(R, T) = h(P, T)`.
  have hRP : ksEntropyPartition hT R = ksEntropyPartition hT P := by
    rw [hAR, hrel, add_zero]
  -- `h(Q, T) ≤ h(R, T) = h(P, T)`.
  calc ksEntropyPartition hT Q
      ≤ ksEntropyPartition hT (joinPartition Q P) := ksEntropyPartition_le_join hT Q P
    _ = ksEntropyPartition hT P := hRP

/-- **The Kolmogorov–Sinai generator theorem** (issue-#13 capstone): for a one-sided generating
finite partition `P` of a standard Borel probability space, the Kolmogorov–Sinai entropy of the
system equals the partition-relative entropy of `P`:
`h(T) = h(T, P)`.

`le_antisymm` of the free bound `h(T, P) ≤ h(T)` (`le_ksEntropy`) and the reverse `h(T) ≤ h(T, P)`.
The latter unfolds the supremum defining `ksEntropy` and reduces by `iSup_le` to the crux
`ksEntropyPartition_le_of_generating`, coerced to `EReal`. No ergodicity is needed; the
`StandardBorelSpace` and `IsProbabilityMeasure` instances are load-bearing (kernel disintegration),
and the saturation supplied by `hgen` is what makes the moving-index Abramov–Rokhlin limit valid. -/
theorem ksEntropy_eq_ksEntropyPartition_of_generating
    {μ : Measure α} [IsProbabilityMeasure μ] {T : α → α}
    (hT : MeasurePreserving T μ μ) {n : ℕ} (P : MeasurePartition μ (Fin n))
    (hgen : IsGenerating μ T P) :
    ksEntropy hT = ((ksEntropyPartition hT P : ℝ) : EReal) := by
  refine le_antisymm ?_ (le_ksEntropy hT P)
  -- Unfold the supremum and reduce to the crux.
  refine iSup_le fun m => iSup_le fun Q => ?_
  rw [EReal.coe_le_coe_iff]
  exact ksEntropyPartition_le_of_generating hT P hgen Q

end Oseledets.Entropy
