/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Entropy.GeneratorTheorem
import Oseledets.Entropy.JoinSigmaAlgebra
import Oseledets.Entropy.CondEntropyContinuous
import Oseledets.Entropy.CondPullback
import Oseledets.Krieger.ZIterate

/-!
# The two-sided Kolmogorov–Sinai generator theorem `h(e) = h(e, P)`

This file builds the **two-sided** (invertible) Kolmogorov–Sinai generator theorem: for a
measure-preserving *automorphism* `e : α ≃ᵐ α` of a standard Borel probability space and a
*two-sided generating* finite partition `P` (`Oseledets.Krieger.IsGeneratingTwoSided e P`, i.e. the
σ-algebra saturated under *both* time directions `⨆_{j : ℤ} eʲ σ(P)` is the ambient σ-algebra), the
entropy of the system is already attained on `P`: `h(e) = h(e, P)`.

The classical one-sided generator theorem (`Oseledets.Entropy.GeneratorTheorem`) requires forward
saturation `⨆_{n : ℕ} (eⁿ)⁻¹ σ(P) = mα`, which provably fails for genuine automorphisms such as the
two-sided Bernoulli shift; the correct hypothesis is the two-sided one. This module supplies the
*first half* of the reduction:

* the **symmetric window partition** `symWindow e he P N` representing `⋁_{j=-N}^{N} eʲ P`, realized
  cleanly as the `eᴺ`-pullback of the forward `(2N+1)`-fold join of `P`;
* the **saturation** identity `⨆_N σ(symWindow N) = ⨆_{j : ℤ} comap (eʲ) σ(P)`, so under
  `IsGeneratingTwoSided` the windows saturate the full σ-algebra;
* the **window invariance** `h(e, symWindow N) = h(e, P)` — the genuine *invertibility crux*, where
  `e` being an automorphism (`MeasurePreserving ⇑e.symm`) is used to relabel atoms of a doubly
  infinite window by the measure-preserving shift `eᴺ` without changing entropy.

The window invariance is assembled from two reusable identities (cf. Le Maître, *Notes on the
Kolmogorov–Sinai theorem* (2017), Thm 5; Walkden, Manchester, Lecture 25):

* **W2 (iterate invariance)** `h(e, R.pullback (ziter e c)) = h(e, R)` for any `c : ℤ` and any
  partition `R` — clean, holding at the level of each entropy-sequence term, no over-counting; this
  is the one place the negative iterates of the inverse `e.symm` enter.
* **W1 (block identity)** `h(e, ksJoin he P k) = h(e, P)` — the standard `h(e, ⋁₀^{k-1} e⁻ⁱP) =
  h(e, P)`, proved through the exact sequence-level telescoping
  `H(⋁₀^{m-1} e⁻ʲ(⋁₀^{k-1} e⁻ⁱP)) = H(⋁₀^{m+k-2} e⁻ˡP)` and a Cesàro shift.

Composing, with `symWindow e he P N = (ksJoin he P (2N+1)).pullback (ziter e (-N))`:
`h(e, symWindow N) = h(e, ksJoin he P (2N+1)) = h(e, P)`.

## References

* François Le Maître, *Notes on the Kolmogorov–Sinai theorem* (2017), §2.
* Charles Walkden, *Ergodic Theory* (Manchester, MATH41112/61112), Lecture 25.
* Peter Walters, *An Introduction to Ergodic Theory*, GTM **79**, Springer (1982), Ch. 4.
-/

open MeasureTheory Function Filter Topology ProbabilityTheory MeasurableSpace
open Oseledets.Krieger

namespace Oseledets.Entropy

variable {α : Type*} {ι : Type*} {𝒜 : MeasurableSpace α} [mα : MeasurableSpace α] {μ : Measure α}

/-- **The generated σ-algebra of a pullback partition is the comap of the base.** For a
measure-preserving endomorphism `T` and a finite partition `P`, the σ-algebra `σ(T⁻¹P)` generated by
the cells of the pullback partition equals `comap T σ(P)`. (The endomorphism mirror of
`Oseledets.Entropy.comap_generatedSigmaAlgebra_pulledBack`.) -/
lemma generatedSigmaAlgebra_pullback [Fintype ι] {T : α → α} (hT : MeasurePreserving T μ μ)
    (P : MeasurePartition μ ι) :
    generatedSigmaAlgebra μ (P.pullback hT) =
      MeasurableSpace.comap T (generatedSigmaAlgebra μ P) := by
  rw [generatedSigmaAlgebra, generatedSigmaAlgebra, MeasurableSpace.comap_generateFrom,
    MeasurePartition.pullback_cells, Set.range_comp' (T ⁻¹' ·) P.cells]

variable [Fintype ι]

/-- The **symmetric window partition** `symWindow e he P N`, representing the doubly-infinite window
join `⋁_{j=-N}^{N} eʲ P`, realized as the `eᴺ`-pullback of the forward `(2N+1)`-fold join of `P`:
its cell at `g : Fin (2N+1) → ι` is `⋂_{i=0}^{2N} (e^{i-N})⁻¹(P_{g i})`. This single clean
`pullback`-of-`ksJoin` definition is what makes both the saturation identity and the window-entropy
invariance close (the latter via the iterate-invariance lemma `W2` and the block identity `W1`). -/
noncomputable def symWindow (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    (P : MeasurePartition μ ι) (N : ℕ) : MeasurePartition μ (Fin (2 * N + 1) → ι) :=
  (ksJoin he P (2 * N + 1)).pullback (measurePreserving_ziter e he (-(N : ℤ)))

@[simp]
lemma symWindow_cells (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    (P : MeasurePartition μ ι) (N : ℕ) :
    (symWindow e he P N).cells =
      fun g => (ziter e (-(N : ℤ))) ⁻¹' (ksJoinCells P.cells (⇑e) (2 * N + 1) g) := by
  rw [symWindow, MeasurePartition.pullback_cells, ksJoin_cells]

/-- **Coordinate shift identity.** Pulling the forward `k`-coordinate cylinder `(eᵏ)⁻¹A` back along
`e⁻ᴺ` (`= ziter e (-N)`) shifts it to the two-sided `(k-N)`-coordinate cylinder
`(e^{k-N})⁻¹A`. This is the cocycle law `ziter_add` packaged for set preimages, and is the engine of
both the cell formula `symWindow_cell_eq` and the coordinate measurability
`measurableSet_symWindow_coord`. -/
lemma ziter_neg_preimage_iterate (e : α ≃ᵐ α) (N k : ℕ) (A : Set α) :
    (ziter e (-(N : ℤ))) ⁻¹' ((⇑e)^[k] ⁻¹' A) = (ziter e ((k : ℤ) - (N : ℤ))) ⁻¹' A := by
  have hcomp : ziter e ((k : ℤ) - (N : ℤ)) = (⇑e)^[k] ∘ ziter e (-(N : ℤ)) := by
    rw [show ((k : ℤ) - (N : ℤ)) = (k : ℤ) + (-(N : ℤ)) by ring, ziter_add, ziter_natCast]
  rw [hcomp, Set.preimage_comp]

/-- The cell of `symWindow e he P N` at `g` is the two-sided window cylinder
`⋂_{i=0}^{2N} (e^{i-N})⁻¹(P_{g i})`. -/
lemma symWindow_cell_eq (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    (P : MeasurePartition μ ι) (N : ℕ) (g : Fin (2 * N + 1) → ι) :
    (symWindow e he P N).cells g =
      ⋂ i : Fin (2 * N + 1), (ziter e (((i : ℕ) : ℤ) - (N : ℤ))) ⁻¹' P.cells (g i) := by
  simp only [symWindow_cells, ksJoinCells_apply, Set.preimage_iInter]
  exact Set.iInter_congr fun i => ziter_neg_preimage_iterate e N (i : ℕ) (P.cells (g i))

/-- **Coordinate measurability for the symmetric window.** For `|j| ≤ N`, written `j = k - N` with
`k : Fin (2N+1)`, the two-sided coordinate cylinder `(e^{k-N})⁻¹(P_i)` is measurable with respect to
the σ-algebra generated by `symWindow e he P N`. Obtained from the one-sided coordinate
measurability `measurableSet_preimage_cells` of the underlying forward join, pulled back along
`e⁻ᴺ` through `generatedSigmaAlgebra_pullback`. -/
lemma measurableSet_symWindow_coord (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    (P : MeasurePartition μ ι) (N : ℕ) (k : Fin (2 * N + 1)) (i : ι) :
    MeasurableSet[generatedSigmaAlgebra μ (symWindow e he P N)]
      ((ziter e (((k : ℕ) : ℤ) - (N : ℤ))) ⁻¹' P.cells i) := by
  rw [symWindow, generatedSigmaAlgebra_pullback]
  refine ⟨(⇑e)^[(k : ℕ)] ⁻¹' P.cells i, measurableSet_preimage_cells he P (2 * N + 1) k i, ?_⟩
  exact ziter_neg_preimage_iterate e N (k : ℕ) (P.cells i)

/-- **Saturation of the symmetric windows.** The supremum over window radii `N` of the σ-algebras
generated by the symmetric windows equals the two-sided saturated σ-algebra of `P`:
`⨆_N σ(symWindow N) = ⨆_{j : ℤ} comap (ziter e j) σ(P)`.

Combined with `IsGeneratingTwoSided e P` (whose content is that the right-hand side is `mα`), this
shows the symmetric windows saturate the full ambient σ-algebra. The `≤` direction expands each
window cell as a finite intersection of two-sided coordinate cylinders (`symWindow_cell_eq`), each a
generator of the right-hand side; the `≥` direction realizes each `comap (ziter e j) σ(P)` inside a
window of radius `|j|` via the coordinate measurability `measurableSet_symWindow_coord`. -/
lemma iSup_generatedSigmaAlgebra_symWindow (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    (P : MeasurePartition μ ι) :
    (⨆ N : ℕ, generatedSigmaAlgebra μ (symWindow e he P N)) =
      ⨆ j : ℤ, MeasurableSpace.comap (ziter e j) (generatedSigmaAlgebra μ P) := by
  apply le_antisymm
  · -- `≤`: each window σ-algebra sits below the two-sided saturation.
    refine iSup_le fun N => ?_
    refine generateFrom_le ?_
    rintro s ⟨g, rfl⟩
    rw [symWindow_cell_eq]
    refine MeasurableSet.iInter fun i => ?_
    refine (le_iSup (fun j : ℤ => MeasurableSpace.comap (ziter e j) (generatedSigmaAlgebra μ P))
      (((i : ℕ) : ℤ) - (N : ℤ))) _ ?_
    exact ⟨P.cells (g i), measurableSet_generateFrom ⟨g i, rfl⟩, rfl⟩
  · -- `≥`: each two-sided pullback sits inside a window of radius `|j|`.
    refine iSup_le fun j => ?_
    set N : ℕ := j.natAbs with hN
    -- `k := j + N ∈ Fin (2N+1)`, with `(k : ℤ) - N = j`.
    have hk_lt : (j + (N : ℤ)).toNat < 2 * N + 1 := by omega
    set k : Fin (2 * N + 1) := ⟨(j + (N : ℤ)).toNat, hk_lt⟩ with hk
    have hkval : ((k : ℕ) : ℤ) - (N : ℤ) = j := by
      have hkn : (k : ℕ) = (j + (N : ℤ)).toNat := rfl
      rw [hkn]; omega
    refine le_trans ?_ (le_iSup (fun M : ℕ => generatedSigmaAlgebra μ (symWindow e he P M)) N)
    have hcomap : MeasurableSpace.comap (ziter e j) (generatedSigmaAlgebra μ P)
        = generateFrom (Set.preimage (ziter e j) '' Set.range P.cells) := by
      rw [generatedSigmaAlgebra, MeasurableSpace.comap_generateFrom]
    rw [hcomap]
    refine generateFrom_le ?_
    rintro s ⟨t, ⟨i, rfl⟩, rfl⟩
    have hcoord := measurableSet_symWindow_coord e he P N k i
    rwa [hkval] at hcoord

/-- **Entropy is invariant under an injective relabeling with null off-image cells.** If `ψ : J → I`
is injective, the measures match on the image (`μ (s (ψ j)) = μ (t j)`), and every cell off the
image is `μ`-null, then `entropy μ s = entropy μ t`. (The over-counted window-join cells are exactly
the off-image null cells; the consistent ones are the image, in measure-preserving bijection with
the forward-join cells.) -/
lemma entropy_eq_of_injective_of_ae_null {I J : Type*} [Fintype I] [Fintype J]
    (s : I → Set α) (t : J → Set α) (ψ : J → I) (hψ : Function.Injective ψ)
    (hmeas : ∀ j, μ (s (ψ j)) = μ (t j))
    (hnull : ∀ i, i ∉ Set.range ψ → μ (s i) = 0) :
    entropy μ s = entropy μ t := by
  classical
  rw [entropy_def, entropy_def]
  have key : ∑ i : I, Real.negMulLog (μ (s i)).toReal
      = ∑ i ∈ (Finset.univ : Finset J).image ψ, Real.negMulLog (μ (s i)).toReal := by
    refine (Finset.sum_subset (Finset.subset_univ _) ?_).symm
    intro i _ hi
    have hnr : i ∉ Set.range ψ := by
      rw [Set.mem_range, not_exists]
      intro j hj
      exact hi (Finset.mem_image.mpr ⟨j, Finset.mem_univ j, hj⟩)
    rw [hnull i hnr, ENNReal.toReal_zero, Real.negMulLog_zero]
  rw [key, Finset.sum_image (fun x _ y _ h => hψ h)]
  exact Finset.sum_congr rfl fun j _ => by rw [hmeas j]

/-- **Iterate invariance of the iterated-join entropy sequence (W2, sequence level).** For any two-
sided iterate `ziter e c`, the entropy sequence of the pullback partition `(ziter e c)⁻¹ P` equals
that of `P` at *every* `n` — no over-counting: the `n`-fold dynamical join of `(ziter e c)⁻¹ P` is
exactly the `(ziter e c)`-pullback of the `n`-fold join of `P` (the iterate commutes with `e^[k]`),
and `entropy_pullback` then identifies the entropies. This is the one place the negative iterates of
the inverse `e.symm` enter. -/
lemma ksEntropySeq_pullback_ziter (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    [IsProbabilityMeasure μ] (P : MeasurePartition μ ι) (c : ℤ) (n : ℕ) :
    ksEntropySeq he (P.pullback (measurePreserving_ziter e he c)) n = ksEntropySeq he P n := by
  rw [ksEntropySeq, ksEntropySeq]
  have hcells : (ksJoin he (P.pullback (measurePreserving_ziter e he c)) n).cells
      = ((ksJoin he P n).pullback (measurePreserving_ziter e he c)).cells := by
    funext F
    simp only [ksJoin_cells, MeasurePartition.pullback_cells, ksJoinCells_apply,
      Set.preimage_iInter]
    refine Set.iInter_congr fun k => ?_
    have hcomm : ziter e c ∘ (⇑e)^[(k : ℕ)] = (⇑e)^[(k : ℕ)] ∘ ziter e c := by
      rw [← ziter_natCast e (k : ℕ), ← ziter_add, ← ziter_add, Int.add_comm]
    rw [← Set.preimage_comp, ← Set.preimage_comp, hcomm]
  rw [hcells, entropy_pullback]

/-- **Iterate invariance of the Kolmogorov–Sinai entropy (W2).** `h(e, (ziter e c)⁻¹ P) = h(e, P)`:
the Fekete limits agree since the entropy sequences agree termwise
(`ksEntropySeq_pullback_ziter`). -/
lemma ksEntropyPartition_pullback_ziter (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    [IsProbabilityMeasure μ] (P : MeasurePartition μ ι) (c : ℤ) :
    ksEntropyPartition he (P.pullback (measurePreserving_ziter e he c)) =
      ksEntropyPartition he P := by
  refine tendsto_nhds_unique (tendsto_ksEntropySeq he _) ?_
  have heq : ∀ n, ksEntropySeq he (P.pullback (measurePreserving_ziter e he c)) n
      = ksEntropySeq he P n := fun n => ksEntropySeq_pullback_ziter e he P c n
  simp_rw [heq]
  exact tendsto_ksEntropySeq he P

/-- **Block decomposition of an index.** For `m ≥ 1`, every `l : Fin (m + K)` can be written as
`l = i + j` with `j : Fin m` and `i : Fin (K + 1)`. Witnessed by `j = min l (m-1)`, `i = l - j`. -/
lemma exists_block_decomp {m K : ℕ} (hm : 1 ≤ m) (l : Fin (m + K)) :
    ∃ (j : Fin m) (i : Fin (K + 1)), (i : ℕ) + (j : ℕ) = (l : ℕ) := by
  have hl := l.isLt
  set jv := min (l : ℕ) (m - 1) with hjv
  have hjm : jv < m := by omega
  have hiK : (l : ℕ) - jv < K + 1 := by omega
  have hsum : ((l : ℕ) - jv) + jv = (l : ℕ) := by omega
  exact ⟨⟨jv, hjm⟩, ⟨(l : ℕ) - jv, hiK⟩, hsum⟩

/-- **The block-encode relabeling** `ψ` underlying the block identity W1: a forward `(m+K)`-join
index `h` is read as the consistent `m`-fold join of `(K+1)`-blocks whose `(j, i)`-entry is
`h (i + j)`. Its image is exactly the *consistent* block-join indices; the inconsistent ones index
`μ`-null over-counted cells. -/
def blockEncode (m K : ℕ) (h : Fin (m + K) → ι) (j : Fin m) (i : Fin (K + 1)) : ι :=
  h ⟨(i : ℕ) + (j : ℕ), by have := i.isLt; have := j.isLt; omega⟩

/-- **Block identity, sequence level (W1).** For `m ≥ 1`, the `m`-fold dynamical-join entropy of the
length-`(K+1)` block partition `⋁₀^K e⁻ⁱP` equals the `(m+K)`-fold dynamical-join entropy of `P`:
`H(⋁₀^{m-1} e⁻ʲ(⋁₀^K e⁻ⁱP)) = H(⋁₀^{m+K-1} e⁻ˡP)`. The over-counted block-join cells are reindexed
by `blockEncode` onto the forward-join cells (an injection whose image is the *consistent* cells,
their measures matching, the inconsistent cells being `μ`-null);
`entropy_eq_of_injective_of_ae_null` then identifies the two entropies. -/
lemma ksEntropySeq_ksJoin_succ (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    [IsProbabilityMeasure μ] (P : MeasurePartition μ ι) (K : ℕ) {m : ℕ} (hm : 1 ≤ m) :
    ksEntropySeq he (ksJoin he P (K + 1)) m = ksEntropySeq he P (m + K) := by
  rw [ksEntropySeq, ksEntropySeq]
  refine entropy_eq_of_injective_of_ae_null
    (ksJoin he (ksJoin he P (K + 1)) m).cells (ksJoin he P (m + K)).cells (blockEncode m K)
    ?_ ?_ ?_
  · -- `blockEncode m K` is injective: each forward index is recovered via the block decomposition.
    intro h h' hhe
    funext l
    obtain ⟨j, i, hij⟩ := exists_block_decomp hm l
    rw [show l = (⟨(i : ℕ) + (j : ℕ), by have := i.isLt; have := j.isLt; omega⟩ : Fin (m + K))
          from Fin.ext hij.symm]
    exact congrFun (congrFun hhe j) i
  · -- Measure match: the consistent block-join cell equals the forward-join cell as a set.
    intro h
    refine congrArg μ ?_
    have hLHS : (ksJoin he (ksJoin he P (K + 1)) m).cells (blockEncode m K h)
        = ⋂ (j : Fin m), ⋂ (i : Fin (K + 1)),
            (⇑e)^[(i : ℕ) + (j : ℕ)] ⁻¹' P.cells (blockEncode m K h j i) := by
      simp only [ksJoin_cells, ksJoinCells_apply, Set.preimage_iInter]
      refine Set.iInter_congr fun j => Set.iInter_congr fun i => ?_
      rw [← Set.preimage_comp, ← Function.iterate_add]
    have hRHS : (ksJoin he P (m + K)).cells h
        = ⋂ l : Fin (m + K), (⇑e)^[(l : ℕ)] ⁻¹' P.cells (h l) := by
      simp only [ksJoin_cells, ksJoinCells_apply]
    rw [hLHS, hRHS]
    apply Set.Subset.antisymm
    · -- consistent cell `⊆` each forward coordinate cell (decompose the coordinate)
      rw [Set.subset_iInter_iff]
      intro l
      obtain ⟨j, i, hij⟩ := exists_block_decomp hm l
      have hkey : (⇑e)^[(i : ℕ) + (j : ℕ)] ⁻¹' P.cells (blockEncode m K h j i)
          = (⇑e)^[(l : ℕ)] ⁻¹' P.cells (h l) := by
        have hbe : blockEncode m K h j i = h l := by
          rw [blockEncode]; congr 1; exact Fin.ext hij
        rw [hij, hbe]
      exact (Set.iInter_subset _ j).trans ((Set.iInter_subset _ i).trans (subset_of_eq hkey))
    · -- forward cell `⊆` each block coordinate cell
      rw [Set.subset_iInter_iff]; intro j
      rw [Set.subset_iInter_iff]; intro i
      exact Set.iInter_subset _
        (⟨(i : ℕ) + (j : ℕ), by have := i.isLt; have := j.isLt; omega⟩ : Fin (m + K))
  · -- Inconsistent indices are `μ`-null: two coordinates collide at distinct `P`-cells.
    intro F hF
    have hcollide : ∃ (j : Fin m) (i : Fin (K + 1)) (j' : Fin m) (i' : Fin (K + 1)),
        (i : ℕ) + (j : ℕ) = (i' : ℕ) + (j' : ℕ) ∧ F j i ≠ F j' i' := by
      by_contra hcon
      simp only [not_exists, not_and, not_not, ne_eq] at hcon
      apply hF
      classical
      choose decJ decI hdec using fun l : Fin (m + K) => exists_block_decomp hm l
      refine ⟨fun l => F (decJ l) (decI l), ?_⟩
      funext j₀ i₀
      have hb : (i₀ : ℕ) + (j₀ : ℕ) < m + K := by have := i₀.isLt; have := j₀.isLt; omega
      exact hcon (decJ ⟨_, hb⟩) (decI ⟨_, hb⟩) j₀ i₀ (by simpa using hdec ⟨_, hb⟩)
    obtain ⟨j, i, j', i', hexp, hne⟩ := hcollide
    have hsub : ∀ (j₂ : Fin m) (i₂ : Fin (K + 1)),
        (ksJoin he (ksJoin he P (K + 1)) m).cells F
          ⊆ (⇑e)^[(i₂ : ℕ) + (j₂ : ℕ)] ⁻¹' P.cells (F j₂ i₂) := by
      intro j₂ i₂
      have hcomp : (⇑e)^[(i₂ : ℕ)] ∘ (⇑e)^[(j₂ : ℕ)] = (⇑e)^[(i₂ : ℕ) + (j₂ : ℕ)] :=
        (Function.iterate_add (⇑e) (i₂ : ℕ) (j₂ : ℕ)).symm
      rw [ksJoin_cells, ksJoinCells_apply]
      refine (Set.iInter_subset _ j₂).trans ?_
      rw [ksJoin_cells, ksJoinCells_apply, Set.preimage_iInter]
      refine (Set.iInter_subset _ i₂).trans (subset_of_eq ?_)
      rw [← Set.preimage_comp, hcomp]
    have h1 := hsub j i
    have h2 := hsub j' i'
    rw [← hexp] at h2
    have hsub2 : (ksJoin he (ksJoin he P (K + 1)) m).cells F
        ⊆ (⇑e)^[(i : ℕ) + (j : ℕ)] ⁻¹' (P.cells (F j i) ∩ P.cells (F j' i')) := by
      rw [Set.preimage_inter]
      exact Set.subset_inter h1 h2
    refine measure_mono_null hsub2 ?_
    rw [(he.iterate ((i : ℕ) + (j : ℕ))).measure_preimage
      ((P.measurable (F j i)).inter (P.measurable (F j' i'))).nullMeasurableSet]
    exact P.aedisjoint hne

/-- **Block identity (W1).** `h(e, ⋁₀^K e⁻ⁱP) = h(e, P)`: the Kolmogorov–Sinai entropy of the system
relative to a length-`(K+1)` block partition equals that relative to `P`. The Cesàro limit of the
sequence identity `ksEntropySeq_ksJoin_succ`: `H_block(m)/m = (H_P(m+K)/(m+K)) · ((m+K)/m)` for
`m ≥ 1`, where the first factor converges to `h(e, P)` (a shift of the Fekete sequence) and the
second to `1`. -/
lemma ksEntropyPartition_ksJoin (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    [IsProbabilityMeasure μ] (P : MeasurePartition μ ι) (K : ℕ) :
    ksEntropyPartition he (ksJoin he P (K + 1)) = ksEntropyPartition he P := by
  refine tendsto_nhds_unique (tendsto_ksEntropySeq he (ksJoin he P (K + 1))) ?_
  have hshift : Tendsto (fun m : ℕ => ksEntropySeq he P (m + K) / ((m + K : ℕ) : ℝ)) atTop
      (𝓝 (ksEntropyPartition he P)) :=
    (tendsto_ksEntropySeq he P).comp (tendsto_add_atTop_nat K)
  have hratio : Tendsto (fun m : ℕ => ((m + K : ℕ) : ℝ) / (m : ℝ)) atTop (𝓝 1) := by
    have h0 : Tendsto (fun m : ℕ => (K : ℝ) / (m : ℝ)) atTop (𝓝 0) :=
      tendsto_const_div_atTop_nhds_zero_nat (K : ℝ)
    have h1 : Tendsto (fun m : ℕ => 1 + (K : ℝ) / (m : ℝ)) atTop (𝓝 (1 + 0)) :=
      tendsto_const_nhds.add h0
    rw [add_zero] at h1
    refine h1.congr' ?_
    filter_upwards [eventually_gt_atTop 0] with m hm
    have hm0 : (m : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
    rw [Nat.cast_add, add_div, div_self hm0]
  have hprod := hshift.mul hratio
  rw [mul_one] at hprod
  refine hprod.congr' ?_
  filter_upwards [eventually_ge_atTop 1] with m hm
  have hm0 : (m : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
  have hmK0 : ((m + K : ℕ) : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
  rw [ksEntropySeq_ksJoin_succ e he P K hm]
  field_simp

/-- **Window invariance (the invertibility crux).** `h(e, symWindow N) = h(e, P)`: the Kolmogorov–
Sinai entropy of the system relative to the symmetric window `⋁_{j=-N}^{N} eʲ P` equals that
relative to `P`. The window is the `eᴺ`-pullback of the forward `(2N+1)`-block, so iterate W2
(`ksEntropyPartition_pullback_ziter`) strips the shift — this is the only step needing `e` to be an
automorphism — and the block identity W1 (`ksEntropyPartition_ksJoin`) collapses the block. -/
lemma ksEntropyPartition_symWindow_eq (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    [IsProbabilityMeasure μ] (P : MeasurePartition μ ι) (N : ℕ) :
    ksEntropyPartition he (symWindow e he P N) = ksEntropyPartition he P := by
  unfold symWindow
  rw [ksEntropyPartition_pullback_ziter e he (ksJoin he P (2 * N + 1)) (-(N : ℤ))]
  exact ksEntropyPartition_ksJoin e he P (2 * N)

/-! ## The continuity half (L2): conditioning on the growing windowed σ-algebra -/

/-- **Conditional entropy of a partition measured by the conditioning σ-algebra vanishes.** If every
cell of `R` is `𝒜`-measurable (`𝒜 ≤ mα`), then `condEntropy μ 𝒜 R.cells = 0`: each `𝒜`-measurable
indicator is its own conditional expectation, so the kernel cell masses are `0`/`1` a.e. and every
`negMulLog` term vanishes (the `𝒜 ≤ mα` generalization of `condEntropy_full_eq_zero`). -/
lemma condEntropy_eq_zero_of_measurable [StandardBorelSpace α] [IsProbabilityMeasure μ]
    (h𝒜 : 𝒜 ≤ mα) (R : MeasurePartition μ ι) (hR : ∀ i, MeasurableSet[𝒜] (R.cells i)) :
    condEntropy μ 𝒜 R.cells = 0 := by
  haveI : SigmaFinite (μ.trim h𝒜) := inferInstance
  rw [condEntropy_def]
  refine integral_eq_zero_of_ae ?_
  have hcell : ∀ i : ι, (fun ω => (@condExpKernel α mα _ μ _ 𝒜 ω (R.cells i)).toReal)
      =ᵐ[μ] (R.cells i).indicator (fun _ => (1 : ℝ)) := by
    intro i
    have h1 : (fun ω => (@condExpKernel α mα _ μ _ 𝒜 ω (R.cells i)).toReal)
        =ᵐ[μ] μ⟦R.cells i | 𝒜⟧ := condExpKernel_ae_eq_condExp h𝒜 (R.measurable i)
    have hfm : StronglyMeasurable[𝒜] ((R.cells i).indicator (fun _ => (1 : ℝ))) :=
      stronglyMeasurable_const.indicator (hR i)
    have hfi : Integrable ((R.cells i).indicator (fun _ => (1 : ℝ))) μ :=
      (integrable_const (1 : ℝ)).indicator (R.measurable i)
    have h2 : μ⟦R.cells i | 𝒜⟧ = (R.cells i).indicator (fun _ => (1 : ℝ)) :=
      condExp_of_stronglyMeasurable h𝒜 hfm hfi
    rw [h2] at h1
    exact h1
  filter_upwards [ae_all_iff.mpr hcell] with ω hω
  refine Finset.sum_eq_zero fun i _ => ?_
  rw [hω i]
  by_cases hmem : ω ∈ R.cells i
  · rw [Set.indicator_of_mem hmem, Real.negMulLog_one]
  · rw [Set.indicator_of_notMem hmem, Real.negMulLog_zero]

/-- The **windowed forward-saturated σ-algebra** `winSat e he P N`: the forward-`e`-saturation of
the symmetric window `symWindow e he P N`, i.e. `⨆ n, σ(⋁₀^{n-1} e⁻ᵏ (symWindow N))`. It is
forward-`e`-invariant (`comap_winSat_le`), increasing in `N` (`winSat_mono`), and saturates `mα` as
`N → ∞` under two-sided generation (`iSup_winSat_eq`); conditioning the Abramov–Rokhlin identity on
it (rather than on `mα`) lets the relative term vanish by Lévy-upward continuity. -/
@[reducible]
noncomputable def winSat (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    (P : MeasurePartition μ ι) (N : ℕ) : MeasurableSpace α :=
  ⨆ n : ℕ, generatedSigmaAlgebra μ (ksJoin he (symWindow e he P N) n)

/-- The windowed σ-algebra is **forward-`e`-invariant**: `comap (⇑e) (winSat N) ≤ winSat N`. Through
`iSup_generatedSigmaAlgebra_ksJoin_eq`, `winSat N = ⨆ k, comap (e^[k]) σ(symWindow N)`, and pulling
back by `e` shifts the index `k ↦ k+1`, staying inside the supremum. -/
lemma comap_winSat_le (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    (P : MeasurePartition μ ι) (N : ℕ) :
    MeasurableSpace.comap (⇑e) (winSat e he P N) ≤ winSat e he P N := by
  unfold winSat
  rw [iSup_generatedSigmaAlgebra_ksJoin_eq he (symWindow e he P N),
    MeasurableSpace.comap_iSup]
  refine iSup_le fun k => ?_
  have hcomp : (⇑e)^[k] ∘ (⇑e) = (⇑e)^[k + 1] := (Function.iterate_succ (⇑e) k).symm
  rw [MeasurableSpace.comap_comp, hcomp]
  exact le_iSup
    (fun k => MeasurableSpace.comap ((⇑e)^[k]) (generatedSigmaAlgebra μ (symWindow e he P N)))
    (k + 1)

/-- **Monotonicity of the window σ-algebra in the radius.** For `N₁ ≤ N₂`, `σ(symWindow N₁) ≤
σ(symWindow N₂)`: every two-sided coordinate cylinder `(e^{k-N₁})⁻¹(P_·)` of the smaller window has
exponent `|k - N₁| ≤ N₁ ≤ N₂`, hence is a coordinate of the larger window
(`measurableSet_symWindow_coord`). -/
lemma generatedSigmaAlgebra_symWindow_mono (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ)
    (P : MeasurePartition μ ι) {N₁ N₂ : ℕ} (hN : N₁ ≤ N₂) :
    generatedSigmaAlgebra μ (symWindow e he P N₁) ≤
      generatedSigmaAlgebra μ (symWindow e he P N₂) := by
  refine generateFrom_le ?_
  rintro s ⟨g, rfl⟩
  rw [symWindow_cell_eq]
  refine MeasurableSet.iInter fun k => ?_
  have hk_lt : (k : ℕ) + (N₂ - N₁) < 2 * N₂ + 1 := by have := k.isLt; omega
  have hms := measurableSet_symWindow_coord e he P N₂ ⟨(k : ℕ) + (N₂ - N₁), hk_lt⟩ (g k)
  have hval : (((⟨(k : ℕ) + (N₂ - N₁), hk_lt⟩ : Fin (2 * N₂ + 1)) : ℕ)) = (k : ℕ) + (N₂ - N₁) :=
    rfl
  rw [hval] at hms
  have heq : (((k : ℕ) + (N₂ - N₁) : ℕ) : ℤ) - (N₂ : ℤ) = ((k : ℕ) : ℤ) - (N₁ : ℤ) := by
    have := k.isLt; omega
  rwa [heq] at hms

/-- The windowed σ-algebra is **monotone in the radius `N`**. Reduces to monotonicity of
`σ(symWindow N)` (`generatedSigmaAlgebra_symWindow_mono`), pushed through the forward saturation
`iSup_generatedSigmaAlgebra_ksJoin_eq` (each `comap (e^[k]) ·` and the supremum are monotone). -/
lemma winSat_mono (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ) (P : MeasurePartition μ ι) :
    Monotone (winSat e he P) := by
  intro N₁ N₂ hN
  unfold winSat
  rw [iSup_generatedSigmaAlgebra_ksJoin_eq he (symWindow e he P N₁),
    iSup_generatedSigmaAlgebra_ksJoin_eq he (symWindow e he P N₂)]
  exact iSup_mono fun k =>
    MeasurableSpace.comap_mono (generatedSigmaAlgebra_symWindow_mono e he P hN)

/-- **The windows saturate the full σ-algebra.** Under two-sided generation, `⨆ N, winSat N = mα`.
Each `winSat N ≤ mα`; conversely `mα = ⨆ j comap (eʲ) σ(P) = ⨆ N σ(symWindow N)` (`hgen` and the L1
saturation `iSup_generatedSigmaAlgebra_symWindow`), and `σ(symWindow N) = σ(⋁₀ symWindow N) ≤
winSat N` (`generatedSigmaAlgebra_ksJoin_one` at `n = 1`). -/
lemma iSup_winSat_eq (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ) (P : MeasurePartition μ ι)
    (hgen : IsGeneratingTwoSided e P) :
    (⨆ N : ℕ, winSat e he P N) = mα := by
  refine le_antisymm (iSup_le fun N => iSup_le fun n => generatedSigmaAlgebra_le _) ?_
  have hgen' : (⨆ j : ℤ, MeasurableSpace.comap (ziter e j) (generatedSigmaAlgebra μ P)) = mα :=
    hgen
  have hsub : (⨆ j : ℤ, MeasurableSpace.comap (ziter e j) (generatedSigmaAlgebra μ P))
      ≤ ⨆ N : ℕ, winSat e he P N := by
    rw [← iSup_generatedSigmaAlgebra_symWindow e he P]
    refine iSup_mono fun N => ?_
    rw [← generatedSigmaAlgebra_ksJoin_one he (symWindow e he P N)]
    exact le_iSup
      (fun n => generatedSigmaAlgebra μ (ksJoin he (symWindow e he P N) n)) 1
  rwa [hgen'] at hsub

/-- **L2 crux — the continuity bound.** For a two-sided generating `P` and any finite partition `Q`,
`h(e, Q) ≤ h(e, P)`. Conditioning the unconditional Abramov–Rokhlin identity on the *forward-
invariant* windowed σ-algebra `winSat N` (not `mα`) splits `h(e, Q ∨ symWindow N)` into `h(e,
symWindow N) + h(e, Q ∨ symWindow N | winSat N)`; window invariance (W1+W2) collapses the first to
`h(e, P)`, while the relative term is `≤ condEntropy μ (winSat N) Q.cells` (the `symWindow N` part
is `winSat N`-measurable, contributing `0`). As `N → ∞`, `winSat N ↗ mα`, so by Lévy continuity
`condEntropy μ (winSat N) Q.cells → condEntropy μ mα Q.cells = 0`, giving the bound. -/
lemma ksEntropyPartition_le_of_isGeneratingTwoSided [StandardBorelSpace α] [IsProbabilityMeasure μ]
    (e : α ≃ᵐ α) (he : MeasurePreserving (⇑e) μ μ) {n : ℕ} (P : MeasurePartition μ (Fin n))
    (hgen : IsGeneratingTwoSided e P) {m : ℕ} (Q : MeasurePartition μ (Fin m)) :
    ksEntropyPartition he Q ≤ ksEntropyPartition he P := by
  have hle : ∀ N, winSat e he P N ≤ mα := fun N => iSup_le fun n => generatedSigmaAlgebra_le _
  -- Per-radius bound from Abramov–Rokhlin conditioned on `winSat N`.
  have hperN : ∀ N, ksEntropyPartition he Q
      ≤ ksEntropyPartition he P + condEntropy μ (winSat e he P N) Q.cells := by
    intro N
    set R : MeasurePartition μ (Fin m × (Fin (2 * N + 1) → Fin n)) :=
      joinPartition Q (symWindow e he P N) with hRdef
    haveI : Nonempty (Fin m × (Fin (2 * N + 1) → Fin n)) := R.index_nonempty
    have hinv : MeasurableSpace.comap (⇑e) (winSat e he P N) ≤ winSat e he P N :=
      comap_winSat_le e he P N
    have hsat : (⨆ k, generatedSigmaAlgebra μ (ksJoin he (symWindow e he P N) k))
        = winSat e he P N := rfl
    have hrefine : ∀ k f, (ksJoin he R k).cells f ≤ᵐ[μ]
        (ksJoin he (symWindow e he P N) k).cells (fun j => (f j).2) := by
      intro k f
      exact HasSubset.Subset.eventuallyLE
        (hRdef ▸ ksJoin_joinPartition_subset he Q (symWindow e he P N) k f)
    have hAR := abramovRokhlin_partition (hle N) he hinv (symWindow e he P N) R
      (fun _ f j => (f j).2) hrefine hsat
    -- `symWindow N` is measured by `winSat N`, so its conditional entropy vanishes.
    have hWcells : ∀ i, MeasurableSet[winSat e he P N] ((symWindow e he P N).cells i) := by
      intro i
      have h1 : generatedSigmaAlgebra μ (symWindow e he P N) ≤ winSat e he P N := by
        rw [← generatedSigmaAlgebra_ksJoin_one he (symWindow e he P N)]
        exact le_iSup
          (fun k => generatedSigmaAlgebra μ (ksJoin he (symWindow e he P N) k)) 1
      exact h1 _ (measurableSet_generateFrom ⟨i, rfl⟩)
    have hWzero : condEntropy μ (winSat e he P N) (symWindow e he P N).cells = 0 :=
      condEntropy_eq_zero_of_measurable (hle N) (symWindow e he P N) hWcells
    have hrel : condEntropy μ (winSat e he P N) R.cells
        ≤ condEntropy μ (winSat e he P N) Q.cells := by
      rw [hRdef, joinPartition_cells]
      calc condEntropy μ (winSat e he P N) (joinCells Q.cells (symWindow e he P N).cells)
          ≤ condEntropy μ (winSat e he P N) Q.cells
              + condEntropy μ (winSat e he P N) (symWindow e he P N).cells :=
            condEntropy_join_le (hle N) Q (symWindow e he P N)
        _ = condEntropy μ (winSat e he P N) Q.cells := by rw [hWzero, add_zero]
    calc ksEntropyPartition he Q
        ≤ ksEntropyPartition he R := by
          rw [hRdef]; exact ksEntropyPartition_le_join he Q (symWindow e he P N)
      _ = ksEntropyPartition he (symWindow e he P N)
            + condKsEntropyPartition (hle N) he hinv R := hAR
      _ ≤ ksEntropyPartition he (symWindow e he P N)
            + condEntropy μ (winSat e he P N) R.cells := by
          have hb := condKsEntropyPartition_le_condEntropy (hle N) he hinv R
          gcongr
      _ ≤ ksEntropyPartition he (symWindow e he P N)
            + condEntropy μ (winSat e he P N) Q.cells := by gcongr
      _ = ksEntropyPartition he P + condEntropy μ (winSat e he P N) Q.cells := by
          rw [ksEntropyPartition_symWindow_eq e he P N]
  -- Pass `N → ∞`: the relative term vanishes by Lévy-upward continuity.
  haveI : Nonempty (Fin m) := Q.index_nonempty
  have hlim : Tendsto (fun N => condEntropy μ (winSat e he P N) Q.cells) atTop (𝓝 0) := by
    have h := condEntropy_tendsto_iSup (winSat e he P) (winSat_mono e he P) hle Q
    rwa [iSup_winSat_eq e he P hgen, condEntropy_full_eq_zero Q] at h
  have htend : Tendsto (fun N => ksEntropyPartition he P + condEntropy μ (winSat e he P N) Q.cells)
      atTop (𝓝 (ksEntropyPartition he P)) := by
    have h2 := (tendsto_const_nhds (x := ksEntropyPartition he P)).add hlim
    simpa using h2
  exact ge_of_tendsto' htend hperN

/-- **The two-sided Kolmogorov–Sinai generator theorem.** For a measure-preserving automorphism
`e : α ≃ᵐ α` of a standard Borel probability space and a *two-sided generating* finite partition `P`
(`IsGeneratingTwoSided e P`), the Kolmogorov–Sinai entropy of the system equals the
partition-relative entropy of `P`: `h(e) = h(e, P)`.

`le_antisymm` of the free bound `h(e, P) ≤ h(e)` (`le_ksEntropy`) and the reverse, which unfolds the
supremum defining `ksEntropy` and reduces by `iSup_le` to the continuity crux
`ksEntropyPartition_le_of_isGeneratingTwoSided`. Unlike the one-sided generator theorem this needs
no forward saturation; the two-sided saturation `hgen` is what makes the windowed Abramov–Rokhlin
limit valid, and invertibility enters only through the window-entropy invariance. -/
theorem ksEntropy_eq_ksEntropyPartition_of_isGeneratingTwoSided
    [StandardBorelSpace α] [IsProbabilityMeasure μ] (e : α ≃ᵐ α)
    (he : MeasurePreserving (⇑e) μ μ) {n : ℕ} (P : MeasurePartition μ (Fin n))
    (hgen : IsGeneratingTwoSided e P) :
    ksEntropy he = ((ksEntropyPartition he P : ℝ) : EReal) := by
  refine le_antisymm ?_ (le_ksEntropy he P)
  refine iSup_le fun m => iSup_le fun Q => ?_
  rw [EReal.coe_le_coe_iff]
  exact ksEntropyPartition_le_of_isGeneratingTwoSided e he P hgen Q

end Oseledets.Entropy
