/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Lyapunov.Extensions.ConstantCocycle
import Mathlib.LinearAlgebra.Matrix.Charpoly.Eigs
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# The full Lyapunov spectrum of a general constant cocycle (Yamamoto's theorem)

For a **constant** (non-symmetric) generator `A ≡ M` the iterated cocycle is the matrix power
`Mⁿ` (`Oseledets.cocycle_const`), so the `i`-th Lyapunov exponent of the cocycle is the
deterministic limit `lim_n (1/n) log σᵢ(Mⁿ)` of the normalized log singular values of the powers.

**Yamamoto's theorem** (Yamamoto, 1967; sharpened by Huang–Tam and others) identifies this limit:
for every matrix `M` and every sorted index `i`,
```
  lim_n (σᵢ(Mⁿ))^{1/n} = |λᵢ(M)|,
```
where `|λᵢ(M)|` is the `i`-th largest *eigenvalue modulus* of `M`, counted with (algebraic)
multiplicity. Equivalently, in logarithmic form,
```
  lim_n (1/n) log σᵢ(Mⁿ) = log |λᵢ(M)|.
```
Hence the `i`-th Lyapunov exponent of the constant cocycle generated by `M` is `log |λᵢ(M)|`. This
is the natural common generalization of two facts already in the library:
* the **symmetric** case `Oseledets.exponents_const`, where `|λᵢ(M)|` is the `i`-th sorted
  eigenvalue of `|M|` (and the singular values of `Mⁿ` are literally `|λ|ⁿ`); and
* the **top** exponent `= log (spectral radius)`, which is Yamamoto at `i = 0` (`s₁ = ‖·‖`).

## Status of this module

The arithmetic content **above** Yamamoto's limit — that the cocycle's `exponents … i` equals
`log |λᵢ(M)|` *given* the limit — is proved here **sorry-free** by uniqueness of limits, since
`exponents … i` is *defined* (in `Oseledets.Lyapunov.Extensions.Spectrum`) as the deterministic
limit of exactly the sequence `(1/n) log σᵢ(cocycle …) = (1/n) log σᵢ(Mⁿ)`.

Yamamoto's limit itself (`yamamoto_singularValues_tendsto`) is the **one** `BLOCKED` leaf. Its
proof is genuinely Mathlib-scale infrastructure that Mathlib does not yet have: it goes through the
multiplicative Jordan–Chevalley decomposition, the conjugation trick
`Wₙ = diag(1, n, …, n^{m-1})` collapsing the strictly-upper-triangular (nilpotent) part, the
trace-power identities `∑ᵢ |λᵢ|^p = limₙ tr(|Aⁿ|^{p/n})`, compactness of the limit points of
`{|Aⁿ|^{1/n}}` in the positive-semidefinite cone, and a multiset match of eigenvalue moduli via the
moments `tr(Hᵖ)`. See the reference below; none of polar `|Aⁿ|`, fractional matrix powers
`H^{p/n}`, or sorted complex-eigenvalue moduli-with-multiplicity is presently available.

## Main definitions

* `Oseledets.eigenvalueModuli M` — the moduli `|λ(M)|` of the (complex) eigenvalues of a real
  matrix `M`, counted with algebraic multiplicity and **sorted in non-increasing order** as a
  `List ℝ` of length `d`. The `i`-th largest modulus is `(eigenvalueModuli M).getD i 0`.

## Main results

* `Oseledets.eigenvalueModuli_length` — the list has length `d` (so `getD i 0` is the genuine
  `i`-th entry for `i < d`).
* `Oseledets.yamamoto_singularValues_tendsto` — **Yamamoto's theorem** (the only `BLOCKED` leaf):
  `(1/n) log σᵢ(Mⁿ) → log |λᵢ(M)|`.
* `Oseledets.exponents_const_general` — **the full spectrum of a general constant cocycle**
  (sorry-free *given* Yamamoto): `exponents (fun _ => M) … i = log |λᵢ(M)|`.

## References

* T. Yamamoto, *On the extreme values of the roots of matrices*, J. Math. Soc. Japan **19** (1967).
* H. Huang, T.-Y. Tam, *An extension of Yamamoto's theorem on the eigenvalues and singular values
  of a matrix*, J. Math. Soc. Japan **58** (2006).
* P. N. Dowla, S. Mukherjee, et al., *A stronger form of Yamamoto's theorem on singular values*,
  arXiv:2303.01252 (2023). (Theorem 3.8 / Corollary 3.9.)
-/

open MeasureTheory Filter Topology
open scoped Matrix

namespace Oseledets

variable {X : Type*} [MeasurableSpace X] {d : ℕ}

/-! ## The sorted eigenvalue moduli of a real matrix -/

/-- **The sorted eigenvalue moduli of a real matrix.** Mapping `M` into `Matrix _ _ ℂ` and taking
the roots of its characteristic polynomial gives the complex eigenvalues of `M` counted with
algebraic multiplicity; their moduli, sorted in non-increasing order, form the list
`eigenvalueModuli M : List ℝ`. The `i`-th largest eigenvalue modulus is
`(eigenvalueModuli M).getD i 0`. -/
noncomputable def eigenvalueModuli (M : Matrix (Fin d) (Fin d) ℝ) : List ℝ :=
  (((M.map (algebraMap ℝ ℂ)).charpoly.roots).map (fun z => ‖z‖)).sort (· ≥ ·)

/-- The sorted eigenvalue-moduli list has length `d`: the characteristic polynomial of the `d × d`
matrix `M` (over the algebraically closed field `ℂ`) is monic of degree `d` and therefore splits
with exactly `d` roots counted with multiplicity. -/
theorem eigenvalueModuli_length (M : Matrix (Fin d) (Fin d) ℝ) :
    (eigenvalueModuli M).length = d := by
  rw [eigenvalueModuli, Multiset.length_sort, Multiset.card_map]
  -- Over the algebraically closed field `ℂ` the charpoly splits, so its root multiset has
  -- cardinality equal to its degree `d`.
  have hsplits : ((M.map (algebraMap ℝ ℂ)).charpoly).Splits := IsAlgClosed.splits _
  rw [Polynomial.splits_iff_card_roots.mp hsplits, Matrix.charpoly_natDegree_eq_dim,
    Fintype.card_fin]

/-! ## Yamamoto's theorem (the single `BLOCKED` leaf) -/

/-- **Yamamoto's theorem (the singular-value / eigenvalue-modulus limit).**
For every real `d × d` matrix `M` and every sorted index `i`, the normalized log of the `i`-th
singular value of the power `Mⁿ` converges to `log` of the `i`-th largest eigenvalue modulus of
`M`:
```
  (1/n) · log σᵢ(Mⁿ)  →  log |λᵢ(M)|   as n → ∞.
```
Equivalently `(σᵢ(Mⁿ))^{1/n} → |λᵢ(M)|`. This is the classical theorem of Yamamoto (1967), in the
logarithmic form consumed by the Oseledets spectrum.

`BLOCKED`: Yamamoto's theorem is Mathlib-scale infrastructure not yet in Mathlib. Its proof
requires the multiplicative Jordan–Chevalley decomposition, the conjugation trick
`Wₙ = diag(1, n, …, n^{d-1})` collapsing the nilpotent part, the moment identities
`∑ᵢ |λᵢ|^p = limₙ tr(|Mⁿ|^{p/n})` for the polar parts `|Mⁿ| = √((Mⁿ)ᴴ Mⁿ)`, compactness of the
limit points of `{|Mⁿ|^{1/n}}` in the positive-semidefinite cone, and a multiset match of
eigenvalue moduli through the moments `tr(Hᵖ)` (Dowla–Mukherjee et al., arXiv:2303.01252,
Theorem 3.8 / Corollary 3.9). Mathlib currently lacks the polar decomposition of a matrix power,
fractional Hermitian matrix powers `H^{p/n}`, and sorted complex-eigenvalue moduli with
multiplicity, so this leaf is left as a precisely-stated assumption above which all the spectrum
arithmetic is discharged sorry-free. -/
theorem yamamoto_singularValues_tendsto (M : Matrix (Fin d) (Fin d) ℝ) (i : ℕ) :
    Tendsto (fun n : ℕ => (n : ℝ)⁻¹ *
        Real.log ((Matrix.toEuclideanLin (M ^ n)).singularValues i))
      atTop (𝓝 (Real.log ((eigenvalueModuli M).getD i 0))) :=
  sorry
  -- BLOCKED: Yamamoto's theorem (1967). Requires the multiplicative Jordan–Chevalley
  -- decomposition, polar parts |Mⁿ| of matrix powers, fractional Hermitian powers H^{p/n}, the
  -- trace-moment identities ∑ᵢ|λᵢ|^p = limₙ tr(|Mⁿ|^{p/n}), positive-semidefinite-cone
  -- compactness of {|Mⁿ|^{1/n}}, and sorted complex eigenvalue moduli with multiplicity — none of
  -- which is presently in Mathlib (Dowla–Mukherjee et al., arXiv:2303.01252, Thm 3.8 / Cor 3.9).

/-! ## The full Lyapunov spectrum of a general constant cocycle (given Yamamoto) -/

section Spectrum

variable {μ : Measure X} {T : X → X} [IsProbabilityMeasure μ] (hT : Ergodic T μ)
    {M : Matrix (Fin d) (Fin d) ℝ} (hdet : M.det ≠ 0) [NeZero d]

include hdet in
/-- **The full Lyapunov spectrum of a general (non-symmetric) constant cocycle.**
For an invertible real generator `M` (no symmetry assumed) and every sorted index `i`, the `i`-th
Lyapunov exponent of the constant cocycle `x ↦ M` is `log` of the `i`-th largest eigenvalue
modulus of `M`:
```
  exponents (fun _ => M) … i = log |λᵢ(M)|.
```

This is the **general** spectrum statement, of which the symmetric `Oseledets.exponents_const`
(where `|λᵢ(M)| = |M|.eigenvalues₀ i`) and the top-exponent (`i = 0`, the spectral radius) facts
are special cases.

The proof is by **uniqueness of limits**, given Yamamoto's theorem
(`yamamoto_singularValues_tendsto`): `exponents (fun _ => M) … i` is, by construction
(`Oseledets.exponents_tendsto_log_singularValue`), the limit of the sequence
`(1/n) log σᵢ(cocycle (fun _ => M) T n x)`, and the constant cocycle is the matrix power
(`Oseledets.cocycle_const`), so that sequence is exactly `(1/n) log σᵢ(Mⁿ)`, whose limit is
`log |λᵢ(M)|` by Yamamoto. As both sides are base-point independent, a single point extracted from
the (`NeBot`) a.e.-filter of the probability measure suffices. -/
theorem exponents_const_general (i : Fin d) :
    exponents hT (const_det_ne_zero hdet) (const_measurable M) (const_integrableLogNorm M)
        (const_integrableLogNorm_inv M) i
      = Real.log ((eigenvalueModuli M).getD (i : ℕ) 0) := by
  -- Extract a single point at which the σ-limit defining `exponents … i` holds.
  obtain ⟨x, hx⟩ := (exponents_tendsto_log_singularValue hT (const_det_ne_zero hdet)
    (const_measurable M) (const_integrableLogNorm M) (const_integrableLogNorm_inv M) i).exists
  -- Rewrite the constant cocycle as the matrix power inside the σ-sequence.
  have hcoc : ∀ n : ℕ,
      (Matrix.toEuclideanLin (cocycle (fun _ => M) T n x)).singularValues (i : ℕ)
        = (Matrix.toEuclideanLin (M ^ n)).singularValues (i : ℕ) := by
    intro n; rw [cocycle_const]
  -- Both `exponents … i` and `log |λᵢ(M)|` are the limit of the SAME sequence.
  have hx' : Tendsto (fun n : ℕ => (n : ℝ)⁻¹ *
      Real.log ((Matrix.toEuclideanLin (M ^ n)).singularValues (i : ℕ)))
      atTop (𝓝 (exponents hT (const_det_ne_zero hdet) (const_measurable M)
        (const_integrableLogNorm M) (const_integrableLogNorm_inv M) i)) := by
    refine hx.congr (fun n => ?_)
    rw [hcoc n]
  exact tendsto_nhds_unique hx' (yamamoto_singularValues_tendsto M (i : ℕ))

end Spectrum

end Oseledets
