/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Krieger.ZIterate

/-!
# The coding layer for Krieger's finite generator theorem: two-sided recovery (Krieger M3)

This file is the **σ-algebra recovery core** of Krieger's finite generator theorem. The classical
proof (Krieger 1970; Einsiedler–Lindenstrauss–Ward *Entropy in Ergodic Theory* §3) builds a finite
`Fin k`-valued partition `P` by *coding* the columns of a Rokhlin tower so that the two-sided
`P`-itinerary of a.e. point recovers its full itinerary under a fixed countable generator `Q`. The
combinatorial heart — that `log k > h` forces the number of `N`-names to be `≤ kᴺ` up to `ε`, so a
`Fin k` code exists — is supplied upstream (the name-count layer M2, the Rokhlin tower M1). What
remains, and is proved here unconditionally, is the **recovery half**: *once* a candidate code `P`
has the property that every cell of `Q` is measurable with respect to the two-sided
`P`-saturation, `P` two-sidedly generates whenever `Q` does.

## The two-sided saturation and its shift-invariance

For `e : α ≃ᵐ α` and a finite partition `P`, write
`twoSidedSat e P := ⨆ n : ℤ, comap (eⁿ) σ(P)`
for the σ-algebra generated by the whole two-sided `P`-itinerary
(`Oseledets.Krieger.IsGeneratingTwoSided e P` is exactly `twoSidedSat e P = mα`). The single
structural fact that drives everything is **shift-invariance**: pulling `twoSidedSat e P` back by
any iterate `eᵐ` lands inside `twoSidedSat e P` again, because reindexing the `ℤ`-supremum
`n ↦ n + m` is a bijection of `ℤ` (`comap_twoSidedSat_le`). This is precisely where two-sidedness
(`⨆` over `ℤ`, not `ℕ`) is load-bearing: a forward `ℕ`-supremum is *not* shift-invariant under the
backward iterate `e⁻¹`.

Shift-invariance immediately gives the **recovery / refinement-monotonicity** lemma: if every cell
of `Q` is `twoSidedSat e P`-measurable (`σ(Q) ≤ twoSidedSat e P`), then `Q`'s entire two-sided
saturation sits inside `P`'s (`twoSidedSat_mono_of_le`), so a generator `Q` lifts to a generator
`P` (`IsGeneratingTwoSided.of_le`). This is the two-sided analogue of
`Oseledets.Entropy.IsGenerating.mono_refine`.

## The coding interface consumed by the headline

The upstream coding construction is exposed to the headline through the predicate
`CodesTwoSided e Q P`, which packages exactly the recovery hypothesis `σ(Q) ≤ twoSidedSat e P`. The
headline (`Oseledets.Krieger.krieger_finite_generator`) takes the *existence* of a `Fin k`-valued
`P` with `CodesTwoSided e Q P` (the conclusion of the M1+M2 combinatorics) and concludes
`IsGeneratingTwoSided e P` via `CodesTwoSided.isGeneratingTwoSided`.

## Main definitions

* `Oseledets.Krieger.twoSidedSat`: the two-sided itinerary σ-algebra `⨆ n : ℤ, comap (eⁿ) σ(P)`.
* `Oseledets.Krieger.CodesTwoSided`: `P`'s two-sided itinerary recovers each cell of `Q`.

## Main results

* `Oseledets.Krieger.comap_twoSidedSat_le`: shift-invariance of the two-sided saturation.
* `Oseledets.Krieger.twoSidedSat_mono_of_le`: σ(Q) ≤ twoSidedSat e P ⟹ twoSidedSat e Q ≤
  twoSidedSat e P.
* `Oseledets.Krieger.IsGeneratingTwoSided.of_le`: recovery lifts a two-sided generator.
* `Oseledets.Krieger.CodesTwoSided.isGeneratingTwoSided`: a code of a two-sided generator is a
  two-sided generator.

## References

* Wolfgang Krieger, *On entropy and generators of measure-preserving transformations*,
  Trans. Amer. Math. Soc. **149** (1970), 453–464.
* Manfred Einsiedler, Elon Lindenstrauss and Thomas Ward, *Entropy in Ergodic Theory and
  Homogeneous Dynamics* (book in progress), §3 (the Krieger generator theorem).
* Eli Glasner, *Ergodic Theory via Joinings*, Math. Surveys Monogr. **101**, AMS (2003) — Krieger
  chapter.
* Tomasz Downarowicz, *Entropy in Dynamical Systems*, Cambridge (2011).
-/

open MeasureTheory Function MeasurableSpace

namespace Oseledets.Krieger

variable {α : Type*} {ι κ : Type*} [mα : MeasurableSpace α] [Fintype ι] [Fintype κ]
  {μ : Measure α}

open Oseledets.Entropy

/-- The **two-sided itinerary σ-algebra** of a finite partition `P` under the automorphism `e`:
the supremum, over all integer iterates `eⁿ` (`n : ℤ`), of the pulled-back generating σ-algebra
`σ(P)`. A set is `twoSidedSat e P`-measurable exactly when it is determined by the (two-sided)
`P`-itinerary `n ↦ (the cell of P containing eⁿ x)`. By definition, `P` two-sidedly generates
`(α, e, μ)` iff `twoSidedSat e P = mα`. Marked `@[reducible]` (its value is a `MeasurableSpace`, a
class type) so it unfolds for instance resolution and definitional rewriting, mirroring
`Oseledets.Entropy.generatedSigmaAlgebra`. -/
@[reducible]
noncomputable def twoSidedSat (e : α ≃ᵐ α) (P : MeasurePartition μ ι) : MeasurableSpace α :=
  ⨆ n : ℤ, MeasurableSpace.comap (ziter e n) (generatedSigmaAlgebra μ P)

@[simp]
lemma twoSidedSat_def (e : α ≃ᵐ α) (P : MeasurePartition μ ι) :
    twoSidedSat e P = ⨆ n : ℤ, MeasurableSpace.comap (ziter e n) (generatedSigmaAlgebra μ P) :=
  rfl

lemma isGeneratingTwoSided_iff (e : α ≃ᵐ α) (P : MeasurePartition μ ι) :
    IsGeneratingTwoSided e P ↔ twoSidedSat e P = mα := Iff.rfl

/-- **Shift-invariance of the two-sided saturation.** Pulling the two-sided itinerary σ-algebra
`twoSidedSat e P` back by any iterate `eᵐ` lands inside it again:
`comap (eᵐ) (twoSidedSat e P) ≤ twoSidedSat e P`.

A generator of `comap (eᵐ) (twoSidedSat e P)` is `eᵐ⁻¹` of a generator of one of the `ℤ`-terms,
namely `comap (eᵐ) (comap (eⁿ) σ(P)) = comap (eⁿ ∘ eᵐ) σ(P) = comap (e^{n+m}) σ(P)` (using
`ziter_add`), which is the `(n + m)`-th term of the same `ℤ`-supremum. This is *exactly* where the
two-sided (`ℤ`) indexing is essential: the reindexing `n ↦ n + m` is a bijection of `ℤ`, so no
terms are lost — a forward (`ℕ`) supremum would lose terms under a backward shift. -/
theorem comap_twoSidedSat_le (e : α ≃ᵐ α) (P : MeasurePartition μ ι) (m : ℤ) :
    MeasurableSpace.comap (ziter e m) (twoSidedSat e P) ≤ twoSidedSat e P := by
  rw [twoSidedSat_def, MeasurableSpace.comap_iSup]
  refine iSup_le fun n => ?_
  rw [MeasurableSpace.comap_comp, ← ziter_add]
  exact le_iSup (fun k : ℤ => MeasurableSpace.comap (ziter e k) (generatedSigmaAlgebra μ P)) (n + m)

/-- **Recovery / refinement monotonicity for two-sided generation.** If every cell of `Q` is
measurable with respect to the two-sided `P`-saturation (`σ(Q) ≤ twoSidedSat e P` — the
`P`-itinerary recovers each `Q`-cell), then the *entire* two-sided saturation of `Q` sits inside
that of `P`:
`twoSidedSat e Q ≤ twoSidedSat e P`.

Each `ℤ`-term `comap (eᵐ) σ(Q)` of `twoSidedSat e Q` is bounded, by `comap`-monotonicity in the
hypothesis, by `comap (eᵐ) (twoSidedSat e P)`, which is `≤ twoSidedSat e P` by shift-invariance
(`comap_twoSidedSat_le`). Taking the supremum over `m` gives the claim. -/
theorem twoSidedSat_mono_of_le (e : α ≃ᵐ α) (P : MeasurePartition μ ι) (Q : MeasurePartition μ κ)
    (hrec : generatedSigmaAlgebra μ Q ≤ twoSidedSat e P) :
    twoSidedSat e Q ≤ twoSidedSat e P := by
  rw [twoSidedSat_def (P := Q)]
  refine iSup_le fun m => ?_
  exact le_trans (MeasurableSpace.comap_mono hrec) (comap_twoSidedSat_le e P m)

/-- **Recovery lifts a two-sided generator.** If `Q` two-sidedly generates `(α, e, μ)` and the
two-sided `P`-itinerary recovers each cell of `Q` (`σ(Q) ≤ twoSidedSat e P`), then `P` two-sidedly
generates as well.

The ambient σ-algebra always dominates `twoSidedSat e P` (each cell of `P` is measurable, so
`σ(P) ≤ mα`, hence every term `comap (eⁿ) σ(P) ≤ mα`). For the reverse inclusion,
`mα = twoSidedSat e Q ≤ twoSidedSat e P` by `Q`'s generation and `twoSidedSat_mono_of_le`;
antisymmetry pins `twoSidedSat e P = mα`. This is the two-sided analogue of
`Oseledets.Entropy.IsGenerating.mono_refine`. -/
theorem IsGeneratingTwoSided.of_le {e : α ≃ᵐ α} {P : MeasurePartition μ ι}
    {Q : MeasurePartition μ κ} (hQ : IsGeneratingTwoSided e Q)
    (hrec : generatedSigmaAlgebra μ Q ≤ twoSidedSat e P) :
    IsGeneratingTwoSided e P := by
  rw [isGeneratingTwoSided_iff]
  -- `twoSidedSat e P ≤ mα`: each cell of `P` is measurable.
  have hP_le : generatedSigmaAlgebra μ P ≤ mα := by
    refine MeasurableSpace.generateFrom_le ?_
    rintro s ⟨i, rfl⟩
    exact P.measurable i
  have hsat_le : twoSidedSat e P ≤ mα := by
    rw [twoSidedSat_def]
    refine iSup_le fun n => ?_
    exact le_trans (MeasurableSpace.comap_mono hP_le) (measurable_ziter e n).comap_le
  -- `mα = twoSidedSat e Q ≤ twoSidedSat e P`.
  refine le_antisymm hsat_le ?_
  calc mα = twoSidedSat e Q := ((isGeneratingTwoSided_iff e Q).mp hQ).symm
    _ ≤ twoSidedSat e P := twoSidedSat_mono_of_le e P Q hrec

/-- **The coding predicate.** A finite `Fin k`-valued (or `ι`-valued) partition `P` *codes* a
partition `Q` two-sidedly under `e` when the two-sided `P`-itinerary recovers every cell of `Q`:
each cell of `Q` is measurable with respect to `twoSidedSat e P`.

This is the exact conclusion of the Krieger coding construction (Rokhlin tower + name count): the
column-coding partition `P` is built so that, off a null set, the two-sided `P`-itinerary of a
point determines its `Q`-itinerary, hence in particular which `Q`-cell it lies in. The headline
consumes the *existence* of such a `P` and turns it into a generator via
`CodesTwoSided.isGeneratingTwoSided`. -/
def CodesTwoSided (e : α ≃ᵐ α) (Q : MeasurePartition μ κ) (P : MeasurePartition μ ι) : Prop :=
  generatedSigmaAlgebra μ Q ≤ twoSidedSat e P

/-- A code of a two-sided generator is itself a two-sided generator — the headline reduction.
Immediate from `IsGeneratingTwoSided.of_le` and the definition of `CodesTwoSided`. -/
theorem CodesTwoSided.isGeneratingTwoSided {e : α ≃ᵐ α} {Q : MeasurePartition μ κ}
    {P : MeasurePartition μ ι} (hQ : IsGeneratingTwoSided e Q) (hP : CodesTwoSided e Q P) :
    IsGeneratingTwoSided e P :=
  IsGeneratingTwoSided.of_le hQ hP

/-- **Reflexivity of coding.** Every partition codes itself two-sidedly: its own static σ-algebra
`σ(Q)` is the `n = 0` term `comap (e⁰) σ(Q) = comap id σ(Q) = σ(Q)` of its two-sided saturation,
hence `σ(Q) ≤ twoSidedSat e Q`. (Sanity check: a two-sided generator codes itself, recovering
`IsGeneratingTwoSided e Q` from itself.) -/
theorem codesTwoSided_self (e : α ≃ᵐ α) (Q : MeasurePartition μ κ) : CodesTwoSided e Q Q := by
  rw [CodesTwoSided, twoSidedSat_def]
  refine le_trans (le_of_eq ?_) (le_iSup _ (0 : ℤ))
  rw [ziter_zero, MeasurableSpace.comap_id]

end Oseledets.Krieger
